project_id = "guqgszwelffntrgtsycm"

[functions.create-customer]
verify_jwt = false

[functions.reset-customer-password]
verify_jwt = false

[functions.create-company]
verify_jwt = false

[functions.create-super-admin]
verify_jwt = false

[functions.create-company-staff]
verify_jwt = false

[functions.create-salesperson-user]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false