// AUTO-GENERATO da /tmp/convert_to_builder.mjs — contenuto delle 58 email di sistema
// (copy riscritti utente, contenuto centrale + {{variabili}}). Fonte di verità del
// DEFAULT mostrato nel builder e del FALLBACK usato dall'invio quando non c'è
// override in platform_email_templates. NON modificare a mano.
/* eslint-disable */
export interface SystemEmailContent { subject: string; html_body: string; text_body: string; }
export const SYSTEM_EMAIL_CONTENT: Record<string, SystemEmailContent> = {
  "welcome": {
    "subject": "{{company.name}} è pronta su Edilizia in Cloud",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Benvenuto, {{user.first_name}}.</h1><p style=\"margin:0 0 16px;\">Da oggi {{company.name}} ha il suo gestionale. Cantieri, fatture, DDT, clienti e team in un posto solo — accessibile anche dal cantiere, col telefono in mano.</p>\n<p style=\"margin:0 0 16px;\">Il tuo account è attivo con ruolo <strong>{{user.role_label}}</strong>. Al primo accesso imposti la password e sei operativo:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password e accedi</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Un consiglio da chi conosce il mestiere: parti creando il primo cantiere e caricando un cliente. Da lì il resto viene da sé.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Ti serve una mano per partire? Rispondi a questa email: dall'altra parte c'è una persona vera.</p>",
    "text_body": ""
  },
  "terms_accepted": {
    "subject": "La tua copia dei documenti, {{user.first_name}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">I documenti che hai accettato</h1><p style=\"margin:0 0 16px;\">Quando hai registrato {{company.name}} hai accettato le condizioni del servizio. Qui sotto trovi la tua copia: tienila da parte, è il riferimento di cosa hai sottoscritto.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Accettazione registrata il {{event.date}} alle {{event.time}}.</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">Termini e Condizioni del Servizio — <a href=\"{{link_url_1}}\">apri</a></li><li style=\"margin:0 0 8px;\">Privacy Policy — <a href=\"{{link_url_2}}\">apri</a></li><li style=\"margin:0 0 8px;\">Accordo trattamento dati (DPA) — <a href=\"{{link_url_3}}\">apri</a></li><li style=\"margin:0 0 8px;\">Cookie Policy — <a href=\"{{link_url_4}}\">apri</a></li></ul>\n<p style=\"margin:0 0 16px;\">Un documento in più, che serve a te: quando i tuoi operai usano l'app (GPS, timbrature) devi consegnare loro l'informativa privacy. Te la lasciamo già pronta, da firmare e archiviare.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_5}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri i tuoi documenti</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "staff_access": {
    "subject": "Il tuo accesso a {{company.name}} è pronto",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Benvenuto in {{company.name}}</h1><p style=\"margin:0 0 16px;\">{{inviter.name}} ti ha creato un account su Edilizia in Cloud, il gestionale che {{company.name}} usa per cantieri, clienti e documenti.</p>\n<p style=\"margin:0 0 16px;\">Per entrare imposta la tua password: è personale, la vedi solo tu.</p>\n<p style=\"margin:0 0 8px;font-size:14px;\">Accedi con: <code style=\"background:#f1f5f9;padding:3px 10px;border-radius:5px;font-size:14px;\">{{user.email}}</code></p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore. Scaduto, usa “Password dimenticata” dalla pagina di accesso.</p>",
    "text_body": ""
  },
  "employee_account": {
    "subject": "Il tuo accesso a {{company.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, {{company.name}} ti ha aperto un account su Edilizia in Cloud. Da qui timbri le ore, vedi i cantieri assegnati e carichi le foto dei lavori — tutto dal telefono.</p>\n<p style=\"margin:0 0 16px;\">Imposta la password e sei operativo:</p>\n<p style=\"margin:0 0 8px;font-size:14px;\">Accedi con: <code style=\"background:#f1f5f9;padding:3px 10px;border-radius:5px;font-size:14px;\">{{user.email}}</code></p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore.</p>",
    "text_body": ""
  },
  "salesperson_account": {
    "subject": "Il tuo accesso a {{company.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, {{company.name}} ti ha aperto un account commerciale su Edilizia in Cloud. Da qui gestisci preventivi, clienti e il tuo portafoglio commesse.</p>\n<p style=\"margin:0 0 16px;\">Imposta la password e parti:</p>\n<p style=\"margin:0 0 8px;font-size:14px;\">Accedi con: <code style=\"background:#f1f5f9;padding:3px 10px;border-radius:5px;font-size:14px;\">{{user.email}}</code></p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore.</p>",
    "text_body": ""
  },
  "password_reset": {
    "subject": "Reimposta la tua password",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Reimposta la password</h1><p style=\"margin:0 0 16px;\">Hai chiesto di reimpostare la password del tuo account. Nessun problema: creane una nuova da qui.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Crea una nuova password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link scade tra 24 ore. Se non hai richiesto tu il reset, ignora questa email: la password resta quella di prima.</p>",
    "text_body": ""
  },
  "password_reset_admin": {
    "subject": "La tua password è stata reimpostata",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, un amministratore di {{company.name}} ha reimpostato il tuo accesso. Per sicurezza la nuova password la scegli tu, in un passaggio:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la nuova password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non te l'aspettavi? Scrivici a {{platform.support_email}}.</p>",
    "text_body": ""
  },
  "password_changed": {
    "subject": "La tua password è stata cambiata",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">La tua password è stata cambiata</h1><p style=\"margin:0 0 16px;\">La password del tuo account {{company.name}} è stata cambiata il <strong>{{event.date}}</strong> alle <strong>{{event.time}}</strong>.</p>\n<p style=\"margin:0 0 16px;\">Se sei stato tu, è tutto a posto: non devi fare nulla.</p>\n<p style=\"margin:0 0 16px;\">Se <strong>non</strong> sei stato tu, qualcuno potrebbe avere accesso al tuo account. Scrivici subito a <a href='mailto:{{platform.support_email}}'>{{platform.support_email}}</a>: blocchiamo l'accesso e lo mettiamo in sicurezza.</p>",
    "text_body": ""
  },
  "otp_login": {
    "subject": "Codice di accesso: {{otp.code}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Il tuo codice di sicurezza</h1><p style=\"margin:0 0 16px;\">Hai inserito la password giusta. Per completare l'accesso digita questo codice:</p>\n<div style=\"margin:8px 0 18px;text-align:center;\"><span style=\"display:inline-block;font-family:monospace;font-size:34px;letter-spacing:8px;font-weight:700;color:#1E3A5F;background:#f1f5f9;border:1px dashed #cbd5e1;border-radius:10px;padding:14px 26px;\">{{otp.code}}</span></div>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Scade tra 15 minuti. Se non stai accedendo tu, qualcuno conosce la tua password: cambiala subito.</p>",
    "text_body": ""
  },
  "email_change_old": {
    "subject": "Hai cambiato l'email di accesso?",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Richiesta di cambio email</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, è stata richiesta la modifica dell'email di accesso del tuo account {{company.name}}, verso <strong>{{user.new_email}}</strong>.</p>\n<p style=\"margin:0 0 16px;\">Se sei stato tu, non devi fare nulla: appena confermi dal nuovo indirizzo, l'accesso si sposta lì.</p>\n<p style=\"margin:0 0 16px;\">Se <strong>non</strong> sei stato tu, qualcuno sta cercando di prenderti l'account. Annulla subito:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Non sono stato io — blocca il cambio</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Per sicurezza inviamo questo avviso anche al nuovo indirizzo.</p>",
    "text_body": ""
  },
  "email_change_new": {
    "subject": "Conferma il tuo nuovo indirizzo email",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, per completare il cambio email del tuo account {{company.name}}, conferma che questo nuovo indirizzo è tuo.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Conferma il nuovo indirizzo</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Finché non confermi, l'accesso resta sull'email precedente. Link valido 24 ore.</p>",
    "text_body": ""
  },
  "twofa_enabled": {
    "subject": "Verifica in due passaggi attivata",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, hai attivato la verifica in due passaggi sul tuo account {{company.name}}. Da ora, a ogni accesso, oltre alla password serve un codice temporaneo: anche se qualcuno indovinasse la password, senza il codice non entra.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non sei stato tu ad attivarla? Scrivici a {{platform.support_email}}.</p>",
    "text_body": ""
  },
  "twofa_disabled": {
    "subject": "Verifica in due passaggi disattivata",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, la verifica in due passaggi sul tuo account {{company.name}} è stata disattivata. Da ora per entrare basta la password.</p>\n<p style=\"margin:0 0 16px;\">Se non sei stato tu, riattivala e cambia la password: qualcuno potrebbe avere accesso.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riattiva la protezione</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "new_device_login": {
    "subject": "Nuovo accesso al tuo account",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Abbiamo notato un nuovo accesso</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, qualcuno ha effettuato l'accesso al tuo account {{company.name}}:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🖥 Dispositivo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{device.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📍 Posizione</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{device.location}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🕐 Quando</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{event.date}} alle {{event.time}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Se sei stato tu, ignora pure questa email.</p>\n<p style=\"margin:0 0 16px;\">Se non ti riconosci, cambia subito la password: mettiamo in sicurezza l'account.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Non sono stato io</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "account_locked": {
    "subject": "Account bloccato temporaneamente",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo bloccato l'accesso al tuo account {{company.name}} dopo diversi tentativi falliti. È una protezione automatica contro chi prova a indovinare la password.</p>\n<p style=\"margin:0 0 16px;\">Puoi riprovare tra qualche minuto. Se non ricordi la password, reimpostala subito:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Reimposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non hai provato a entrare tu? Reimposta la password per sicurezza.</p>",
    "text_body": ""
  },
  "user_invited": {
    "subject": "{{inviter.name}} ti ha invitato su Edilizia in Cloud",
    "html_body": "<p style=\"margin:0 0 16px;\">{{inviter.name}} ti ha invitato a entrare in Edilizia in Cloud come <strong>{{user.role_label}}</strong>. Accetta e crea il tuo account: bastano due minuti.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Accetta l'invito</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Vale 7 giorni. Se non riconosci la richiesta, ignora l'email.</p>",
    "text_body": ""
  },
  "accountant_invite": {
    "subject": "{{company.name}} ti ha aggiunto come commercialista",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{accountant.name}}, {{inviter.name}} di {{company.name}} ti ha dato accesso come commercialista, con livello <strong>{{access.level}}</strong>. Da qui vedi fatture e documenti dell'azienda senza più rincorrerli via email.</p>\n<p style=\"margin:0 0 16px;\">Non hai ancora un account studio? Lo apri in 60 secondi e l'azienda compare subito tra i tuoi clienti.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Accetta e accedi</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">{{company.name}} non avrà mai accesso ai dati del tuo studio.</p>",
    "text_body": ""
  },
  "invite_reminder": {
    "subject": "Ti aspettano su {{company.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">{{inviter.name}} ti ha invitato su {{company.name}} qualche giorno fa, ma non sei ancora entrato. Manca solo che imposti la password — poi accedi ai cantieri.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Completa l'accesso</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Link scaduto? Chiedi a {{inviter.name}} di rimandartelo.</p>",
    "text_body": ""
  },
  "account_verify": {
    "subject": "Conferma la tua email per attivare l'account",
    "html_body": "<p style=\"margin:0 0 16px;\">Ci siamo quasi. Conferma che questo è il tuo indirizzo e attiviamo subito il tuo account su {{company.name}}.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Conferma l'email</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link è valido 24 ore. Non hai creato tu questo account? Ignora pure.</p>",
    "text_body": ""
  },
  "invite_accepted_admin": {
    "subject": "{{user.full_name}} è entrato in {{company.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, <strong>{{user.full_name}}</strong> ha accettato l'invito ed è ora attivo su {{company.name}} con ruolo <strong>{{user.role_label}}</strong>.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Gestisci il team</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Vuoi cambiargli i permessi? Lo fai dalla sezione Persone & Accessi.</p>",
    "text_body": ""
  },
  "role_changed": {
    "subject": "Il tuo ruolo su {{company.name}} è cambiato",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, il tuo ruolo su {{company.name}} è stato aggiornato a <strong>{{user.role_label}}</strong>. A seconda del ruolo cambia cosa puoi vedere e modificare nella piattaforma.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Accedi e dai un'occhiata</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Qualcosa non torna? Parlane con chi gestisce gli accessi in azienda.</p>",
    "text_body": ""
  },
  "user_removed": {
    "subject": "Il tuo accesso a {{company.name}} è stato revocato",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, il tuo accesso a {{company.name}} su Edilizia in Cloud è stato rimosso. Da questo momento non puoi più entrare nei cantieri e nei documenti dell'azienda.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Pensi sia un errore? Contatta chi gestisce gli accessi in {{company.name}}.</p>",
    "text_body": ""
  },
  "invite_expired": {
    "subject": "Il tuo invito a {{company.name}} è scaduto",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, l'invito a entrare in {{company.name}} è scaduto prima che lo accettassi. Capita.</p>\n<p style=\"margin:0 0 16px;\">Per riaverlo chiedi a {{inviter.name}} di rimandartelo: ci mette dieci secondi.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Gli inviti scadono per sicurezza, così nessun link resta valido all'infinito.</p>",
    "text_body": ""
  },
  "setup_incomplete": {
    "subject": "Manca poco per partire, {{user.first_name}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Manca poco per partire</h1><p style=\"margin:0 0 16px;\">Hai aperto l'account ma il setup di {{company.name}} è a metà. Ti restano due cose, cinque minuti in tutto:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">Completare i dati per le fatture (così emetti la prima senza intoppi)</li><li style=\"margin:0 0 8px;\">Creare il primo cantiere</li></ul>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Completa il setup</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Ti si blocca qualcosa? Rispondi a questa email, ti diamo una mano noi.</p>",
    "text_body": ""
  },
  "lifecycle_trial_ending": {
    "subject": "Il tuo trial scade tra {{trial.days_left}} giorni",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Mancano {{trial.days_left}} giorni, {{user.first_name}}</h1><p style=\"margin:0 0 16px;\">Il periodo di prova sta per finire. Intanto guarda cosa hai già messo dentro:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Commesse create</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{stats.orders}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">👥 Clienti gestiti</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{stats.customers}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Quando il trial scade l'accesso si ferma e questi dati restano in attesa. Attiva un piano e continui da dove sei, senza perdere niente.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Attiva un piano</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Domande prima di decidere? Rispondi qui.</p>",
    "text_body": ""
  },
  "lifecycle_payment_failed": {
    "subject": "Pagamento non riuscito — sistemalo in 1 minuto",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, non siamo riusciti ad addebitare {{subscription.amount}} per l'abbonamento di {{company.name}} (tentativo {{dunning.attempt}}).</p>\n<p style=\"margin:0 0 16px;\">Di solito è solo una carta scaduta o un plafond momentaneo. Aggiorna il metodo e risolviamo in un minuto — prima che l'account venga sospeso.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Aggiorna il pagamento</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Riproviamo in automatico nei prossimi giorni. Se ti serve aiuto, rispondi a questa email.</p>",
    "text_body": ""
  },
  "purchase_confirmed": {
    "subject": "Abbonamento attivo: bentornato operativo",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Il tuo abbonamento è attivo</h1><p style=\"margin:0 0 16px;\">Grazie {{user.first_name}}. L'abbonamento di {{company.name}} è attivo: hai tutta la piattaforma, senza i limiti del periodo di prova.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Piano</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{plan.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🔁 Fatturazione</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.periodicity}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vai alla dashboard</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">La ricevuta arriva in una mail separata.</p>",
    "text_body": ""
  },
  "payment_received": {
    "subject": "Ricevuta pagamento · {{company.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo ricevuto il pagamento dell'abbonamento di {{company.name}}.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💳 Metodo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.method}} ••{{card.last4}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Data</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{event.date}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Scarica la fattura</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Conserva questa email per la contabilità.</p>",
    "text_body": ""
  },
  "renewal_upcoming": {
    "subject": "Tra pochi giorni si rinnova l'abbonamento",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, ti avvisiamo in anticipo: l'abbonamento di {{company.name}} si rinnova il <strong>{{subscription.renewal_date}}</strong> per {{subscription.amount}}, sullo stesso metodo di pagamento.</p>\n<p style=\"margin:0 0 16px;\">Va bene così? Non devi fare nulla. Vuoi cambiare piano o metodo? Fallo prima del rinnovo:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Gestisci l'abbonamento</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "card_expiring": {
    "subject": "La carta sta per scadere",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, la carta che usi per l'abbonamento di {{company.name}} (••{{card.last4}}) scade a breve. Aggiornala adesso, così al prossimo rinnovo non si blocca niente.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Aggiorna la carta</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Ci vuole un minuto. Meglio ora che con l'account sospeso.</p>",
    "text_body": ""
  },
  "trial_expired": {
    "subject": "Il tuo trial è finito — i dati sono al sicuro",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, il periodo di prova di {{company.name}} è terminato e l'accesso è in pausa. I tuoi dati — commesse, clienti, documenti — sono tutti lì, intatti.</p>\n<p style=\"margin:0 0 16px;\">Quando sei pronto, attivi un piano e riparti esattamente da dove avevi lasciato.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riattiva l'account</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Conserviamo i dati per un periodo limitato: non aspettare troppo per non rischiare di perderli.</p>",
    "text_body": ""
  },
  "plan_changed": {
    "subject": "Piano aggiornato: ora sei su {{plan.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, il piano di {{company.name}} è stato aggiornato a <strong>{{plan.name}}</strong>. La modifica è attiva da subito.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Nuovo piano</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{plan.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🔁 Prossimo rinnovo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.renewal_date}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi cosa è cambiato</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "subscription_cancelled": {
    "subject": "Abbonamento cancellato — ci dispiace vederti andare",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo registrato la cancellazione dell'abbonamento di {{company.name}}. Continui a usare tutto fino al <strong>{{subscription.renewal_date}}</strong>: dopo, l'account va in pausa e i dati restano in attesa.</p>\n<p style=\"margin:0 0 16px;\">Se cambi idea, riattivi con un click prima di quella data.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Ho ripensato — riattiva</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Un minuto per dirci cosa non ha funzionato? Rispondi a questa email: leggo tutto io.</p>",
    "text_body": ""
  },
  "account_suspended": {
    "subject": "Account sospeso — riattivalo ora",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Account in pausa</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, dopo diversi tentativi non siamo riusciti a incassare l'abbonamento di {{company.name}}, quindi l'account è stato sospeso. L'accesso è bloccato, ma i tuoi dati sono ancora tutti lì.</p>\n<p style=\"margin:0 0 16px;\">Aggiorna il pagamento e torni operativo all'istante:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Aggiorna e riattiva</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">I dati restano disponibili per un periodo limitato. Riattiva prima di rischiare di perderli.</p>",
    "text_body": ""
  },
  "refund_issued": {
    "subject": "Rimborso di {{payment.amount}} in arrivo",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo emesso un rimborso di {{payment.amount}} sull'abbonamento di {{company.name}}.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💳 Su</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.method}} ••{{card.last4}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Riferimento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.reference}}</td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Arriva entro 5-10 giorni lavorativi, secondo i tempi della tua banca.</p>",
    "text_body": ""
  },
  "partner_welcome": {
    "subject": "Sei dentro: benvenuto tra i partner di Edilizia in Cloud",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Benvenuto tra i partner 🎉</h1><p style=\"margin:0 0 16px;\">Ciao {{user.full_name}}, da oggi sei partner <strong>{{partner.tier}}</strong>. Te lo spiego in due righe.</p>\n<p style=\"margin:0 0 16px;\">Ogni azienda che si registra col tuo link ti riconosce il <strong>{{partner.commission}}</strong> del suo abbonamento — ogni mese, finché resta cliente. Non una tantum: ricorrente.</p>\n<p style=\"margin:0 0 8px;font-size:14px;\">Il tuo codice: <code style=\"background:#f1f5f9;padding:3px 10px;border-radius:5px;font-size:14px;\">{{referral.code}}</code></p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vai alla dashboard partner</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Lì trovi il link da condividere e segui le conversioni in tempo reale.</p>",
    "text_body": ""
  },
  "partner_conversion": {
    "subject": "Nuova conversione: {{company.name}} si è registrata 🚀",
    "html_body": "<p style=\"margin:0 0 16px;\">Ottimo lavoro, {{user.full_name}}. {{company.name}} si è appena registrata usando il tuo link.</p>\n<p style=\"margin:0 0 16px;\">Da qui in poi, finché resta cliente, entra nelle tue commissioni ricorrenti. Il primo accredito parte dal prossimo ciclo di calcolo.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi le tue conversioni</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "partner_commission": {
    "subject": "Le tue commissioni di {{period.month}} sono pronte 💰",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.full_name}}, abbiamo chiuso il mese. Ecco quanto hai maturato:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💰 Commissioni {{period.month}}</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{commission.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🏢 Aziende attive</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{partner.active_companies}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Richiedi il pagamento</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "partner_payout": {
    "subject": "Pagamento di {{payout.amount}} approvato ✅",
    "html_body": "<p style=\"margin:0 0 16px;\">Ci siamo, {{user.full_name}}. Il tuo pagamento di {{payout.amount}} è stato approvato e parte il bonifico.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">✅ Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payout.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Riferimento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.reference}}</td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Arriva entro 3-5 giorni lavorativi. Lo trovi anche nello storico della dashboard.</p>",
    "text_body": ""
  },
  "partner_tier": {
    "subject": "Sei salito a {{partner.new_tier}} 🎊",
    "html_body": "<p style=\"margin:0 0 16px;\">Complimenti {{user.full_name}}: hai raggiunto il tier <strong>{{partner.new_tier}}</strong>. Hai portato abbastanza aziende da sbloccare un guadagno più alto.</p>\n<p style=\"margin:0 0 16px;\">Da adesso ogni commissione vale <strong>{{partner.multiplier}}</strong> in più. Vale anche sulle aziende che hai già portato.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi il nuovo tier</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "document_shared": {
    "subject": "{{sender.name}} ha condiviso un documento con te",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, {{sender.name}} ha condiviso un documento con te su {{company.name}}:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📄 Documento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.name}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri il documento</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Lo trovi anche nella sezione documenti del cantiere.</p>",
    "text_body": ""
  },
  "task_assigned": {
    "subject": "Hai una nuova attività: {{task.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, {{sender.name}} ti ha assegnato un'attività su {{company.name}}:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">✅ Attività</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{task.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Scadenza</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{task.due_date}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri l'attività</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "report_ready": {
    "subject": "Il tuo report è pronto",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, il report che hai richiesto su {{company.name}} è pronto:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📊 Report</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.name}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Scarica il report</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Resta disponibile nella tua dashboard.</p>",
    "text_body": ""
  },
  "silvio_approval": {
    "subject": "Silvio ha bisogno del tuo ok",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Una cosa da approvare</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, Silvio ha preparato un'azione per {{company.name}} ed è in attesa del tuo via libera prima di eseguirla:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">⚙️ Azione</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{task.name}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Dai un'occhiata: se va bene, approvi con un click. Se no, la blocchi. Niente parte senza il tuo ok.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Rivedi e approva</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Hai tempo per decidere: finché non approvi, Silvio resta fermo.</p>",
    "text_body": ""
  },
  "sdi_accepted": {
    "subject": "Fattura {{invoice.number}} consegnata ✅",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, la fattura {{invoice.number}} di {{company.name}} è stata accettata dal Sistema di Interscambio ed è ufficialmente trasmessa al cliente.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Fattura</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{invoice.number}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">✅ Stato</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">Consegnata</td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">La ricevuta di consegna è archiviata nel CassettoSDI.</p>",
    "text_body": ""
  },
  "sdi_rejected": {
    "subject": "⚠️ Fattura {{invoice.number}} scartata dallo SDI",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">La fattura è stata scartata</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, lo SDI ha scartato la fattura {{invoice.number}} di {{company.name}}. Tradotto: per il Fisco al momento <strong>non è stata emessa</strong>. Va corretta e rinviata, possibilmente in giornata.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Fattura</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{invoice.number}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">❌ Motivo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{sdi.reject_reason}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Apri la fattura, sistema il punto segnalato e rimandala: te lo facciamo fare in due click.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Correggi e rinvia</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Hai 5 giorni dalla notifica di scarto per rinviarla mantenendo la data originale.</p>",
    "text_body": ""
  },
  "payment_reminder": {
    "subject": "Promemoria: fattura {{invoice.number}} in scadenza",
    "html_body": "<p style=\"margin:0 0 16px;\">Gentile {{customer.name}}, le ricordiamo che la fattura {{invoice.number}} emessa da {{company.name}} è in scadenza:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Fattura</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{invoice.number}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Scadenza</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.expiry_date}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Se ha già provveduto, ignori questo promemoria. In caso contrario, può saldare con i riferimenti che trova in fattura.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Messaggio inviato automaticamente da {{company.name}} tramite Edilizia in Cloud.</p>",
    "text_body": ""
  },
  "document_expiring": {
    "subject": "{{document.type}} in scadenza tra {{document.days_left}} giorni",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Un documento sta per scadere</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, un documento di {{company.name}} sta per scadere. Senza, rischi di doverti fermare in cantiere o di restare fuori da una gara:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📋 Documento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.type}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Scade il</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.expiry_date}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">⏳ Mancano</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.days_left}} giorni</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi il documento</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Te lo ricordiamo in anticipo, così hai il tempo di rinnovarlo con calma.</p>",
    "text_body": ""
  },
  "site_inspection": {
    "subject": "Sopralluogo fissato: {{inspection.date}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, è stato fissato un sopralluogo per {{company.name}}:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Data</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{inspection.date}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🕐 Ora</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{inspection.time}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📍 Dove</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{site.address}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri il sopralluogo</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Da qui vedi la scheda e, sul posto, compili il rilievo direttamente dal telefono.</p>",
    "text_body": ""
  },
  "lifecycle_monthly_summary": {
    "subject": "Il tuo mese su Edilizia in Cloud · {{period.month}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Com'è andato {{period.month}}</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, due numeri sul tuo mese — quelli che contano:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Commesse gestite</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{stats.orders}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Fatturato</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{stats.revenue}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">⏱ Ore risparmiate vs carta/Excel</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">~{{stats.hours_saved}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri la dashboard</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "lifecycle_d3_no_activation": {
    "subject": "Ti aiuto a partire, {{user.first_name}}?",
    "html_body": "<p style=\"margin:0 0 16px;\">Hai aperto l'account di {{company.name}} qualche giorno fa, ma il setup è fermo. Capita: il cantiere chiama. Però bastano 5 minuti per essere operativo. Tre passi:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">Aggiungi il primo cliente</li><li style=\"margin:0 0 8px;\">Crea la prima commessa</li><li style=\"margin:0 0 8px;\">Invita il tuo team</li></ul>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riprendi da qui</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Rispondi a questa email e ti seguo io, passo passo.</p>",
    "text_body": ""
  },
  "lifecycle_d7_features": {
    "subject": "3 funzioni di EiC che ti fanno guadagnare ore",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">3 superpoteri che forse non conosci</h1><p style=\"margin:0 0 16px;\">È passata una settimana, {{user.first_name}}. Ti mostro tre cose che gli imprenditori più rapidi su EiC usano ogni giorno:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\"><strong>Render AI</strong> — Foto del cantiere → render fotorealistico in 90 secondi.</li><li style=\"margin:0 0 8px;\"><strong>AI Preventivo</strong> — Descrivi il lavoro a voce o testo → preventivo pronto in 2 minuti.</li><li style=\"margin:0 0 8px;\"><strong>Automazioni</strong> — Le imposti una volta, lavorano per te per sempre.</li></ul>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Provale ora</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "winback": {
    "subject": "{{user.first_name}}, è un po' che non ci vediamo",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, non accedi a {{company.name}} da {{user.inactive_days}} giorni. Niente prediche: il cantiere mangia il tempo, lo sappiamo bene.</p>\n<p style=\"margin:0 0 16px;\">Però i tuoi dati sono tutti lì, pronti. E nel frattempo abbiamo aggiunto qualcosa che ti fa risparmiare ancora più tempo.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riprendi da dove eri</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Ti serve una mano per ripartire? Rispondi a questa email.</p>",
    "text_body": ""
  },
  "feature_announcement": {
    "subject": "Novità su EiC: {{feature.name}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">È arrivata: {{feature.name}}</h1><p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo aggiunto una cosa che ci chiedevate in tanti: <strong>{{feature.name}}</strong>.</p>\n<p style=\"margin:0 0 16px;\">In due parole, ti serve a fare prima quello che oggi ti porta via tempo. È già attiva nel tuo account: non devi installare niente.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Provala adesso</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "nps_feedback": {
    "subject": "Due secondi: come ci stiamo comportando?",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, ti rubo due secondi. Su una scala da 0 a 10, quanto consiglieresti Edilizia in Cloud a un altro imprenditore come te?</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Rispondi (un click)</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Se c'è qualcosa che non va, scrivimelo senza filtri: è così che miglioriamo.</p>",
    "text_body": ""
  },
  "maintenance_scheduled": {
    "subject": "Breve manutenzione programmata il {{maintenance.date}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, il <strong>{{maintenance.date}}</strong>, nella finestra {{maintenance.window}}, facciamo un intervento di manutenzione su Edilizia in Cloud. In quel lasso di tempo la piattaforma potrebbe essere lenta o non raggiungibile per qualche minuto.</p>\n<p style=\"margin:0 0 16px;\">Ti avvisiamo prima così organizzi il lavoro senza sorprese. Nessun dato va perso.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Programmiamo gli interventi in orari serali/notturni quando possibile, per darti meno fastidio.</p>",
    "text_body": ""
  },
  "terms_update": {
    "subject": "Aggiorniamo Termini e Privacy — cosa cambia",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo aggiornato i Termini di Servizio e la Privacy Policy di Edilizia in Cloud. Entrano in vigore il <strong>{{event.date}}</strong>.</p>\n<p style=\"margin:0 0 16px;\">Te lo diciamo in italiano, non in legalese: <em>{{terms.summary}}</em>. Continuando a usare la piattaforma dopo quella data, accetti le nuove condizioni.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Leggi cosa cambia</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Vuoi i documenti completi? Sono linkati nella pagina.</p>",
    "text_body": ""
  },
  "gdpr_export": {
    "subject": "Il tuo export dati è pronto",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}}, abbiamo preparato l'export dei dati di {{company.name}} che avevi richiesto. È tutto in un unico archivio, pronto da scaricare.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Scarica i tuoi dati</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Per sicurezza il link scade tra {{export.days_left}} giorni. Dopo, dovrai richiedere un nuovo export.</p>",
    "text_body": ""
  }
};
