// AUTO-GENERATO da /tmp/convert_to_builder.mjs — contenuto delle 58 email di sistema
// (copy riscritti utente, contenuto centrale + {{variabili}}). Fonte di verità del
// DEFAULT mostrato nel builder e del FALLBACK usato dall'invio quando non c'è
// override in platform_email_templates. NON modificare a mano.
/* eslint-disable */
export interface SystemEmailContent { subject: string; html_body: string; text_body: string; }
export const SYSTEM_EMAIL_CONTENT: Record<string, SystemEmailContent> = {
  "welcome": {
    "subject": "{{company.name}} è pronta. Si parte.",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Benvenuto, {{user.first_name}}.</h1>\n<p style=\"margin:0 0 16px;\">Da oggi {{company.name}} ha tutto in un posto solo: cantieri, preventivi, fatture, DDT, clienti e team. Anche dal telefono, direttamente dal cantiere.</p>\n<p style=\"margin:0 0 16px;\">Il tuo account è attivo con ruolo {{user.role_label}}. Imposta la password e sei dentro:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password e accedi</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Primo passo che ti consiglio: crea il primo cantiere e carica un cliente. Cinque minuti. Da lì il resto viene da sé.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">PS. Ti blocchi da qualche parte? Rispondi a questa email: dall'altra parte c'è una persona vera, non un robot.</p>",
    "text_body": ""
  },
  "terms_accepted": {
    "subject": "La tua copia dei documenti, {{user.first_name}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Qui c'è tutto quello che hai firmato.</h1>\n<p style=\"margin:0 0 16px;\">Quando hai registrato {{company.name}} hai accettato le condizioni del servizio. Questa è la tua copia: tienila da parte, è il riferimento di cosa hai sottoscritto.</p>\n<p style=\"margin:0 0 16px;\">Accettazione registrata il {{event.date}} alle {{event.time}}.</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">Termini e Condizioni del Servizio — <a href=\"{{link_url_1}}\">apri</a></li><li style=\"margin:0 0 8px;\">Privacy Policy — <a href=\"{{link_url_2}}\">apri</a></li><li style=\"margin:0 0 8px;\">Accordo trattamento dati (DPA) — <a href=\"{{link_url_3}}\">apri</a></li><li style=\"margin:0 0 8px;\">Cookie Policy — <a href=\"{{link_url_4}}\">apri</a></li></ul>\n<p style=\"margin:0 0 16px;\">E un documento in più, che serve a te: quando i tuoi operai usano l'app (GPS, timbrature) devi consegnargli l'informativa privacy. Te la lasciamo già pronta — da stampare, firmare e archiviare. Un pensiero in meno se passa un controllo.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_5}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri i tuoi documenti</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "staff_access": {
    "subject": "Il tuo accesso a {{company.name}} è pronto",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Benvenuto in {{company.name}}.</h1>\n<p style=\"margin:0 0 16px;\">{{inviter.name}} ti ha creato un account su Edilizia in Cloud: è il gestionale che {{company.name}} usa per cantieri, clienti e documenti. Da oggi ci lavori anche tu.</p>\n<p style=\"margin:0 0 16px;\">Imposta la tua password — è personale, la vedi solo tu — e sei dentro in un minuto.</p>\n<p style=\"margin:0 0 16px;\">Accedi con: {{user.email}}</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore. Se scade, usa \"Password dimenticata\" dalla pagina di accesso.</p>",
    "text_body": ""
  },
  "employee_account": {
    "subject": "{{user.first_name}}, da oggi le ore le timbri dal telefono",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">{{company.name}} ti ha aperto un account su Edilizia in Cloud. Cosa cambia per te: timbri le ore, vedi i tuoi cantieri e carichi le foto dei lavori. Tutto dal telefono, niente fogli.</p>\n<p style=\"margin:0 0 16px;\">Imposta la password e sei operativo:</p>\n<p style=\"margin:0 0 16px;\">Accedi con: {{user.email}}</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore. Ci metti meno che a compilare un rapportino.</p>",
    "text_body": ""
  },
  "salesperson_account": {
    "subject": "{{user.first_name}}, il tuo portafoglio commesse è qui dentro",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">{{company.name}} ti ha aperto un account commerciale su Edilizia in Cloud. Da qui gestisci preventivi, clienti e il tuo portafoglio commesse — e vedi a che punto è ogni trattativa senza chiedere in giro.</p>\n<p style=\"margin:0 0 16px;\">Imposta la password e parti:</p>\n<p style=\"margin:0 0 16px;\">Accedi con: {{user.email}}</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore.</p>",
    "text_body": ""
  },
  "password_reset": {
    "subject": "Reimposta la password",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Capita a tutti.</h1>\n<p style=\"margin:0 0 16px;\">Hai chiesto di reimpostare la password del tuo account. Creane una nuova da qui, ci vogliono trenta secondi:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Crea una nuova password</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Il link scade tra 24 ore.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non hai richiesto tu il reset? Ignora questa email: la password resta quella di prima e nessuno può cambiarla senza questo link.</p>",
    "text_body": ""
  },
  "password_reset_admin": {
    "subject": "Devi impostare una nuova password",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">un amministratore di {{company.name}} ha reimpostato il tuo accesso. Per sicurezza la nuova password la scegli tu — nessuno la conosce, nemmeno l'amministratore:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Imposta la nuova password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non te l'aspettavi? Scrivici a {{platform.support_email}} prima di cliccare qualsiasi cosa.</p>",
    "text_body": ""
  },
  "password_changed": {
    "subject": "La tua password è stata cambiata",
    "html_body": "<p style=\"margin:0 0 16px;\">La password del tuo account {{company.name}} è stata cambiata il {{event.date}} alle {{event.time}}.</p>\n<p style=\"margin:0 0 16px;\">Sei stato tu? Tutto a posto, non devi fare nulla.</p>\n<p style=\"margin:0 0 16px;\">Non sei stato tu? Allora qualcuno ha accesso al tuo account, e ogni minuto conta. Scrivici SUBITO a {{platform.support_email}}: blocchiamo l'accesso e lo mettiamo in sicurezza.</p>",
    "text_body": ""
  },
  "otp_login": {
    "subject": "Codice di accesso: {{otp.code}}",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Il tuo codice di sicurezza:</h1>\n<div style=\"margin:8px 0 18px;text-align:center;\"><span style=\"display:inline-block;font-family:monospace;font-size:34px;letter-spacing:8px;font-weight:700;color:#1E3A5F;background:#f1f5f9;border:1px dashed #cbd5e1;border-radius:10px;padding:14px 26px;\">{{otp.code}}</span></div>\n<p style=\"margin:0 0 16px;\">Scade tra 15 minuti.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non stai accedendo tu? Allora qualcuno conosce la tua password. Non inserire il codice da nessuna parte e cambia subito la password.</p>",
    "text_body": ""
  },
  "email_change_old": {
    "subject": "Hai chiesto tu di cambiare l'email di accesso?",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">qualcuno ha chiesto di spostare l'email di accesso del tuo account {{company.name}} verso {{user.new_email}}.</p>\n<p style=\"margin:0 0 16px;\">Sei stato tu? Non devi fare nulla: appena confermi dal nuovo indirizzo, l'accesso si sposta lì.</p>\n<p style=\"margin:0 0 16px;\">Non sei stato tu? Qualcuno sta cercando di prenderti l'account. Bloccalo adesso:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Non sono stato io — blocca il cambio</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Per sicurezza mandiamo questo avviso anche al nuovo indirizzo.</p>",
    "text_body": ""
  },
  "email_change_new": {
    "subject": "Un click e il cambio email è fatto",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">per completare il cambio email del tuo account {{company.name}} manca solo una conferma: dimostra che questo indirizzo è tuo.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Conferma il nuovo indirizzo</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Finché non confermi, l'accesso resta sull'email precedente. Il link vale 24 ore.</p>",
    "text_body": ""
  },
  "twofa_enabled": {
    "subject": "Fatto: il tuo account ora è blindato",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">hai attivato la verifica in due passaggi sul tuo account {{company.name}}. Buona mossa.</p>\n<p style=\"margin:0 0 16px;\">Da ora, a ogni accesso, oltre alla password serve un codice temporaneo. Anche se qualcuno ti rubasse la password, senza il codice resta fuori. Dentro ci sono i tuoi cantieri e le tue fatture: meglio così.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non sei stato tu ad attivarla? Scrivici a {{platform.support_email}}.</p>",
    "text_body": ""
  },
  "twofa_disabled": {
    "subject": "Hai tolto la protezione in due passaggi",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">la verifica in due passaggi sul tuo account {{company.name}} è stata disattivata. Da ora per entrare basta la password — tua o di chiunque la scopra.</p>\n<p style=\"margin:0 0 16px;\">Sei stato tu e sai quello che fai? Ok, tutto qui.</p>\n<p style=\"margin:0 0 16px;\">Non sei stato tu? Riattivala e cambia subito la password:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riattiva la protezione</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "new_device_login": {
    "subject": "Nuovo accesso al tuo account — sei stato tu?",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">qualcuno è entrato nel tuo account {{company.name}}:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🖥 Dispositivo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{device.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📍 Posizione</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{device.location}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🕐 Quando</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{event.date}} alle {{event.time}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Sei stato tu — nuovo telefono, altro computer? Ignora pure questa email.</p>\n<p style=\"margin:0 0 16px;\">Non ti riconosci? Blocca subito e cambia la password:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Non sono stato io</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "account_locked": {
    "subject": "Account bloccato per qualche minuto — ecco perché",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">abbiamo bloccato temporaneamente l'accesso al tuo account {{company.name}}: troppi tentativi falliti di fila. È una protezione automatica contro chi prova a indovinare la password — scatta anche se eri tu che non la ricordavi.</p>\n<p style=\"margin:0 0 16px;\">Due strade:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">Ricordi la password? Riprova tra qualche minuto.</li><li style=\"margin:0 0 8px;\">Non la ricordi? Reimpostala adesso, fai prima:</li></ul>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Reimposta la password</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non hai provato a entrare tu? Reimposta comunque la password: qualcuno ci sta provando al posto tuo.</p>",
    "text_body": ""
  },
  "user_invited": {
    "subject": "{{inviter.name}} ti ha invitato su Edilizia in Cloud",
    "html_body": "<p style=\"margin:0 0 16px;\">{{inviter.name}} ti ha invitato a entrare in Edilizia in Cloud come {{user.role_label}}.</p>\n<p style=\"margin:0 0 16px;\">Accetta e crea il tuo account: due minuti, non serve altro.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Accetta l'invito</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">L'invito vale 7 giorni. Non riconosci la richiesta? Ignora questa email e non succede niente.</p>",
    "text_body": ""
  },
  "accountant_invite": {
    "subject": "{{company.name}} ti ha dato accesso ai suoi documenti",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{accountant.name}},</p>\n<p style=\"margin:0 0 16px;\">{{inviter.name}} di {{company.name}} ti ha dato accesso come commercialista, con livello {{access.level}}.</p>\n<p style=\"margin:0 0 16px;\">Cosa significa in pratica: fatture e documenti dell'azienda li vedi qui, aggiornati, quando ti servono. Fine delle email \"mi mandi le fatture di marzo?\" — e dei solleciti per averle.</p>\n<p style=\"margin:0 0 16px;\">Non hai ancora un account studio? Lo apri in 60 secondi e {{company.name}} compare subito tra i tuoi clienti.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Accetta e accedi</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Una cosa chiara: {{company.name}} non avrà mai accesso ai dati del tuo studio. L'accesso va in una direzione sola.</p>",
    "text_body": ""
  },
  "invite_reminder": {
    "subject": "{{inviter.name}} ti sta aspettando",
    "html_body": "<p style=\"margin:0 0 16px;\">{{inviter.name}} ti ha invitato su {{company.name}} un paio di giorni fa, ma non sei ancora entrato.</p>\n<p style=\"margin:0 0 16px;\">Manca un passo solo: imposti la password e sei dentro, coi cantieri e i documenti che ti riguardano.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Completa l'accesso</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Un minuto adesso, e non ci pensi più.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Link scaduto? Chiedi a {{inviter.name}} di rimandartelo: ci mette dieci secondi.</p>",
    "text_body": ""
  },
  "account_verify": {
    "subject": "Un click e il tuo account è attivo",
    "html_body": "<p style=\"margin:0 0 16px;\">Ci siamo quasi.</p>\n<p style=\"margin:0 0 16px;\">Conferma che questo indirizzo è tuo e attiviamo subito il tuo account su {{company.name}}:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Conferma l'email</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Il link vale 24 ore. Non hai creato tu questo account? Ignora questa email e non si attiva niente.</p>",
    "text_body": ""
  },
  "invite_accepted_admin": {
    "subject": "{{user.full_name}} è dentro ✅",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">{{user.full_name}} ha accettato l'invito ed è operativo su {{company.name}} con ruolo {{user.role_label}}.</p>\n<p style=\"margin:0 0 16px;\">Vuoi controllare o cambiare cosa può vedere e modificare? Lo fai da Persone &amp; Accessi:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Gestisci il team</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "role_changed": {
    "subject": "Il tuo ruolo su {{company.name}} è cambiato: ora sei {{user.role_label}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il tuo ruolo su {{company.name}} è stato aggiornato a {{user.role_label}}. Col ruolo cambia cosa puoi vedere e modificare nel gestionale.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Entra e guarda cosa è cambiato</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Qualcosa non torna? Parlane con chi gestisce gli accessi in azienda: la modifica arriva da lì, non da noi.</p>",
    "text_body": ""
  },
  "user_removed": {
    "subject": "Il tuo accesso a {{company.name}} è stato revocato",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il tuo accesso a {{company.name}} su Edilizia in Cloud è stato rimosso. Da questo momento non puoi più entrare nei cantieri e nei documenti dell'azienda.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Pensi sia un errore? Contatta chi gestisce gli accessi in {{company.name}}: possono riattivarti in un minuto.</p>",
    "text_body": ""
  },
  "invite_expired": {
    "subject": "L'invito a {{company.name}} è scaduto (rimedio facile)",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">l'invito a entrare in {{company.name}} è scaduto prima che lo accettassi. Capita: il lavoro chiama.</p>\n<p style=\"margin:0 0 16px;\">Il rimedio è semplice: chiedi a {{inviter.name}} di rimandartelo. Dieci secondi per lui, e questa volta entra subito anche tu.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Gli inviti scadono per sicurezza: nessun link deve restare valido all'infinito.</p>",
    "text_body": ""
  },
  "setup_incomplete": {
    "subject": "Ti mancano 5 minuti, {{user.first_name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Hai aperto l'account di {{company.name}}, poi qualcosa ti ha chiamato via. Normale: il cantiere non aspetta.</p>\n<p style=\"margin:0 0 16px;\">Ti mancano due cose, cinque minuti in tutto:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">I dati di fatturazione — così la prima fattura esce senza intoppi</li><li style=\"margin:0 0 8px;\">Il primo cantiere — così vedi subito il gestionale che lavora coi TUOI dati, non con quelli finti di una demo</li></ul>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Completa il setup</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Ti blocchi su un passaggio? Rispondi a questa email: ti guidiamo noi, passo passo.</p>",
    "text_body": ""
  },
  "lifecycle_trial_ending": {
    "subject": "{{trial.days_left}} giorni, poi l'accesso si ferma",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">{{user.first_name}}, mancano {{trial.days_left}} giorni.</h1>\n<p style=\"margin:0 0 16px;\">Poi il trial finisce e l'accesso si blocca. E dentro c'è già del lavoro tuo, vero:</p>\n<p style=\"margin:0 0 16px;\">📦 {{stats.orders}} commesse create<br/>👥 {{stats.customers}} clienti caricati</p>\n<p style=\"margin:0 0 16px;\">Quei dati non spariscono. Ma restano chiusi lì — e tu torni a fare a mano quello che qui era già fatto.</p>\n<p style=\"margin:0 0 16px;\">Attiva un piano e non cambia niente: stessi dati, stesso punto, zero da rifare.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Attiva un piano</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">PS. Un dubbio sul prezzo o sul piano giusto per la tua impresa? Rispondi a questa email: ti rispondo io, senza copione da venditore.</p>",
    "text_body": ""
  },
  "lifecycle_payment_failed": {
    "subject": "Pagamento non passato — 1 minuto per sistemarlo",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">l'addebito di {{subscription.amount}} per l'abbonamento di {{company.name}} non è passato (tentativo {{dunning.attempt}}).</p>\n<p style=\"margin:0 0 16px;\">Quasi sempre è una carta scaduta o un plafond momentaneo. Niente di grave — se lo sistemi adesso:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Aggiorna il pagamento</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Riproviamo in automatico nei prossimi giorni. Ma se i tentativi si esauriscono, l'account si sospende: e restare chiusi fuori dai propri cantieri per una carta scaduta è un peccato.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Problemi col pagamento? Rispondi a questa email: troviamo una soluzione insieme.</p>",
    "text_body": ""
  },
  "purchase_confirmed": {
    "subject": "Fatto: {{company.name}} è operativa senza limiti",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">Grazie {{user.first_name}}.</h1>\n<p style=\"margin:0 0 16px;\">L'abbonamento di {{company.name}} è attivo: da adesso hai tutto il gestionale, senza i limiti del periodo di prova.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Piano</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{plan.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🔁 Fatturazione</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.periodicity}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vai alla dashboard</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">La ricevuta arriva con una mail separata: girala pure al commercialista.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Un consiglio da subito: invita il tuo team. Il gestionale rende il doppio quando le ore e le foto le caricano loro, direttamente dal cantiere.</p>",
    "text_body": ""
  },
  "payment_received": {
    "subject": "Ricevuta pagamento · {{company.name}} · {{event.date}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">pagamento ricevuto per l'abbonamento di {{company.name}}. Tutto regolare.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💳 Metodo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.method}} ••{{card.last4}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Data</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{event.date}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Scarica la fattura</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Conserva questa email o girala al commercialista: è già tutto quello che gli serve.</p>",
    "text_body": ""
  },
  "renewal_upcoming": {
    "subject": "Il {{subscription.renewal_date}} si rinnova l'abbonamento — tutto ok?",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">ti avvisiamo prima, come è giusto: l'abbonamento di {{company.name}} si rinnova il {{subscription.renewal_date}} per {{subscription.amount}}, sullo stesso metodo di pagamento.</p>\n<p style=\"margin:0 0 16px;\">Va bene così? Non devi fare nulla, pensa al cantiere.</p>\n<p style=\"margin:0 0 16px;\">Vuoi cambiare piano o metodo di pagamento? Fallo prima del rinnovo:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Gestisci l'abbonamento</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "card_expiring": {
    "subject": "La carta ••{{card.last4}} sta per scadere",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">la carta che usi per l'abbonamento di {{company.name}} (••{{card.last4}}) scade a breve.</p>\n<p style=\"margin:0 0 16px;\">Un minuto adesso per aggiornarla, e al prossimo rinnovo non si blocca niente:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Aggiorna la carta</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Meglio ora che a account sospeso, con te chiuso fuori e il lavoro che aspetta.</p>",
    "text_body": ""
  },
  "trial_expired": {
    "subject": "Il trial è finito. I tuoi dati no.",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il periodo di prova di {{company.name}} è terminato e l'accesso è in pausa.</p>\n<p style=\"margin:0 0 16px;\">I tuoi dati — commesse, clienti, documenti — sono tutti lì. Intatti. Attivi un piano quando vuoi e riparti dal punto esatto dove eri:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riattiva l'account</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Un avviso onesto: li conserviamo per un periodo limitato. Non lasciar passare mesi.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">PS. Se non hai attivato per un dubbio — prezzo, funzioni, tempo per imparare a usarlo — rispondi a questa email. Meglio una risposta vera che un account fermo.</p>",
    "text_body": ""
  },
  "plan_changed": {
    "subject": "Fatto: ora sei su {{plan.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il piano di {{company.name}} è passato a {{plan.name}}. La modifica è già attiva, non devi fare niente.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Nuovo piano</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{plan.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🔁 Prossimo rinnovo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{subscription.renewal_date}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi cosa è incluso nel tuo piano</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "subscription_cancelled": {
    "subject": "Cancellazione registrata — hai tempo fino al {{subscription.renewal_date}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">abbiamo registrato la cancellazione dell'abbonamento di {{company.name}}. Nessun trucco: continui a usare tutto fino al {{subscription.renewal_date}}, poi l'account va in pausa e i dati restano lì, in attesa.</p>\n<p style=\"margin:0 0 16px;\">Se cambi idea prima di quella data, riattivi con un click:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Ho ripensato — riattiva</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Un minuto per dirmi cosa non ha funzionato? Rispondi a questa email. La leggo io, personalmente — ed è il modo più rapido per far sistemare quello che ti ha fatto andare via.</p>",
    "text_body": ""
  },
  "account_suspended": {
    "subject": "Account sospeso — 2 minuti per riaccenderlo",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">dopo diversi tentativi non siamo riusciti a incassare l'abbonamento di {{company.name}}, quindi l'account è sospeso. L'accesso è bloccato — ma i tuoi dati sono ancora tutti lì: commesse, clienti, documenti.</p>\n<p style=\"margin:0 0 16px;\">Aggiorna il pagamento e torni operativo all'istante:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Aggiorna e riattiva</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">I dati restano disponibili per un periodo limitato. Non aspettare che il problema si risolva da solo: le carte scadute non si aggiornano da sole.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Se il problema non è la carta, rispondi a questa email: parliamone.</p>",
    "text_body": ""
  },
  "refund_issued": {
    "subject": "Rimborso di {{payment.amount}} in arrivo sulla tua carta",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">fatto: abbiamo emesso il rimborso di {{payment.amount}} sull'abbonamento di {{company.name}}.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💳 Su</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.method}} ••{{card.last4}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Riferimento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.reference}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Lo vedi sull'estratto conto entro 5-10 giorni lavorativi: il tempo lo fa la tua banca, non noi.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Se dopo 10 giorni non è arrivato, rispondi a questa email col riferimento qui sopra.</p>",
    "text_body": ""
  },
  "partner_welcome": {
    "subject": "Sei dentro. Ecco come si guadagna.",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.full_name}}, benvenuto: da oggi sei partner {{partner.tier}} di Edilizia in Cloud.</p>\n<p style=\"margin:0 0 16px;\">Come funziona, in due righe e senza asterischi:</p>\n<p style=\"margin:0 0 16px;\">Ogni azienda che si registra col tuo link ti riconosce il {{partner.commission}} del suo abbonamento. Ogni mese, finché resta cliente. Non una tantum: ricorrente. Porti un cliente una volta, incassi finché lui lavora.</p>\n<p style=\"margin:0 0 16px;\">Il tuo codice: {{referral.code}}</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vai alla dashboard partner</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Lì trovi il link da condividere e vedi le conversioni in tempo reale.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Primo passo che funziona sempre: mandalo alle 3 imprese che conosci meglio. Il passaparola tra colleghi converte più di qualsiasi post.</p>",
    "text_body": ""
  },
  "partner_conversion": {
    "subject": "🚀 {{company.name}} si è registrata col tuo link",
    "html_body": "<p style=\"margin:0 0 16px;\">Ottimo lavoro, {{user.full_name}}.</p>\n<p style=\"margin:0 0 16px;\">{{company.name}} si è appena registrata usando il tuo link. Da qui in poi, finché resta cliente, entra nelle tue commissioni ricorrenti — il primo accredito parte dal prossimo ciclo di calcolo.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi le tue conversioni</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Il momento buono per raddoppiare è adesso: a chi altro puoi girare il link questa settimana?</p>",
    "text_body": ""
  },
  "partner_commission": {
    "subject": "{{commission.amount}} maturati a {{period.month}} 💰",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.full_name}},</p>\n<p style=\"margin:0 0 16px;\">mese chiuso. Ecco il tuo:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💰 Commissioni {{period.month}}</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{commission.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🏢 Aziende attive</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{partner.active_companies}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Richiedi il pagamento</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">E ricorda come funziona il ricorrente: le {{partner.active_companies}} aziende di questo mese lavorano per te anche il prossimo. Ogni nuova che porti si somma, non si sostituisce.</p>",
    "text_body": ""
  },
  "partner_payout": {
    "subject": "✅ {{payout.amount}} in arrivo: bonifico partito",
    "html_body": "<p style=\"margin:0 0 16px;\">Ci siamo, {{user.full_name}}.</p>\n<p style=\"margin:0 0 16px;\">Il tuo pagamento di {{payout.amount}} è approvato e il bonifico è partito.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">✅ Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payout.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Riferimento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.reference}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Arriva entro 3-5 giorni lavorativi. Lo trovi anche nello storico della dashboard.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Soldi veri, guadagnati facendo conoscere uno strumento che ai colleghi serve davvero. Avanti così.</p>",
    "text_body": ""
  },
  "partner_tier": {
    "subject": "🎊 Nuovo tier {{partner.new_tier}}: da oggi guadagni di più",
    "html_body": "<p style=\"margin:0 0 16px;\">Complimenti {{user.full_name}}: sei salito al tier {{partner.new_tier}}.</p>\n<p style=\"margin:0 0 16px;\">Hai portato abbastanza aziende da sbloccare un guadagno più alto. Da adesso ogni commissione vale {{partner.multiplier}} in più — e vale anche sulle aziende che hai GIÀ portato, non solo sulle prossime.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi il nuovo tier</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Tradotto: il lavoro fatto finora ha appena aumentato di valore. Da solo.</p>",
    "text_body": ""
  },
  "document_shared": {
    "subject": "{{sender.name}} ti ha condiviso: {{document.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">{{sender.name}} ha condiviso un documento con te su {{company.name}}:</p>\n<p style=\"margin:0 0 16px;\">📄 {{document.name}}</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri il documento</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Lo ritrovi quando vuoi nella sezione documenti del cantiere: niente più \"me lo rimandi?\".</p>",
    "text_body": ""
  },
  "task_assigned": {
    "subject": "Nuova attività da {{sender.name}}: {{task.name}} · entro {{task.due_date}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">{{sender.name}} ti ha assegnato un'attività su {{company.name}}:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">✅ Cosa</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{task.name}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Entro quando</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{task.due_date}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri l'attività</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Dentro trovi i dettagli e puoi segnare l'avanzamento — così {{sender.name}} lo vede senza chiamarti.</p>",
    "text_body": ""
  },
  "report_ready": {
    "subject": "Pronto: {{document.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il report che hai richiesto su {{company.name}} è pronto da scaricare:</p>\n<p style=\"margin:0 0 16px;\">📊 {{document.name}}</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Scarica il report</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Resta comunque disponibile nella tua dashboard, quando ti serve.</p>",
    "text_body": ""
  },
  "silvio_approval": {
    "subject": "Silvio aspetta il tuo ok: {{task.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">Silvio ha preparato un'azione per {{company.name}} e aspetta il tuo via libera prima di muoversi:</p>\n<p style=\"margin:0 0 16px;\">⚙️ Azione: {{task.name}}</p>\n<p style=\"margin:0 0 16px;\">Se va bene, approvi con un click. Se non ti convince, la blocchi. Niente parte senza il tuo ok — mai.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Rivedi e approva</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non c'è fretta: finché non decidi tu, Silvio resta fermo. Comandi tu, lui esegue.</p>",
    "text_body": ""
  },
  "sdi_accepted": {
    "subject": "✅ Fattura {{invoice.number}} consegnata: tutto in regola",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">buone notizie: la fattura {{invoice.number}} di {{company.name}} è stata accettata dallo SDI e trasmessa al cliente. Per il Fisco è ufficialmente emessa.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Fattura</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{invoice.number}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">✅ Stato</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">Consegnata</td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non devi fare nulla: la ricevuta di consegna è già archiviata nel CassettoSDI, pronta se il commercialista la chiede.</p>",
    "text_body": ""
  },
  "sdi_rejected": {
    "subject": "⚠️ Fattura {{invoice.number}} scartata — correggila oggi",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">lo SDI ha scartato la fattura {{invoice.number}} di {{company.name}}. Tradotto: per il Fisco quella fattura al momento NON è stata emessa. Va corretta e rinviata — meglio in giornata.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Fattura</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{invoice.number}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">❌ Motivo dello scarto</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{sdi.reject_reason}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Niente panico: quasi sempre è un dato sbagliato, si sistema in due minuti. Apri la fattura, correggi il punto segnalato e rimandala — te lo facciamo fare in due click:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Correggi e rinvia</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Attenzione al termine: hai 5 giorni dalla notifica di scarto per rinviarla mantenendo la data originale. Passati quelli, si complica.</p>",
    "text_body": ""
  },
  "payment_reminder": {
    "subject": "Promemoria di {{company.name}}: fattura {{invoice.number}} in scadenza il {{document.expiry_date}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Gentile {{customer.name}},</p>\n<p style=\"margin:0 0 16px;\">un promemoria cortese da parte di {{company.name}}: la fattura {{invoice.number}} è in scadenza.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🧾 Fattura</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{invoice.number}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Importo</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{payment.amount}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Scadenza</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.expiry_date}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">Se ha già provveduto al pagamento, ignori pure questo messaggio e ci scusi il disturbo. In caso contrario, può saldare con i riferimenti indicati in fattura.</p>\n<p style=\"margin:0 0 16px;\">Per qualsiasi chiarimento può rispondere direttamente a questa email: {{company.name}} la ricontatterà al più presto.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Messaggio inviato automaticamente da {{company.name}} tramite Edilizia in Cloud.</p>",
    "text_body": ""
  },
  "document_expiring": {
    "subject": "{{document.type}} scade tra {{document.days_left}} giorni — muoviti per tempo",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">controlla questa: un documento di {{company.name}} sta per scadere.</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📋 Documento</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.type}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Scade il</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.expiry_date}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">⏳ Mancano</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{document.days_left}} giorni</td></tr></table>\n<p style=\"margin:0 0 16px;\">Lo sai meglio di me: senza questo documento rischi il cantiere fermo, o di restare fuori da una gara. E il rinnovo fatto all'ultimo costa sempre più caro di quello fatto con calma.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Vedi il documento</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Te lo ricordiamo apposta in anticipo: il tempo per muoverti ce l'hai, usalo.</p>",
    "text_body": ""
  },
  "site_inspection": {
    "subject": "Sopralluogo {{inspection.date}} ore {{inspection.time}} — {{site.address}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">sopralluogo fissato per {{company.name}}. Segnatelo:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📅 Data</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{inspection.date}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">🕐 Ora</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{inspection.time}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📍 Dove</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{site.address}}</td></tr></table>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri la scheda sopralluogo</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Sul posto compili il rilievo direttamente dal telefono: foto, misure e note finiscono già nella scheda. Niente da ricopiare quando torni.</p>",
    "text_body": ""
  },
  "lifecycle_monthly_summary": {
    "subject": "{{period.month}} in 3 numeri: {{stats.orders}} commesse, {{stats.revenue}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il tuo {{period.month}}, in tre numeri — quelli che contano davvero:</p>\n<table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"border:1px solid #e6eaf0;border-radius:8px;margin:0 0 18px;overflow:hidden;\"><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">📦 Commesse gestite</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{stats.orders}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">💶 Fatturato</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">{{stats.revenue}}</td></tr><tr><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:13px;color:#64748b;width:42%;\">⏱ Ore risparmiate rispetto a carta ed Excel</td><td style=\"padding:8px 14px;border-bottom:1px solid #eef1f5;font-size:14px;font-weight:600;color:#1a1a1a;\">~{{stats.hours_saved}}</td></tr></table>\n<p style=\"margin:0 0 16px;\">{{stats.hours_saved}} ore sono giornate intere che questo mese hai passato in cantiere o a casa, invece che dietro una scrivania a rincorrere fogli.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Apri la dashboard e guarda il dettaglio</a>\n    </td></tr></table>",
    "text_body": ""
  },
  "lifecycle_d3_no_activation": {
    "subject": "Ti do una mano a partire, {{user.first_name}}?",
    "html_body": "<p style=\"margin:0 0 16px;\">Hai aperto l'account di {{company.name}} qualche giorno fa, poi tutto fermo. Capita a tanti: il cantiere chiama e il gestionale aspetta.</p>\n<p style=\"margin:0 0 16px;\">Ma per essere operativo bastano 5 minuti, in tre passi:</p>\n<p style=\"margin:0 0 16px;\">1. Aggiungi il primo cliente<br/>2. Crea la prima commessa<br/>3. Invita il tuo team</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riprendi da qui</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Fai anche solo il passo 1: domani il 2 e il 3 vengono da soli.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">PS. Preferisci farlo insieme? Rispondi a questa email e ti seguo io, passo passo. Gratis, senza impegno: mi interessa che parti bene.</p>",
    "text_body": ""
  },
  "lifecycle_d7_features": {
    "subject": "Il preventivo in 2 minuti, dettato a voce",
    "html_body": "<h1 style=\"margin:0 0 18px;font-family:Arial;font-size:23px;line-height:30px;font-weight:700;color:#1a1a1a;\">{{user.first_name}}, è passata una settimana.</h1>\n<p style=\"margin:0 0 16px;\">Ti risparmio la scoperta per tentativi: queste tre cose sono quelle che fanno dire \"ah, però\" a chi le prova. In ordine di ore che ti restituiscono:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">AI Preventivo — descrivi il lavoro, a voce o per iscritto. Preventivo pronto in 2 minuti, non in due sere.</li><li style=\"margin:0 0 8px;\">Render AI — foto del cantiere, render fotorealistico in 90 secondi. Il cliente vede il risultato finito e firma prima.</li><li style=\"margin:0 0 8px;\">Automazioni — le imposti una volta. Poi lavorano loro, anche di domenica.</li></ul>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Provale ora</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Prova la prima già oggi, sul prossimo preventivo che devi fare comunque.</p>",
    "text_body": ""
  },
  "winback": {
    "subject": "{{user.first_name}}, i tuoi cantieri sono ancora qui",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">sono passati {{user.inactive_days}} giorni dal tuo ultimo accesso a {{company.name}}. Nessuna predica: quando il cantiere chiama, il gestionale aspetta. È il suo mestiere.</p>\n<p style=\"margin:0 0 16px;\">Però una cosa te la dico. I preventivi, le ore, i documenti: o stanno qui, o stanno in testa. E in testa, coi giorni, si perdono pezzi.</p>\n<p style=\"margin:0 0 16px;\">I tuoi dati sono esattamente dove li hai lasciati. Riparti da lì:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Riprendi da dove eri</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">PS. Se qualcosa ti ha bloccato — una funzione che non trovavi, un dubbio, un accidenti — rispondi a questa email. Nove volte su dieci si sistema in due righe.</p>",
    "text_body": ""
  },
  "feature_announcement": {
    "subject": "Da oggi su EiC: {{feature.name}}",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">abbiamo aggiunto una cosa che ci chiedevate in tanti: {{feature.name}}.</p>\n<p style=\"margin:0 0 16px;\">È già attiva nel tuo account. Non devi installare niente, non devi pagare niente in più: entri e la trovi.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Provala adesso</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Ti torna utile? Ci piacerebbe saperlo. Non ti serve? Ignorala, non cambia nient'altro.</p>",
    "text_body": ""
  },
  "nps_feedback": {
    "subject": "Una domanda sola, {{user.first_name}}. Un click.",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">ti rubo dieci secondi, promesso. Da 0 a 10: quanto consiglieresti Edilizia in Cloud a un altro imprenditore edile come te?</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Rispondi con un click</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">E se c'è qualcosa che non va, scrivimelo senza filtri, anche brutale. Le pacche sulle spalle non ci fanno migliorare: le critiche sì.</p>",
    "text_body": ""
  },
  "maintenance_scheduled": {
    "subject": "Manutenzione il {{maintenance.date}} ({{maintenance.window}}): cosa aspettarti",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">il {{maintenance.date}}, nella finestra {{maintenance.window}}, facciamo manutenzione su Edilizia in Cloud. In quel lasso di tempo il gestionale potrebbe essere lento o irraggiungibile per qualche minuto.</p>\n<p style=\"margin:0 0 16px;\">Due cose da sapere:</p>\n<ul style=\"padding-left:20px;margin:0 0 16px;\"><li style=\"margin:0 0 8px;\">Nessun dato va perso. Niente. Tutto torna esattamente com'era.</li><li style=\"margin:0 0 8px;\">Scegliamo orari serali o notturni apposta, per non intralciarti il lavoro.</li></ul>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Non devi fare nulla: ti avvisiamo solo per non farti trovare la sorpresa.</p>",
    "text_body": ""
  },
  "terms_update": {
    "subject": "Aggiorniamo Termini e Privacy — te lo spieghiamo in italiano",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">abbiamo aggiornato i Termini di Servizio e la Privacy Policy di Edilizia in Cloud. Entrano in vigore il {{event.date}}.</p>\n<p style=\"margin:0 0 16px;\">Cosa cambia, detto in italiano e non in legalese: {{terms.summary}}</p>\n<p style=\"margin:0 0 16px;\">Se continui a usare il gestionale dopo quella data, accetti le nuove condizioni. Vuoi leggere tutto per bene? Fai giusto:</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Leggi cosa cambia</a>\n    </td></tr></table>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">I documenti completi sono linkati nella pagina.</p>",
    "text_body": ""
  },
  "gdpr_export": {
    "subject": "Il tuo export è pronto — scaricalo entro {{export.days_left}} giorni",
    "html_body": "<p style=\"margin:0 0 16px;\">Ciao {{user.first_name}},</p>\n<p style=\"margin:0 0 16px;\">l'export dei dati di {{company.name}} che avevi richiesto è pronto: un unico archivio, tutto dentro.</p>\n<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:22px 0 4px;\"><tr>\n    <td align=\"center\" bgcolor=\"#F97316\" style=\"background:#F97316;border-radius:6px;\">\n      <a href=\"{{link_url_1}}\" style=\"display:inline-block;padding:14px 30px;font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:600;color:#FFFFFF;text-decoration:none;border-radius:6px;\">Scarica i tuoi dati</a>\n    </td></tr></table>\n<p style=\"margin:0 0 16px;\">Il link scade tra {{export.days_left}} giorni — è una misura di sicurezza: i tuoi dati non devono restare scaricabili all'infinito. Dopo la scadenza basta richiedere un nuovo export.</p>\n<p style=\"margin:14px 0 0;font-size:13px;line-height:1.55;color:#64748b;\">Scaricalo adesso, finché ce l'hai sotto mano.</p>",
    "text_body": ""
  }
};
