import {
  Bath,
  Building2,
  DoorOpen,
  DraftingCompass,
  GalleryHorizontalEnd,
  Grid3X3,
  Hammer,
  Home,
  Layers3,
  Link2,
  PanelLeftClose,
  ShieldCheck,
  SlidersHorizontal,
  Sofa,
  Sparkles,
  Sun,
  TreePine,
  Upload,
  Wand2,
  Waves,
} from "lucide-react";
import type { RenderModuleHubConfig } from "@/components/render/RenderModuleHubPage";

const baseWorkflow = {
  upload: {
    icon: Upload,
    title: "Foto reale",
    description: "Parti sempre da uno scatto leggibile, con zona target e contesto ben visibili.",
  },
  analysis: {
    icon: Wand2,
    title: "Analisi tecnica",
    description: "Il sistema blocca prospettiva, geometria, vincoli e aree che non devono cambiare.",
  },
  choices: {
    icon: SlidersHorizontal,
    title: "Scelte complete",
    description: "Materiali, finiture e dettagli tecnici guidano il render e riducono invenzioni AI.",
  },
  output: {
    icon: GalleryHorizontalEnd,
    title: "Output commerciale",
    description: "Salva in galleria, collega a CRM e apri il dettaglio per prima/dopo e PDF.",
  },
};

const sharedQuality = [
  {
    icon: ShieldCheck,
    title: "Stessa scena",
    description: "Il render deve preservare identita, prospettiva, proporzioni e contesto della foto.",
  },
  {
    icon: Sparkles,
    title: "Controllo tecnico",
    description: "Le istruzioni sono costruite per sostituire solo i sistemi selezionati.",
  },
  {
    icon: Link2,
    title: "CRM ordinato",
    description: "Ogni render resta recuperabile per autore, contatto, opportunita e data.",
  },
];

export const renderModuleHubConfigs: Record<string, RenderModuleHubConfig> = {
  planimetrie: {
    moduleId: "planimetrie",
    moduleName: "Planimetrie AI",
    breadcrumbLabel: "Planimetrie AI",
    badgeLabel: "Sketch to CAD",
    title: "Da schizzo, PDF o planimetria a editor CAD, 3D navigabile e render cliente.",
    description: "Carica una planimetria o un disegno fatto a mano: il modulo ricostruisce muri, stanze, aperture, quote e arredi in un workspace editabile per architetti, tecnici e venditori.",
    icon: DraftingCompass,
    accentClassName: "text-slate-800",
    iconBgClassName: "bg-slate-100",
    newPath: "/azienda/render/planimetrie/new",
    newButtonLabel: "Apri studio planimetrie",
    workflow: [
      { ...baseWorkflow.upload, title: "Sketch, PDF o foto", description: "Accetta disegni su carta, planimetrie scansionate, PDF e foto da telefono." },
      { icon: Wand2, title: "Rilevamento AI", description: "Separa muri, stanze, porte, finestre, arredi, quote e zone incerte." },
      { icon: Layers3, title: "Editor CAD + 3D", description: "Correggi la geometria, conferma una quota reale e naviga la vista dollhouse." },
      { icon: GalleryHorizontalEnd, title: "Output cliente", description: "Prepara CAD, 3D, render di stile e brief per preventivo o sopralluogo." },
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Geometria prima dello stile", description: "Muri, aperture e quote restano separati da materiali, arredi e render." },
      { icon: DraftingCompass, title: "Revisione tecnica", description: "Il sistema segnala quote incerte, stanze non chiuse e punti da verificare." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessuna planimetria ancora",
    emptyDescription: "Carica uno schizzo, una scansione o un PDF per creare una base CAD editabile.",
    recentDescription: "Planimetrie ricostruite e output cliente salvati.",
    imageFit: "contain",
  },
  infissi: {
    moduleId: "infissi",
    moduleName: "Infissi",
    breadcrumbLabel: "Infissi",
    badgeLabel: "Render infissi",
    title: "Nuovi infissi sulla stessa facciata, con controllo tecnico e commerciale.",
    description: "Configura profili, vetro, maniglie, cassonetti e oscuranti mantenendo prospettiva, facciata e aperture reali. Ogni render resta collegabile a contatti e opportunita.",
    icon: DoorOpen,
    accentClassName: "text-blue-600",
    iconBgClassName: "bg-blue-50",
    newPath: "/azienda/render/infissi/new",
    galleryPath: "/azienda/render/infissi/gallery",
    workflow: [
      baseWorkflow.upload,
      { ...baseWorkflow.analysis, title: "Analisi aperture", description: "Mantiene muri, vetri, soglie, davanzali e rapporto con la facciata." },
      baseWorkflow.choices,
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Stessa facciata", description: "Facciata, prospettiva, soglie, davanzali e contesto non vengono reinterpretati." },
      { icon: SlidersHorizontal, title: "Scelte tecniche", description: "Materiale, colore, profilo, vetro e accessori restano leggibili nel risultato." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render ancora",
    emptyDescription: "Carica una foto della facciata o del vano e configura i tuoi infissi.",
  },
  bagno: {
    moduleId: "bagno",
    moduleName: "Bagno",
    breadcrumbLabel: "Bagno",
    badgeLabel: "Render bagno",
    title: "Bagno rinnovato sulla stessa foto, con scelte tecniche sempre leggibili.",
    description: "Configura rivestimenti, sanitari, doccia, vasca, mobile, specchio, rubinetteria e placca WC preservando geometria, infissi, punti funzionali e prospettiva.",
    icon: Bath,
    accentClassName: "text-cyan-600",
    iconBgClassName: "bg-cyan-50",
    newPath: "/azienda/render/bagno/new",
    galleryPath: "/azienda/render/bagno/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto del bagno attuale con sanitari, pareti, pavimento e punti funzionali visibili." },
      { icon: Wand2, title: "Analisi bagno", description: "Riconosce vasca/doccia, mobile, WC, bidet, rivestimenti, placca e vincoli reali." },
      { icon: SlidersHorizontal, title: "Finiture e sanitari", description: "Rivestimenti, formati, WC, placca, mobile, rubinetti e accessori guidano il prompt." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Punti funzionali fermi", description: "WC, bidet, lavabo, vasca/doccia e scarichi non vengono duplicati o spostati a caso." },
      { icon: Grid3X3, title: "Lastre e formati", description: "Le grandi lastre restano grandi, con fughe coerenti e senza griglie casuali." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render bagno ancora",
    emptyDescription: "Carica una foto del bagno e configura il nuovo intervento.",
    imageFit: "contain",
  },
  stanza: {
    moduleId: "stanza",
    moduleName: "Stanza",
    breadcrumbLabel: "Stanza / Interni",
    badgeLabel: "Render stanza",
    title: "Restyling interni sulla stessa stanza, senza effetto stanza generata.",
    description: "Scegli stile, pareti, arredo, pavimento, illuminazione, tende e cucina mantenendo shell, aperture, proporzioni, prospettiva e identita della foto.",
    icon: Sofa,
    accentClassName: "text-purple-600",
    iconBgClassName: "bg-purple-50",
    newPath: "/azienda/render/stanza/new",
    galleryPath: "/azienda/render/stanza/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto della stanza con pareti, arredi, pavimento e aperture leggibili." },
      { icon: Wand2, title: "Scene analysis", description: "Blocca architettura, camera angle, target zones e sistemi da preservare." },
      { icon: SlidersHorizontal, title: "Restyling guidato", description: "Stile, intensita, pareti, arredi, luci e tende vengono coordinati." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Same-room redesign", description: "Stessa stanza, stessa architettura, stessi infissi, stesso punto di ripresa." },
      { icon: Sofa, title: "Layout controllato", description: "Gli arredi cambiano solo secondo la modalita scelta, senza staging casuale." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render stanza ancora",
    emptyDescription: "Carica una foto della stanza e configura il restyling.",
  },
  pavimento: {
    moduleId: "pavimento",
    moduleName: "Pavimento",
    breadcrumbLabel: "Pavimento",
    badgeLabel: "Render pavimento",
    title: "Nuovo pavimento nella stessa stanza, con posa e battiscopa credibili.",
    description: "Configura materiale, colore, finitura, formato, posa, fuga e battiscopa eliminando tracce del vecchio pavimento e preservando tutto il resto.",
    icon: Grid3X3,
    accentClassName: "text-amber-600",
    iconBgClassName: "bg-amber-50",
    newPath: "/azienda/render/pavimento/new",
    galleryPath: "/azienda/render/pavimento/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto della stanza con pavimento e perimetri visibili." },
      { icon: Wand2, title: "Floor map", description: "Identifica area pavimento, oggetti appoggiati, muri, porte e battiscopa." },
      { icon: SlidersHorizontal, title: "Posa tecnica", description: "Materiale, modulo, schema, fuga e battiscopa definiscono geometria e scala." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: Grid3X3, title: "Pattern coerente", description: "Spina, grandi lastre, parquet, resina o moquette hanno regole diverse." },
      { icon: ShieldCheck, title: "Vecchio pavimento rimosso", description: "Nessun fantasma di fughe, doghe o texture incompatibili." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render pavimento ancora",
    emptyDescription: "Carica una foto della stanza e configura materiale e posa.",
  },
  facciata: {
    moduleId: "facciata",
    moduleName: "Facciata",
    breadcrumbLabel: "Facciata",
    badgeLabel: "Render facciata",
    title: "Facciata rinnovata sullo stesso edificio, con involucro e dettagli coerenti.",
    description: "Gestisci cappotto, intonaco, colore, rivestimenti, basamenti, balconi e dettagli senza cambiare aperture, proporzioni e contesto.",
    icon: Building2,
    accentClassName: "text-orange-600",
    iconBgClassName: "bg-orange-50",
    newPath: "/azienda/render/facciata/new",
    galleryPath: "/azienda/render/facciata/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto dell'edificio con facciata, aperture e contesto visibili." },
      { icon: Wand2, title: "Analisi involucro", description: "Distingue superfici, aperture, zoccolature, balconi e vincoli architettonici." },
      { icon: SlidersHorizontal, title: "Sistemi selettivi", description: "Cappotto, colore o rivestimento cambiano solo le zone target." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Aperture preservate", description: "Finestre, porte, balconi e proporzioni restano fedeli alla foto." },
      { icon: Building2, title: "Dettaglio costruttivo", description: "Spessori, contorni e raccordi seguono logica da involucro reale." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render facciata ancora",
    emptyDescription: "Carica una foto dell'edificio e configura l'intervento.",
    imageFit: "contain",
  },
  persiane: {
    moduleId: "persiane",
    moduleName: "Persiane",
    breadcrumbLabel: "Persiane",
    badgeLabel: "Render persiane",
    title: "Persiane, scuri e oscuranti sulla stessa facciata, senza errori di apertura.",
    description: "Aggiungi, sostituisci, rimuovi o cambia colore degli oscuranti preservando vetri, telai, soglie, muri e geometria della facciata.",
    icon: PanelLeftClose,
    accentClassName: "text-green-600",
    iconBgClassName: "bg-green-50",
    newPath: "/azienda/render/persiane/new",
    galleryPath: "/azienda/render/persiane/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto esterna o interna con aperture e contorni ben leggibili." },
      { icon: Wand2, title: "Scope aperture", description: "Definisce quali aperture cambiano e quali restano identiche." },
      { icon: SlidersHorizontal, title: "Oscuranti tecnici", description: "Persiane, scuri, veneziane e colori rispettano ferramenta e spazio reale." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "No stack error", description: "Le configurazioni sono validate evitando cicli e stati impossibili." },
      { icon: PanelLeftClose, title: "Ferramenta coerente", description: "Ante, lamelle, cerniere e posizione seguono la facciata reale." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render persiane ancora",
    emptyDescription: "Carica una foto e configura oscuranti, colore e aperture target.",
    imageFit: "contain",
  },
  tetto: {
    moduleId: "tetto",
    moduleName: "Tetto",
    breadcrumbLabel: "Tetto",
    badgeLabel: "Render tetto",
    title: "Nuovo tetto sullo stesso edificio, con manto, lattonerie e fotovoltaico realistici.",
    description: "Sostituisci copertura, colore, gronde, lucernari, sovracopertura e pannelli preservando falde, facciata, contesto e prospettiva.",
    icon: Home,
    accentClassName: "text-red-600",
    iconBgClassName: "bg-red-50",
    newPath: "/azienda/render/tetto/new",
    galleryPath: "/azienda/render/tetto/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto edificio con tetto, falde e accessori visibili." },
      { icon: Wand2, title: "Falde target", description: "Distingue falde, colmi, converse, lucernari, gronde e accessori." },
      { icon: SlidersHorizontal, title: "Sistema copertura", description: "Manto, bordo, flashing, lattonerie e fotovoltaico restano installabili." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Geometria tetto ferma", description: "Le falde non cambiano forma salvo intervento esplicito." },
      { icon: Home, title: "Waterproofing logic", description: "Colmi, scossaline, bordi, gronde e pannelli seguono dettagli plausibili." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render tetto ancora",
    emptyDescription: "Carica una foto dell'edificio e configura copertura e accessori.",
  },
  pergole: {
    moduleId: "pergole",
    moduleName: "Pergole",
    breadcrumbLabel: "Pergole",
    badgeLabel: "Render pergole",
    title: "Pergole installabili nello stesso esterno, con struttura e ombre credibili.",
    description: "Configura pergole addossate, autoportanti, bioclimatiche, telo, vetro, screen ZIP, luci e accessori rispettando facciata, pavimento, aperture e passaggi.",
    icon: Sun,
    accentClassName: "text-emerald-600",
    iconBgClassName: "bg-emerald-50",
    newPath: "/azienda/render/pergole/new",
    galleryPath: "/azienda/render/pergole/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto di patio, terrazza, giardino o bordo piscina con spazio di installazione visibile." },
      { icon: Wand2, title: "Installability map", description: "Definisce impronta, altezza, montanti, ancoraggi e interferenze." },
      { icon: SlidersHorizontal, title: "Sistema pergola", description: "Struttura, copertura, lamelle, telo, vetro, ZIP e drenaggio sono coordinati." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Niente strutture sospese", description: "Montanti, attacchi e contatti a terra devono sembrare reali." },
      { icon: Sun, title: "Bioclimatica leggibile", description: "Lamelle, telo, vetro o screen sono distinti e riconoscibili." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render pergola ancora",
    emptyDescription: "Carica una foto esterna e configura la pergola.",
  },
  piscine: {
    moduleId: "piscine",
    moduleName: "Piscine",
    breadcrumbLabel: "Piscine",
    badgeLabel: "Render piscine",
    title: "Piscine credibili nello stesso giardino, con acqua, bordo e quota corretti.",
    description: "Inserisci piscina interrata, sfioro, infinity, skimmer, spiaggetta, coping, deck e luci con integrazione realistica nel terreno.",
    icon: Waves,
    accentClassName: "text-teal-600",
    iconBgClassName: "bg-teal-50",
    newPath: "/azienda/render/piscine/new",
    galleryPath: "/azienda/render/piscine/gallery",
    workflow: [
      { ...baseWorkflow.upload, description: "Foto esterna con giardino, patio, quote e zona piscina visibili." },
      { icon: Wand2, title: "Buildability envelope", description: "Valuta impronta, quota, bordo, deck, percorsi, muri e vincoli." },
      { icon: SlidersHorizontal, title: "Sistema acqua", description: "Skimmer, sfioro, infinity, rivestimento, gradini e coping restano coerenti." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "No piscina appoggiata", description: "La vasca deve integrarsi nel terreno con profondita e bordo credibili." },
      { icon: Waves, title: "Acqua realistica", description: "Trasparenza, riflessi, colore e profondita seguono luce e rivestimento." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render piscina ancora",
    emptyDescription: "Carica una foto del giardino e configura la piscina.",
  },
  ristrutturazioni: {
    moduleId: "ristrutturazioni",
    moduleName: "Ristrutturazioni",
    breadcrumbLabel: "Ristrutturazioni",
    badgeLabel: "Orchestratore multi-sistema",
    title: "Ristrutturazioni coordinate, con compatibilita scena-sistemi prima del render.",
    description: "Il modulo orchestra piu domini evitando conflitti fra bagno, stanza, facciata, tetto, pavimenti, aperture e outdoor nella stessa foto.",
    icon: Hammer,
    accentClassName: "text-indigo-600",
    iconBgClassName: "bg-indigo-50",
    newPath: "/azienda/render/ristrutturazioni/new",
    galleryPath: "/azienda/render/ristrutturazioni/gallery",
    workflow: [
      baseWorkflow.upload,
      { icon: Wand2, title: "Scene router", description: "Classifica la foto e blocca i domini non visibili o incompatibili." },
      { icon: Layers3, title: "Manifest globale", description: "Unifica target map, preservation map, dependency graph e conflict resolver." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Zero ibridi", description: "Niente somma casuale di prompt o domini incompatibili nella stessa foto." },
      { icon: Hammer, title: "Ordine lavori", description: "Demolizioni, superfici, serramenti, arredi e dettagli seguono priorita logiche." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render ristrutturazione ancora",
    emptyDescription: "Carica una foto e configura una ristrutturazione compatibile con la scena.",
  },
  "pavimenti-esterni": {
    moduleId: "pavimenti-esterni",
    moduleName: "Pavimenti esterni",
    breadcrumbLabel: "Pavimenti esterni",
    badgeLabel: "Outdoor hardscape",
    title: "Pavimenti esterni con quote, drenaggio, bordi e soglie credibili.",
    description: "Il motore gestisce patio, vialetti, deck, coping piscina, gradini, soglie e fasce carrabili senza trattarli come una texture appoggiata.",
    icon: Layers3,
    accentClassName: "text-lime-700",
    iconBgClassName: "bg-lime-50",
    newPath: "/azienda/render/pavimenti-esterni/new",
    galleryPath: "/azienda/render/pavimenti-esterni/gallery",
    workflow: [
      baseWorkflow.upload,
      { icon: Wand2, title: "Target surface map", description: "Distingue patio, camminamenti, bordo piscina, gradini, soglie e zone non target." },
      { icon: Layers3, title: "Drainage envelope", description: "Controlla spessore, pendenze, giunti, tagli, bordi e raccordi." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Stesso esterno", description: "Casa, facciata, prato, piscina e arredi non target restano invariati." },
      { icon: Grid3X3, title: "No vecchie fughe", description: "La vecchia pavimentazione sparisce quando cambia sistema o materiale." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render pavimento esterno ancora",
    emptyDescription: "Carica una foto esterna e configura materiale, posa, drenaggio e bordi.",
  },
  giardini: {
    moduleId: "giardini",
    moduleName: "Giardini",
    breadcrumbLabel: "Giardini",
    badgeLabel: "Landscape design",
    title: "Giardini progettati sulla stessa foto, con scala vegetale e zone credibili.",
    description: "Il motore coordina prato, aiuole, siepi, alberi, camminamenti, arredo, luci e declutter preservando casa, hardscape e visuali.",
    icon: TreePine,
    accentClassName: "text-green-700",
    iconBgClassName: "bg-green-50",
    newPath: "/azienda/render/giardini/new",
    galleryPath: "/azienda/render/giardini/gallery",
    workflow: [
      baseWorkflow.upload,
      { icon: Wand2, title: "Garden zoning", description: "Distingue prato, perimetro, bordo casa, piscina, pergola, passaggi e zone intoccabili." },
      { icon: TreePine, title: "Planting envelope", description: "Controlla altezze, densita, distanze, manutenzione e visual balance." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "No collage verde", description: "Le piante devono avere scala, ombre e densita realistiche." },
      { icon: TreePine, title: "Stile riconoscibile", description: "Moderno, mediterraneo, naturale o low maintenance cambiano davvero la composizione." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render giardino ancora",
    emptyDescription: "Carica una foto del giardino e configura prato, aiuole, siepi, percorsi e arredi.",
  },
  "porte-blindate": {
    moduleId: "porte-blindate",
    moduleName: "Porte blindate",
    breadcrumbLabel: "Porte blindate",
    badgeLabel: "Security doors",
    title: "Porte blindate nel vano reale, senza effetto porta incollata.",
    description: "Il motore governa anta, telaio, coprifili, soglia, ferramenta, lato visibile, fiancoluce, sopraluce e rasomuro preservando ingresso e pavimento.",
    icon: ShieldCheck,
    accentClassName: "text-slate-700",
    iconBgClassName: "bg-slate-100",
    newPath: "/azienda/render/porte-blindate/new",
    galleryPath: "/azienda/render/porte-blindate/gallery",
    workflow: [
      baseWorkflow.upload,
      { icon: Wand2, title: "Opening map", description: "Distingue anta, telaio, soglia, coprifili, pareti adiacenti e zone da preservare." },
      { icon: DoorOpen, title: "Security system", description: "Finiture, maniglia, defender, spioncino e telaio restano proporzionati." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Vano preservato", description: "La nuova porta occupa il vano reale senza deformare pareti o pavimento." },
      { icon: DoorOpen, title: "Vecchio telaio rimosso", description: "Niente residui, cornici fantasma o ibridi vecchio/nuovo." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render porta blindata ancora",
    emptyDescription: "Carica una foto dell'ingresso e configura porta, telaio, soglia e ferramenta.",
  },
  "porte-interne": {
    moduleId: "porte-interne",
    moduleName: "Porte interne",
    breadcrumbLabel: "Porte interne",
    badgeLabel: "Interior openings",
    title: "Porte interne nello stesso vano, con apertura e ferramenta plausibili.",
    description: "Il motore gestisce battente, scorrevole interno muro, scorrevole esterno, libro, rasomuro, tutta altezza, vetro, telaio, coprifili e maniglia.",
    icon: DoorOpen,
    accentClassName: "text-violet-600",
    iconBgClassName: "bg-violet-50",
    newPath: "/azienda/render/porte-interne/new",
    galleryPath: "/azienda/render/porte-interne/gallery",
    workflow: [
      baseWorkflow.upload,
      { icon: Wand2, title: "Compatibility envelope", description: "Verifica vano, zoccolino, soffitto, mobili vicini e parete di scorrimento." },
      { icon: DoorOpen, title: "Meccanismo leggibile", description: "Battente, scorrevole, rasomuro o vetrata non si mescolano in stati ibridi." },
      baseWorkflow.output,
    ],
    qualityCards: [
      { icon: ShieldCheck, title: "Stessa stanza", description: "Pareti, pavimento, zoccolino, arredi e prospettiva restano invariati." },
      { icon: DoorOpen, title: "No collisioni", description: "Scorrevoli, binari, doppie ante e porte altezza piena rispettano il contesto." },
      sharedQuality[2],
    ],
    emptyTitle: "Nessun render porta interna ancora",
    emptyDescription: "Carica una foto della stanza o del vano e configura porta, telaio e apertura.",
  },
};
