/** Editorial content for the six native Climatizzazione modules. Images illustrate scope, never customer work. */
import { GENERATED_CLM_ASSETS } from "./generatedClmAssets";
export type ClmEditorialPair = readonly [string, string];
export interface ClmEditorial {
  title: string; hero: string; subtitle: string; cover: string; detail: string; context: string;
  scope: string; specs: ClmEditorialPair[]; stages: ClmEditorialPair[]; checks: ClmEditorialPair[];
  faq: ClmEditorialPair[]; rows: [string, string, number][];
}
const stock = (name: string) => `/pdf-stock/climatizzazione/${name}.jpg`;
const common = (name: string) => `/pdf-stock/comune/${name}.jpg`;
export const CLM_EDITORIAL = {
  monosplit: {
    title: "Impianto monosplit", hero: "Il tuo ambiente.\nIl clima che scegli.",
    subtitle: "Una unità interna e una esterna: posizione, collegamenti e comandi studiati per il locale da servire.",
    cover: "/module-art/climatizzazione.jpg", detail: stock("unita-esterna"), context: stock("estate"),
    scope: "La proposta riguarda una coppia di unità compatibili e le sole linee, protezioni e lavorazioni elencate. Lunghezze aggiuntive, pompe condensa, alimentazione dedicata, accessi in quota e ripristini richiedono voci esplicite.",
    specs: [
      ["Il locale da servire", "Superficie, esposizione, vetrate, occupazione e uso guidano la selezione. La sola metratura non determina la potenza necessaria."],
      ["Unità e posizione", "Modelli abbinati, ingombri e distanze di servizio si verificano insieme alla direzione del getto, evitando postazioni occupate stabilmente."],
      ["Linee e condensa", "Percorso, lunghezze, dislivelli e scarico devono rispettare le indicazioni dei componenti scelti e le condizioni rilevate."],
      ["Comandi e alimentazione", "Funzioni del telecomando, eventuale controllo remoto e alimentazione disponibile vengono indicati nella configurazione."]],
    stages: [
      ["Rilievo del locale", "Concordiamo area servita, posizione delle unità e percorso dei collegamenti."],
      ["Scelta della coppia", "Identifichiamo apparecchi, accessori, scarico e opere comprese prima dell'ordine."],
      ["Posa e collegamenti", "Proteggiamo le aree coinvolte ed eseguiamo fissaggi e collegamenti previsti."],
      ["Avviamento guidato", "Verifichiamo funzioni, scarico condensa e comandi, poi spieghiamo uso e pulizia dei filtri."]],
    checks: [["Fissaggi", "Riscontro dei supporti e delle distanze di servizio."], ["Circuito e collegamenti", "Verifiche e avviamento previsti per gli apparecchi installati."], ["Condensa", "Controllo del deflusso nel punto di scarico concordato."], ["Uso del locale", "Prova dei comandi e orientamento delle alette in relazione agli occupanti."]],
    faq: [
      ["Un monosplit raffresca tutta la casa?", "La proposta serve il locale individuato. Non presume una distribuzione uniforme attraverso porte e corridoi."],
      ["Quale potenza occorre?", "Serve valutare il locale e le condizioni d'uso. La potenza del modello sarà riportata nella proposta tecnica."],
      ["Dove si colloca l'unità esterna?", "In una posizione accessibile e compatibile con distanze, ventilazione, supporti e vincoli dell'immobile."],
      ["Le tubazioni sono tutte comprese?", "Solo percorso e quantità indicati. Eventuali metri aggiuntivi o attraversamenti vanno concordati."],
      ["Lo scarico funziona per gravità?", "Pendenze e destinazione si verificano al rilievo. Una pompa condensa va descritta e quotata se necessaria."],
      ["Posso comandarlo dal telefono?", "Solo se il modello e gli accessori includono tale funzione e la rete disponibile è compatibile."],
      ["Quanto consumerà?", "Dipende da apparecchio, clima, involucro e utilizzo. Nessun costo mensile o risparmio è garantito dal modello."],
      ["Sono compresi manutenzione e incentivi?", "La pulizia periodica e i servizi successivi si definiscono separatamente. Nessuna agevolazione è presunta."]],
    rows: [["Apparecchi", "Coppia monosplit: unità interna ed esterna della configurazione dimostrativa", 980], ["Installazione", "Posa e collegamenti sul percorso descritto, scarico condensa previsto", 380], ["Avviamento", "Verifica funzionale e spiegazione dei comandi monosplit", 120]],
  },
  multisplit: {
    title: "Impianto multisplit", hero: "Più ambienti.\nUn sistema coordinato.",
    subtitle: "Unità interne dedicate ai locali, un gruppo esterno compatibile e collegamenti definiti zona per zona.",
    cover: stock("tecnica-multisplit"), detail: stock("unita-esterna"), context: stock("estate"),
    scope: "La configurazione elenca le unità interne, l'abbinamento esterno, le linee di ciascuna zona e gli scarichi previsti. Aggiungere una stanza richiede una verifica di compatibilità e capacità, non soltanto un nuovo terminale.",
    specs: [
      ["Locali e contemporaneità", "Valutiamo fabbisogni e orari di utilizzo stanza per stanza, distinguendo funzionamento singolo e contemporaneo."],
      ["Abbinamento delle unità", "Il numero di unità interne e la combinazione con l'esterna devono risultare compatibili secondo i dati del sistema proposto."],
      ["Reti per ogni zona", "Ogni ambiente ha un percorso da rilevare: lunghezze, dislivelli, attraversamenti e scarico condensa non sono intercambiabili."],
      ["Comandi e modalità", "Regolazioni e limiti delle modalità simultanee dipendono dalla macchina selezionata; vanno spiegati prima della scelta."]],
    stages: [["Rilievo stanza per stanza", "Definiamo locali serviti, occupazione, posizioni e percorsi."], ["Configurazione compatibile", "Confermiamo abbinamenti, contemporaneità e accessori delle singole zone."], ["Posa delle reti", "Coordiniamo passaggi, collegamenti e scarichi, mantenendo identificabili i circuiti."], ["Prove per zona", "Verifichiamo ciascuna unità e il funzionamento coordinato, illustrando comandi e limiti."]],
    checks: [["Corrispondenza delle zone", "Ogni unità deve corrispondere al locale e alla linea previsti."], ["Scarichi separati", "Verificare il deflusso delle condense da ogni terminale."], ["Comandi", "Provare regolazioni locali e funzioni centralizzate se comprese."], ["Funzionamento coordinato", "Riscontrare le modalità ammesse dalla combinazione installata."]],
    faq: [
      ["Quante stanze sono comprese?", "Sono quelle associate alle unità interne elencate. Il numero non si ricava dalla foto illustrativa."],
      ["Le stanze possono lavorare in modalità diverse?", "Le combinazioni ammesse dipendono dal sistema: non si presume caldo e freddo simultanei."],
      ["La potenza esterna è la somma delle interne?", "La scelta richiede dati di compatibilità, capacità disponibile e contemporaneità; non basta sommare le targhe."],
      ["Posso aggiungere uno split in futuro?", "Solo se capacità, attacchi e combinazioni consentite lo permettono. La predisposizione va concordata."],
      ["Serve uno scarico per ogni locale?", "Ogni unità deve avere un percorso della condensa verificato; le soluzioni vanno specificate."],
      ["Le tracce murarie sono incluse?", "Solo le tracce e i ripristini espressamente descritti, con finiture e aree definite."],
      ["Cosa succede se si ferma l'unità esterna?", "Le unità collegate dipendono dal gruppo esterno; diagnosi e assistenza seguono il sistema installato."],
      ["Il multisplit garantisce risparmio?", "No. Il confronto richiede condizioni equivalenti, dati del prodotto e abitudini reali."]],
    rows: [["Sistema", "Sistema multisplit dimostrativo con due unità interne e gruppo esterno compatibile", 2200], ["Reti e posa", "Collegamenti e scarichi delle due zone descritte", 780], ["Configurazione", "Avviamento e prove di funzionamento per entrambe le unità", 180]],
  },
  canalizzato: {
    title: "Impianto canalizzato", hero: "Il comfort si diffonde.\nLo spazio resta tuo.",
    subtitle: "Unità nascosta, canali, mandata e ripresa: il progetto dell'aria si integra con gli ambienti e con le quote disponibili.",
    cover: "/module-art/climatizzazione-canalizzato-editorial.jpg", detail: GENERATED_CLM_ASSETS.canalizzato.path, context: "/module-art/ristrutturazioni-commerciale.jpg",
    scope: "Sono inclusi soltanto unità, rete aeraulica, terminali e regolazioni elencati. Controsoffitti, botole, opere elettriche, finiture e zonizzazione richiedono definizione esplicita. Le immagini mostrano contesti abitativi e di lavoro, non il progetto dei canali.",
    specs: [["Quote e ispezionabilità", "Ingombro dell'unità, spazio per i canali e accessi per filtri e manutenzione devono essere verificati prima di chiudere i controsoffitti."], ["Mandata e ripresa", "Percorsi, sezioni e terminali si definiscono insieme, con attenzione a perdite di carico e passaggio dell'aria tra le zone."], ["Rumore e isolamento", "Velocità, supporti e isolamento si valutano nel progetto; la sola macchina non determina il comfort acustico dell'impianto."], ["Regolazione delle zone", "Sonde, comandi ed eventuali serrande sono inclusi solo se elencati. Una bocchetta per stanza non equivale a controllo indipendente."]],
    stages: [["Rilievo degli ingombri", "Misuriamo quote utili, passaggi, posizione dell'unità e accessi manutentivi."], ["Coordinamento del progetto", "Definiamo mandata, ripresa, terminali e interferenze con gli altri impianti."], ["Posa prima delle chiusure", "Installiamo le parti previste e concordiamo i controlli prima dei ripristini."], ["Regolazione e consegna", "Riscontriamo distribuzione e comandi previsti, individuando filtri e accessi da mantenere liberi."]],
    checks: [["Accessi", "Botole e spazi permettono le operazioni previste dal produttore."], ["Rete aeraulica", "Riscontro dei percorsi, delle giunzioni e dell'isolamento compreso."], ["Terminali", "Controllo di mandata, ripresa e regolazioni previste nelle zone."], ["Condensa e comandi", "Verifica dello scarico e spiegazione delle impostazioni concordate."]],
    faq: [["Serve sempre un controsoffitto?", "Occorre uno spazio compatibile con unità e rete. Quote, finiture e accessi si verificano nel progetto."], ["Le bocchette sostituiscono gli split?", "Distribuiscono l'aria prodotta dall'unità canalizzata; tipologia e numero sono quelli del progetto."], ["È previsto ricambio con aria esterna?", "Non automaticamente. Ricircolo per climatizzazione e ventilazione sono funzioni distinte."], ["Ogni stanza ha una temperatura autonoma?", "Solo se la zonizzazione è prevista con componenti e logiche compatibili."], ["Dove si puliscono i filtri?", "L'accesso deve restare disponibile e va mostrato alla consegna."], ["Il sistema sarà silenzioso?", "Il risultato dipende dall'intero progetto aeraulico e dalla posa. Non si promettono valori senza dati verificati."], ["Chi realizza controsoffitti e tinteggiature?", "La proposta deve indicare responsabilità, superfici e finiture incluse."], ["Posso spostare le bocchette dopo la posa?", "La modifica va valutata rispetto a portate, rete e opere già eseguite e richiede un accordo."]],
    rows: [["Apparecchi", "Unità canalizzata e gruppo esterno compatibile della configurazione dimostrativa", 2800], ["Distribuzione", "Rete aeraulica e terminali delle zone descritte, posa inclusa", 1900], ["Regolazione", "Riscontri della distribuzione, configurazione e consegna dei comandi", 350]],
  },
  sostituzione: {
    title: "Sostituzione climatizzatori", hero: "Nuove unità.\nCompatibilità verificata.",
    subtitle: "Rinnovare il comfort parte da un controllo delle linee esistenti, degli scarichi e degli spazi disponibili.",
    cover: stock("installazione"), detail: stock("unita-esterna"), context: stock("controllo-collaudo"),
    scope: "La sostituzione riguarda gli apparecchi identificati e le lavorazioni elencate. Il riuso di tubazioni, cavi, staffe e scarichi è subordinato alle verifiche di compatibilità e stato; gli adeguamenti emersi si concordano prima dell'esecuzione.",
    specs: [["Apparecchi esistenti", "Registriamo unità da rimuovere, posizione, accessi e parti da conservare senza presumere che il vecchio impianto sia riutilizzabile."], ["Compatibilità delle linee", "Diametri, lunghezze, isolamento e condizioni del circuito si confrontano con le indicazioni delle nuove unità."], ["Rimozione organizzata", "Definiamo smontaggio, gestione dei componenti rimossi e attività sul circuito secondo l'intervento effettivo."], ["Nuova configurazione", "Modelli, supporti, scarichi e collegamenti adeguati risultano nella proposta aggiornata."]],
    stages: [["Ricognizione dell'esistente", "Identifichiamo macchine e percorsi accessibili, raccogliendo documenti disponibili."], ["Decisione sul riuso", "Confermiamo cosa conservare e quali adeguamenti sono necessari."], ["Rimozione e montaggio", "Organizziamo dismissione e posa con le interruzioni concordate."], ["Riavvio e istruzioni", "Verifichiamo le nuove unità e consegniamo comandi e documenti aggiornati."]],
    checks: [["Componenti conservati", "Riscontro delle verifiche che consentono il riutilizzo previsto."], ["Nuovi abbinamenti", "Controllo della corrispondenza tra modelli ordinati e installati."], ["Scarichi e fissaggi", "Verifica delle parti riutilizzate o adeguate comprese nell'offerta."], ["Avviamento", "Prove previste dai prodotti e spiegazione delle nuove funzioni."]],
    faq: [["Le vecchie tubazioni si possono riusare?", "Solo dopo la verifica di compatibilità e condizioni rispetto ai nuovi apparecchi."], ["Basta sostituire l'unità interna?", "L'abbinamento con l'esterna deve essere espressamente compatibile; non si presume dal marchio."], ["La rimozione è compresa?", "Smontaggio e gestione del rimosso devono comparire tra le attività incluse."], ["Saranno necessarie nuove tracce?", "Dipende da percorsi e adeguamenti. Le opere si definiscono dopo il rilievo."], ["E se emerge una linea danneggiata?", "Si documenta il riscontro e si concorda la variazione prima di eseguire lavori aggiuntivi."], ["Posso mantenere i vecchi comandi?", "Solo quando compatibili con il nuovo sistema; le funzioni possono cambiare."], ["Quanto tempo resterò senza clima?", "Il programma dipende dagli accessi e dalle lavorazioni. La finestra di fermo va concordata."], ["Il nuovo modello consumerà meno?", "Serve un confronto documentato e coerente con l'uso reale; nessuna percentuale è automatica."]],
    rows: [["Rimozione", "Rimozione della coppia di climatizzatori identificata e gestione del rimosso prevista", 220], ["Nuove unità", "Coppia di unità sostitutive compatibili della configurazione dimostrativa", 1200], ["Installazione", "Montaggio sui collegamenti verificati e avviamento delle nuove unità", 480]],
  },
  manutenzione: {
    title: "Manutenzione e pulizia", hero: "Il clima di ogni giorno.\nLa cura che serve.",
    subtitle: "Unità identificate, operazioni concordate e riscontri documentati: un intervento commisurato allo stato dell'impianto.",
    cover: stock("controllo-collaudo"), detail: GENERATED_CLM_ASSETS.manutenzione.path, context: stock("unita-esterna"),
    scope: "Il servizio comprende le pulizie e i controlli elencati sulle unità accessibili indicate. Ricambi, ricerca perdite, riparazioni, ripristini e attività non previste richiedono un accordo separato. La pulizia non equivale a una promessa di sanificazione degli ambienti.",
    specs: [["Inventario delle unità", "Numero, tipologia, posizione e accessibilità definiscono il servizio. Annotiamo anomalie segnalate e documentazione disponibile."], ["Pulizia delle parti previste", "Filtri e superfici accessibili si trattano con modalità compatibili con i materiali e le istruzioni dei prodotti."], ["Riscontri funzionali", "Comandi, deflusso condensa e funzionamento si verificano nei limiti delle attività concordate e dello stato dell'impianto."], ["Rapporto e periodicità", "Registriamo attività svolte, anomalie e proposte successive. La cadenza dipende da uso, ambiente e istruzioni, non da una promessa standard."]],
    stages: [["Identificazione e accessi", "Confermiamo unità, sintomi segnalati e condizioni per operare."], ["Pulizie concordate", "Proteggiamo le aree e trattiamo le parti accessibili previste."], ["Controlli e riscontri", "Eseguiamo le verifiche definite e segnaliamo eventuali attività ulteriori."], ["Rapporto dell'intervento", "Consegniamo l'elenco delle operazioni e le indicazioni per la cura ordinaria."]],
    checks: [["Filtri e parti accessibili", "Registrare cosa è stato pulito e cosa non era raggiungibile."], ["Scarico condensa", "Riscontrare il deflusso nell'ambito del servizio previsto."], ["Funzionamento", "Annotare i riscontri ottenuti e gli eventuali limiti della prova."], ["Anomalie e seguito", "Distinguere attività concluse, ricambi proposti e verifiche ulteriori."]],
    faq: [["Quante unità comprende il servizio?", "Solo quelle elencate, distinguendo unità interne ed esterne e relativo accesso."], ["Pulizia e riparazione sono la stessa cosa?", "No. Ricambi e riparazioni richiedono diagnosi e approvazione delle attività ulteriori."], ["È prevista una ricarica di refrigerante?", "Non automaticamente: serve una valutazione tecnica del circuito e della causa dell'eventuale problema."], ["Elimina tutti gli odori?", "L'esito dipende dalla causa. Gli odori persistenti possono richiedere indagini su scarichi e componenti."], ["Posso pulire i filtri da solo?", "Segui le istruzioni dell'apparecchio per le operazioni consentite all'utilizzatore e le relative precauzioni."], ["Il servizio certifica aria salubre?", "Non viene promesso un risultato sanitario o una certificazione ambientale dalla sola pulizia."], ["La visita si ripete automaticamente?", "Solo se è concordato un piano periodico con durata, frequenza e condizioni esplicite."], ["Cosa riceverò alla fine?", "Un riepilogo delle attività e dei riscontri, con anomalie e interventi suggeriti tenuti distinti."]],
    rows: [["Pulizia", "Pulizia delle parti accessibili previste su due unità interne dimostrative", 120], ["Controlli", "Riscontri funzionali e verifica degli scarichi delle unità indicate", 65], ["Rapporto", "Riepilogo attività e indicazioni di cura ordinaria", 25]],
  },
  vmc: {
    title: "Ventilazione meccanica controllata", hero: "Aria che si rinnova.\nSpazi da vivere.",
    subtitle: "Ricambio d'aria progettato per gli ambienti: unità, percorsi, filtri e regolazioni definiti insieme.",
    cover: GENERATED_CLM_ASSETS.vmc.path, detail: GENERATED_CLM_ASSETS.vmc.path, context: common("consegna-documenti"),
    scope: "La proposta identifica una soluzione puntuale o centralizzata, gli ambienti serviti e i componenti elencati. Recupero di calore, sensori, canalizzazioni e opere murarie sono compresi solo se descritti. Le foto illustrano gli spazi, non la tecnologia fornita.",
    specs: [["Ambienti e ricambi", "Occupazione, destinazione dei locali e percorsi dell'aria guidano la definizione delle portate; i valori vanno documentati nel progetto."], ["Puntuale o centralizzata", "Unità locali e reti centralizzate richiedono opere e spazi diversi. La scelta deve risultare esplicita nella configurazione."], ["Prese, espulsioni e passaggi", "Posizioni, attraversamenti, distanze e trasferimento dell'aria tra i locali si verificano insieme a vincoli e accessibilità."], ["Filtri e regolazione", "Tipologia dei filtri, accessi, modalità di funzionamento e sensori previsti devono essere chiari per la gestione quotidiana."]],
    stages: [["Rilievo degli ambienti", "Raccogliamo usi, occupazione, vincoli e possibili posizioni delle unità."], ["Definizione del sistema", "Concordiamo tecnologia, portate, percorsi e opere comprese."], ["Posa coordinata", "Realizziamo i passaggi e installiamo i componenti previsti mantenendo gli accessi necessari."], ["Regolazione e gestione", "Riscontriamo le portate dove previsto e spieghiamo comandi, filtri e manutenzione."]],
    checks: [["Percorsi dell'aria", "Riscontro di prese, espulsioni e passaggi previsti tra i locali."], ["Portate", "Verifica e registrazione delle regolazioni previste dal progetto."], ["Filtri e accessi", "Controllo di installazione, verso e accessibilità dei componenti di filtrazione."], ["Comandi", "Prova delle modalità incluse e istruzioni per l'uso continuativo previsto."]],
    faq: [["La VMC raffresca come un climatizzatore?", "La ventilazione rinnova l'aria. Raffrescamento e riscaldamento attivi esistono solo se previsti da componenti specifici."], ["È sempre presente il recupero di calore?", "Solo se il sistema proposto lo comprende e ne specifica le caratteristiche."], ["Meglio puntuale o centralizzata?", "Dipende da ambienti, percorsi, spazi e opere accettabili. Il progetto confronta le soluzioni applicabili."], ["Risolve da sola muffa e umidità?", "Le cause possono essere diverse. La proposta non garantisce la risoluzione di infiltrazioni, ponti termici o altri difetti dell'edificio."], ["Occorre forare le pareti?", "Prese ed espulsioni richiedono passaggi compatibili con la soluzione e con i vincoli verificati."], ["Quando si cambiano i filtri?", "Secondo indicazioni del produttore e condizioni d'uso. Ricambi e servizio periodico vanno indicati separatamente."], ["Le portate sono uguali in ogni stanza?", "No. Dipendono dalla funzione dei locali e dal progetto di ventilazione."], ["Sono inclusi sensori e controllo remoto?", "Solo quelli elencati, con alimentazione, collegamenti e funzioni compatibili."]],
    rows: [["Ventilazione", "Configurazione VMC puntuale dimostrativa con due unità e relativi accessori", 1400], ["Posa e passaggi", "Posizionamento, attraversamenti e collegamenti nei punti descritti", 650], ["Regolazione", "Configurazione, riscontri previsti e istruzioni per filtri e comandi", 220]],
  },
} satisfies Record<string, ClmEditorial>;
