/** Editorial source for the seven original electrical intervention documents.
 * Photos are illustrative; no products, certifications or customer jobs are implied.
 */
export type EltPair = readonly [string, string];
export interface EltEditorial {
  title: string; hero: string; subtitle: string; cover: string; detail: string; context: string;
  scope: string; specs: EltPair[]; stages: EltPair[]; checks: EltPair[]; faq: EltPair[];
  rows: [string, string, number][];
}
export const ELT_EDITORIAL = {
  completo: {
    title: "Impianto elettrico completo", hero: "La tua casa.\nCollegata alle tue abitudini.",
    subtitle: "Prese, luci e circuiti progettati insieme: dalle esigenze di ogni stanza al quadro che li governa.",
    cover: "/module-art/elettrico.jpg", detail: "/pdf-stock/elettrico/tracce.jpg", context: "/pdf-stock/elettrico/risultato.jpg",
    scope: "Il rifacimento comprende i punti, le linee, il quadro e le lavorazioni descritti nel computo. Contatore, opere del distributore, rete dati, allarme, domotica, corpi illuminanti e tinteggiatura richiedono voci esplicite. Il numero di punti e il livello dell'impianto si definiscono nel progetto, senza ricavarli dalla superficie o dalle fotografie.",
    specs: [
      ["Una mappa stanza per stanza", "Posizione di arredi, piano cucina, elettrodomestici e postazioni di lavoro guida prese e comandi. Ogni punto va individuato prima delle tracce."],
      ["Circuiti distinti", "Illuminazione, prese e utilizzatori dedicati vengono organizzati in circuiti identificabili, dimensionati rispetto ai carichi e ai percorsi effettivi."],
      ["Quadro e protezioni", "Spazio disponibile, dispositivi e collegamento di terra si valutano come un insieme. Marca e caratteristiche sono riportate nella configurazione offerta."],
      ["Finiture coordinate", "Serie civile, placche, quote e allineamenti si concordano con le finiture. La presenza di un punto luce non comprende automaticamente l'apparecchio illuminante."],
    ],
    stages: [["Rilievo e dotazioni", "Raccogliamo le esigenze per ambiente, i carichi previsti e i vincoli degli spazi."], ["Disegno dei percorsi", "Confermiamo punti, circuiti, posizione del quadro e confini delle opere murarie."], ["Posa e collegamenti", "Coordiniamo canalizzazioni, cavi, apparecchi e quadro con l'avanzamento delle finiture."], ["Verifiche e consegna", "Registriamo i riscontri previsti, identifichiamo i circuiti e spieghiamo comandi e documenti."]],
    checks: [["Corrispondenza al progetto", "Riscontro di punti e circuiti con l'elenco concordato, segnalando le varianti autorizzate."], ["Misure dell'impianto", "Verifiche strumentali e funzionali previste per le opere, svolte da personale qualificato e documentate."], ["Comandi e utenze", "Prova dei punti serviti e identificazione delle linee nel quadro."], ["Consegna comprensibile", "Etichette, istruzioni e indicazioni sulle sole parti effettivamente realizzate."]],
    faq: [["Quanti punti sono compresi?", "Quelli indicati per ambiente nel computo. Prese aggiuntive e spostamenti successivi devono essere concordati."], ["Sono comprese le tracce?", "Aperture, chiusure, rasatura e pittura sono fasi diverse: la proposta precisa quali sono incluse."], ["Posso scegliere le placche?", "Sì, prima dell'ordine, tra serie e finiture quotate. Un cambio di gamma può modificare il prezzo."], ["Il contatore viene sostituito?", "Le attività sul contatore e la potenza contrattuale non sono comprese nell'impianto interno."], ["La casa può restare abitata?", "Dipende da estensione e sequenza dei lavori. Accessi e periodi senza alimentazione vanno concordati."], ["Sono compresi lampadari e faretti?", "Solo gli apparecchi elencati: predisporre un punto luce e fornire un corpo illuminante sono attività distinte."], ["Il livello è già stabilito?", "No. Dotazioni e livello vengono confermati con i dati dell'abitazione e il progetto della fornitura."], ["Quali documenti riceverò?", "Elenco delle opere, documentazione applicabile, identificazione dei circuiti e istruzioni dei componenti installati."]],
    rows: [["Distribuzione", "Canalizzazioni e linee dei circuiti della configurazione dimostrativa", 2800], ["Dotazioni", "Prese, comandi e serie civile per gli ambienti del progetto dimostrativo", 1900], ["Quadro e consegna", "Quadro, collegamenti, verifiche previste e documentazione delle opere", 1450]],
  },
  adeguamento: {
    title: "Adeguamento impianto", hero: "Partire da ciò che c'è.\nIntervenire dove serve.",
    subtitle: "Rilievo dell'esistente, componenti da conservare e opere mirate: un perimetro verificabile prima di iniziare.",
    cover: "/pdf-stock/elettrico/quadro.jpg", detail: "/pdf-stock/ristrutturazione/controllo-elettrico.jpg", context: "/pdf-stock/elettrico/risultato.jpg",
    scope: "L'adeguamento riguarda soltanto circuiti e componenti identificati nella proposta. Non equivale al rifacimento dell'intero impianto e non attribuisce prestazioni o conformità alle parti non esaminate. Difetti nascosti, tratti inaccessibili e nuove esigenze emerse durante le verifiche richiedono una valutazione e un accordo separati.",
    specs: [["Stato di partenza", "Documenti disponibili, accessibilità del quadro, linee e sintomi segnalati vengono raccolti prima di definire le opere."], ["Parti conservate", "L'elenco distingue cavi, canalizzazioni e apparecchi riutilizzabili dalle parti da sostituire, nei limiti dei riscontri effettuati."], ["Interventi mirati", "Sostituzione di dispositivi, revisione di collegamenti e integrazione di linee vengono quotate per attività e zona interessata."], ["Limiti espliciti", "Le parti non accessibili e le verifiche non eseguite restano indicate. L'intervento non nasconde le criticità rimaste fuori dal perimetro."]],
    stages: [["Raccolta delle anomalie", "Registriamo disservizi, modifiche pregresse e documenti disponibili."], ["Verifica e proposta", "Valutiamo le parti accessibili e distinguiamo interventi necessari, opzioni e limiti."], ["Adeguamento concordato", "Interveniamo sui soli circuiti elencati, comunicando eventuali nuove criticità prima di ampliare i lavori."], ["Riscontro finale", "Verifichiamo le parti interessate e consegniamo riepilogo delle opere e delle limitazioni residue."]],
    checks: [["Criticità iniziali", "Confronto tra anomalie rilevate e attività eseguite, con indicazione di quelle non risolte."], ["Componenti sostituiti", "Riscontro di identificazione, collegamenti e compatibilità con il circuito interessato."], ["Prove pertinenti", "Misure e prove relative all'estensione delle opere, con esiti e limiti del controllo."], ["Parti escluse", "Segnalazione delle zone non ispezionate e degli eventuali interventi successivi da valutare."]],
    faq: [["Adeguare significa rifare tutto?", "No. La proposta deve elencare esattamente che cosa cambia e che cosa resta."], ["Si possono riutilizzare i cavi?", "Solo dopo una valutazione delle caratteristiche e delle condizioni riscontrabili dei tratti interessati."], ["Basta sostituire il differenziale?", "La scelta dipende dal problema e dall'impianto. Un dispositivo nuovo non risolve automaticamente ogni criticità."], ["Come si gestiscono problemi nascosti?", "Vengono comunicati e quantificati prima di estendere l'intervento, salvo le misure necessarie per gestire una condizione di pericolo."], ["Dovrò lasciare la casa?", "Le interruzioni e gli accessi dipendono dalle zone interessate e si pianificano prima dell'esecuzione."], ["Sono compresi i ripristini?", "Solo quelli descritti: distinguere chiusura delle tracce, rasatura e tinteggiatura evita equivoci."], ["L'offerta copre tutto l'impianto?", "Soltanto le parti indicate. Il rapporto chiarisce anche i limiti di accessibilità e di verifica."], ["Come capisco ciò che rimane da fare?", "Il riepilogo finale distingue opere eseguite, anomalie residue e possibili approfondimenti."]],
    rows: [["Rilievo", "Esame delle parti accessibili e definizione dei circuiti interessati", 240], ["Adeguamento", "Sostituzioni e collegamenti delle sole parti della configurazione dimostrativa", 980], ["Riscontro", "Verifiche delle opere e rapporto con limitazioni residue", 260]],
  },
  punti: {
    title: "Punti luce, prese e linee", hero: "La presa giusta.\nNel posto che ti serve.",
    subtitle: "Aggiunte e spostamenti localizzati, con percorsi, finiture e alimentazioni definiti prima del lavoro.",
    cover: "/pdf-stock/elettrico/risultato.jpg", detail: "/pdf-stock/elettrico/tracce.jpg", context: "/pdf-stock/elettrico/sera.jpg",
    scope: "La proposta comprende esclusivamente i punti e i tratti di linea elencati. Numero di frutti, placche, lunghezze, posa a vista o incassata e ripristini devono risultare nel computo. L'aggiunta di una presa non implica l'adeguamento dell'intero impianto né l'idoneità del circuito a qualsiasi carico.",
    specs: [["Punti riconoscibili", "Ogni presa, comando o uscita luce è associata a un ambiente e a una posizione; si precisano numero di moduli e funzione."], ["Percorso della linea", "Distanza, attraversamenti e modalità di posa incidono sul lavoro. Un percorso esistente si riusa solo se accessibile e compatibile."], ["Carico da alimentare", "Un elettrodomestico dedicato richiede la valutazione del circuito e delle protezioni, non soltanto una nuova presa."], ["Serie e ripristini", "Compatibilità delle placche, colore e finitura sono definiti prima dell'acquisto, insieme al confine delle opere murarie."]],
    stages: [["Posizioni e utilizzi", "Segniamo i punti richiesti sulla disposizione degli arredi."], ["Percorsi e quantità", "Confermiamo linee, accessibilità, finiture e quantità dei componenti."], ["Posa localizzata", "Programmiamo l'interruzione del circuito ed eseguiamo i tratti concordati."], ["Prova dei punti", "Controlliamo le funzioni previste e riepiloghiamo le modifiche effettuate."]],
    checks: [["Posizione", "Riscontro delle quote e della destinazione dei punti rispetto all'accordo."], ["Collegamenti", "Verifica dei tratti modificati e della loro integrazione nel circuito."], ["Funzioni", "Prova di prese, comandi e uscite luce previste nell'intervento."], ["Finitura", "Controllo di placche, fissaggi e soli ripristini compresi."]],
    faq: [["Che cosa conta come punto?", "La definizione dipende dalla voce: presa, comando e uscita luce vanno identificati con moduli e dotazione."], ["La linea è compresa nel punto?", "Occorre leggere lunghezza e percorso inclusi. Tratti aggiuntivi possono avere una voce separata."], ["È possibile evitare le tracce?", "Si valuta l'uso di canalizzazioni esistenti o una posa a vista concordata, senza promettere percorsi non verificati."], ["La presa può alimentare il forno?", "Carico, circuito e protezione devono essere verificati prima di destinare il punto a quell'utilizzo."], ["La placca sarà uguale alle altre?", "Si controllano serie e disponibilità. Componenti fuori produzione possono richiedere una soluzione concordata."], ["È inclusa la pittura?", "Solo se indicata separatamente: chiudere una traccia non equivale a ritinteggiare la parete."], ["Posso cambiare posizione durante i lavori?", "Prima si verificano nuovi percorsi, tempi e costi, poi si conferma la variante."], ["Viene controllato l'intero impianto?", "Le verifiche riguardano l'intervento e le parti necessarie alla sua valutazione; un esame completo richiede un incarico specifico."]],
    rows: [["Punti", "Aggiunta di prese e comandi nelle posizioni della configurazione dimostrativa", 420], ["Linee", "Tratti di alimentazione sui percorsi accessibili indicati", 310], ["Finiture e prova", "Placche, fissaggi e riscontro funzionale dei punti modificati", 170]],
  },
  quadro: {
    title: "Quadro elettrico", hero: "Circuiti ordinati.\nComandi riconoscibili.",
    subtitle: "Un quadro definito sui carichi e sulle linee reali, con protezioni, collegamenti ed etichette coerenti.",
    cover: "/pdf-stock/elettrico/quadro.jpg", detail: "/module-art/elettrico-quadro-dettaglio-v1.jpg", context: "/pdf-stock/fotovoltaico/quadro-elettrico.jpg",
    scope: "L'offerta comprende carpenteria, dispositivi e collegamenti del quadro descritti. Linee a valle, montante, impianto di terra, contatore e opere murarie restano esclusi salvo voce specifica. La sostituzione del quadro non rinnova automaticamente i circuiti esistenti; compatibilità e criticità rilevate devono essere documentate.",
    specs: [["Circuiti censiti", "Si identificano utenze, carichi e linee in arrivo e in partenza, chiarendo eventuali circuiti non riconoscibili."], ["Carpenteria e spazio", "Ingombri, posa, accessibilità e spazio per i dispositivi si verificano sul posto; eventuali moduli liberi vengono esplicitati."], ["Protezioni coordinate", "Tipologia e caratteristiche dei dispositivi si definiscono in relazione alle linee e agli utilizzatori; la foto non è uno schema di cablaggio."], ["Etichette e schema", "Ogni circuito deve essere riconoscibile nella configurazione consegnata, con legenda e documentazione riferite alle opere."]],
    stages: [["Censimento", "Rileviamo quadro, circuiti, carichi e disponibilità degli spazi."], ["Configurazione", "Definiamo involucro, dispositivi, morsetti e identificazione delle linee."], ["Sostituzione programmata", "Concordiamo il periodo senza alimentazione e le utenze che richiedono organizzazione preventiva."], ["Prove e legenda", "Verifichiamo il quadro e consegniamo l'identificazione dei circuiti e i documenti previsti."]],
    checks: [["Configurazione", "Riscontro dei dispositivi installati rispetto all'elenco della proposta."], ["Collegamenti", "Controllo dei collegamenti e delle caratteristiche pertinenti alle linee interessate."], ["Prove", "Verifiche strumentali e funzionali previste per il quadro e per le parti coinvolte."], ["Identificazione", "Coerenza tra etichette, circuito servito e schema consegnato."]],
    faq: [["Basta un quadro più grande?", "Lo spazio è solo una delle condizioni: dispositivi e collegamenti devono essere scelti sui circuiti reali."], ["Si mantengono i vecchi interruttori?", "Solo quelli espressamente ritenuti compatibili e indicati come conservati."], ["Sono comprese nuove linee?", "Soltanto se elencate. Sostituire il quadro non include il rifacimento dei cavi a valle."], ["Quanto dura l'interruzione?", "Si definisce dopo il rilievo e in base alla configurazione; l'offerta non presume una durata uguale per tutti."], ["È inclusa la protezione dalle sovratensioni?", "La presenza e la tipologia dei dispositivi devono risultare nella configurazione quotata."], ["L'impianto di terra è compreso?", "Controlli e opere sulla terra si precisano separatamente, secondo quanto necessario per l'intervento."], ["Posso aggiungere circuiti in futuro?", "Si può concordare spazio di riserva, ma l'aggiunta richiederà comunque una verifica di capacità e compatibilità."], ["Come riconoscerò gli interruttori?", "La legenda associa i comandi ai circuiti effettivamente identificati e viene spiegata alla consegna."]],
    rows: [["Carpenteria", "Involucro e dotazioni di montaggio del quadro dimostrativo", 320], ["Dispositivi", "Protezioni e morsetti della configurazione dimostrativa", 680], ["Collegamenti e prove", "Sostituzione, identificazione circuiti e verifiche delle parti interessate", 460]],
  },
  domotica: {
    title: "Domotica e automazioni", hero: "La casa risponde.\nAlle tue scelte.",
    subtitle: "Luci, oscuranti e scenari coordinati: funzioni comprensibili, dispositivi compatibili e comandi da provare insieme.",
    cover: "/module-art/elettrico-domotica-cover.jpg", detail: "/module-art/elettrico-domotica-editorial.jpg", context: "/module-art/elettrico.jpg",
    scope: "Sono comprese le funzioni e le automazioni elencate, con dispositivi e integrazioni identificati. Rete Wi-Fi, connessione internet, abbonamenti cloud, assistenti vocali, motori e apparecchi non descritti non sono inclusi. Una scena dimostrativa non prova la compatibilità con tutti i prodotti presenti nell'abitazione.",
    specs: [["Funzioni prima dei dispositivi", "Definiamo cosa deve succedere a un comando: accensione, chiusura di oscuranti o richiamo di una scena, distinguendo ogni funzione inclusa."], ["Compatibilità verificata", "Protocollo, alimentazione, carichi comandabili e gateway si scelgono sulla configurazione reale, non sulla sola dicitura smart."], ["Rete e continuità", "Si distinguono funzioni locali e remote e si chiarisce cosa resta utilizzabile senza internet o in caso di indisponibilità del servizio."], ["Accessi del proprietario", "Account, ruoli, app e modalità di consegna degli accessi si concordano; password e credenziali non vengono stampate nel preventivo."]],
    stages: [["Scenari desiderati", "Descriviamo per ambiente i comandi e gli automatismi utili."], ["Mappa delle integrazioni", "Verifichiamo dispositivi esistenti, protocollo, rete e limiti delle funzioni."], ["Installazione e configurazione", "Configuriamo dispositivi e scene comprese, con nomi comprensibili all'utilizzatore."], ["Prova accompagnata", "Proviamo gli scenari, spieghiamo i comandi manuali e consegniamo la gestione degli accessi."]],
    checks: [["Scena per scena", "Prova delle azioni concordate e dei dispositivi coinvolti."], ["Comandi manuali", "Riscontro dei comandi disponibili senza app e delle condizioni di funzionamento locale."], ["Accesso remoto", "Prova delle sole funzioni remote incluse, se rete e servizi necessari sono disponibili."], ["Consegna degli accessi", "Verifica che il proprietario disponga dei ruoli concordati e delle indicazioni per la gestione successiva."]],
    faq: [["Funziona senza internet?", "Dipende dall'architettura. La proposta distingue funzioni locali, remote e servizi cloud."], ["Posso usare gli interruttori normali?", "Si definiscono i comandi manuali previsti per ogni funzione e li si prova alla consegna."], ["Sono comprese le tapparelle motorizzate?", "Motori, alimentazioni e adattamenti sono inclusi solo se elencati; automatizzare il comando non significa fornire la tapparella."], ["È compatibile con il mio assistente vocale?", "La specifica integrazione deve essere verificata e indicata nella fornitura."], ["Ci sono canoni?", "App, cloud o servizi di terzi possono richiedere condizioni separate, da chiarire prima dell'ordine."], ["Chi possiede gli account?", "La consegna stabilisce intestazione e ruoli del proprietario, insieme alle modalità di assistenza autorizzata."], ["Posso cambiare gli scenari?", "Le modifiche accessibili all'utente vengono spiegate; programmazioni aggiuntive possono richiedere un servizio dedicato."], ["Le foto mostrano il sistema venduto?", "No, illustrano l'uso degli ambienti. Modelli e funzioni sono quelli elencati nella proposta."]],
    rows: [["Dispositivi", "Moduli di comando e gateway della configurazione domotica dimostrativa", 1250], ["Integrazioni", "Collegamenti delle sole luci e automazioni concordate", 580], ["Scenari", "Configurazione, prova delle scene e consegna degli accessi", 390]],
  },
  videocitofonia: {
    title: "Videocitofonia", hero: "Vedere chi arriva.\nRispondere con semplicità.",
    subtitle: "Ingresso, postazioni interne e apertura coordinati: una configurazione commisurata agli accessi e al cablaggio esistente.",
    cover: "/module-art/elettrico-videocitofonia-cover.jpg", detail: "/module-art/elettrico-videocitofonia-editorial.jpg", context: "/pdf-stock/elettrico/risultato.jpg",
    scope: "La proposta comprende solo ingressi, utenze e postazioni elencati. Compatibilità del cablaggio, alimentatori, serratura e parti comuni va verificata; rifacimento delle dorsali, rete dati, opere condominiali e servizi remoti richiedono voci specifiche. Le foto illustrano gli spazi e i percorsi, non il modello di videocitofono fornito.",
    specs: [["Ingressi e chiamate", "Si contano accessi, pulsanti, unità servite e postazioni interne, chiarendo a chi deve arrivare ciascuna chiamata."], ["Cablaggio esistente", "Tipologia, percorso e condizioni dei cavi determinano la possibilità di riuso. Un sistema nuovo non è automaticamente compatibile con ogni dorsale."], ["Postazione esterna", "Posizione, visibilità, illuminazione, esposizione e ingombri si confrontano con il prodotto scelto e con l'accesso reale."], ["Apertura e app", "Il comando di apertura va coordinato con la serratura; la risposta da smartphone è inclusa solo se la specifica funzione è quotata."]],
    stages: [["Rilievo degli accessi", "Identifichiamo ingressi, postazioni, cablaggi e parti comuni interessate."], ["Scelta del sistema", "Confermiamo dispositivi, alimentazioni, riuso dei cavi e funzioni di apertura."], ["Posa e associazioni", "Installiamo le postazioni previste e associamo chiamate e comandi alle utenze concordate."], ["Chiamata di prova", "Proviamo audio, video e apertura con l'utilizzatore e consegniamo le istruzioni."]],
    checks: [["Destinazione chiamate", "Ogni pulsante viene provato rispetto alla postazione interna associata."], ["Audio e video", "Riscontro di comunicazione e inquadratura nelle condizioni dell'accesso reale."], ["Apertura", "Prova del comando sulla serratura prevista, distinguendo eventuali accessi esclusi."], ["Funzioni aggiuntive", "Prova di app o deviazione di chiamata soltanto se comprese e con i servizi necessari disponibili."]],
    faq: [["Si possono mantenere i fili?", "Il riuso dipende dal sistema proposto e dalle condizioni del cablaggio, da verificare prima dell'ordine."], ["Quanti monitor sono inclusi?", "Il computo indica il numero di postazioni per ciascuna unità servita."], ["Posso rispondere dal telefono?", "Solo con dispositivi e servizi compatibili, se questa funzione è inclusa nella configurazione."], ["La serratura viene sostituita?", "La sostituzione deve essere espressamente quotata; il collegamento al comando non implica una serratura nuova."], ["Serve coinvolgere il condominio?", "Se si interviene su parti comuni, la disponibilità degli accessi e gli accordi necessari devono essere definiti prima dei lavori."], ["È inclusa la registrazione video?", "Non è implicita. Le funzioni del prodotto e le modalità d'uso vanno chiarite separatamente."], ["La pulsantiera entra nello spazio esistente?", "Misure e montaggio si verificano sul posto; adattamenti murari o cornici devono risultare nell'offerta."], ["Come viene verificata la consegna?", "Con chiamate, riscontro audio e video e prova dell'apertura sui soli accessi compresi."]],
    rows: [["Postazioni", "Postazione esterna e interna della configurazione videocitofonica dimostrativa", 720], ["Collegamenti", "Alimentazione e collegamenti sui percorsi concordati", 330], ["Configurazione", "Associazione chiamate, prove audio-video e comando di apertura", 180]],
  },
  ricarica: {
    title: "Ricarica veicoli elettrici", hero: "Rientrare a casa.\nPreparare il prossimo viaggio.",
    subtitle: "Dispositivo, linea e gestione della potenza: il punto di ricarica nasce dalle condizioni reali del tuo posto auto.",
    cover: "/module-art/elettrico-ricarica.jpg", detail: "/pdf-stock/fotovoltaico/componenti-elettrici.jpg", context: "/pdf-stock/fotovoltaico/quadro-elettrico.jpg",
    scope: "La fornitura comprende il dispositivo, la linea, le protezioni e le funzioni descritte. Aumento di potenza, lavori del distributore, scavi, attraversamenti di parti comuni, rete dati e integrazione fotovoltaica non sono impliciti. Potenza effettiva e tempi di ricarica dipendono anche dal veicolo e dalla disponibilità elettrica, non soltanto dal valore nominale della wallbox.",
    specs: [["Disponibilità elettrica", "Fornitura, carichi contemporanei e caratteristiche dell'impianto vengono valutati prima di scegliere la potenza configurata."], ["Percorso fino al posto auto", "Distanza, posa, attraversamenti e posizione del dispositivo definiscono la linea e le opere accessorie da quotare."], ["Dispositivo e protezioni", "Modello, connettore, installazione e protezioni si coordinano con le istruzioni del produttore e con l'impianto reale."], ["Gestione dei carichi", "Limitazione e regolazione dinamica sono funzioni distinte: sensori, collegamenti e impostazioni sono inclusi solo se indicati."]],
    stages: [["Auto e posto di ricarica", "Raccogliamo caratteristiche del veicolo, uso previsto, fornitura e posizione di sosta."], ["Linea e configurazione", "Confermiamo percorso, dispositivo, protezioni, potenza impostata e funzioni incluse."], ["Installazione", "Coordiniamo accessi, eventuali attraversamenti e collegamenti delle sole opere quotate."], ["Prova di ricarica", "Verifichiamo le funzioni previste e spieghiamo limiti, comandi e gestione degli accessi."]],
    checks: [["Linea dedicata", "Riscontro della linea e delle protezioni previste nella configurazione."], ["Potenza impostata", "Confronto tra impostazioni, disponibilità dell'impianto e caratteristiche del dispositivo."], ["Sessione di ricarica", "Prova funzionale nelle condizioni disponibili, indicando eventuali limiti di veicolo o rete."], ["Gestione carichi", "Prova della regolazione e dell'accesso autorizzato se compresi, con consegna delle istruzioni."]],
    faq: [["Devo aumentare la potenza?", "Si valuta sulla fornitura, sugli altri carichi e sull'uso previsto. L'eventuale pratica non è compresa automaticamente."], ["Quanto tempo impiegherà l'auto?", "Dipende da energia richiesta, caricatore di bordo, potenza disponibile e condizioni d'uso. Non si promette un tempo dal solo valore della wallbox."], ["È inclusa la gestione dinamica?", "Solo se sono elencati funzione, sensore e collegamenti necessari."], ["Posso usare il fotovoltaico?", "L'integrazione richiede compatibilità e configurazione specifiche, da descrivere nella proposta."], ["Sono compresi scavi e attraversamenti?", "Solo quelli misurati e quotati. Distanze e passaggi nelle parti comuni si verificano prima."], ["Serve internet?", "Dipende dalle funzioni: ricarica locale, app, report e servizi remoti hanno requisiti diversi."], ["La possono usare altre persone?", "Modalità di autorizzazione, chiavi o account si definiscono con il dispositivo scelto."], ["Ci sono incentivi già conteggiati?", "No. L'anteprima non applica agevolazioni; un eventuale beneficio richiede una valutazione separata dei requisiti effettivi."]],
    rows: [["Dispositivo", "Punto di ricarica e accessori della configurazione dimostrativa", 980], ["Infrastruttura", "Linea e protezioni sul percorso dimostrativo fino al posto auto", 760], ["Messa in servizio", "Impostazioni, prove delle funzioni incluse e istruzioni d'uso", 260]],
  },
} satisfies Record<string, EltEditorial>;
