/** Editorial content only: illustrative scopes, never a technical project or price list. */
export type FacPair = readonly [title: string, text: string];
export type FacPriceRow = readonly [chapter: string, description: string, unit: "mq" | "ml" | "corpo" | "cad", quantity: number, price: number];
export interface FacEditorialContent {
  title: string; subtitle: string; short: string; cover: string;
  needs: readonly FacPair[]; solution: readonly FacPair[]; specs: readonly FacPair[];
  included: readonly FacPair[]; excluded: readonly FacPair[]; stages: readonly FacPair[];
  protection: readonly FacPair[]; checks: readonly FacPair[]; documents: readonly FacPair[];
  faq: readonly FacPair[]; prices: readonly FacPriceRow[];
}

const facade = "/module-art/facciate.jpg";
export const FAC_EDITORIAL = {
  cappotto: {
    title: "Il comfort parte\ndall'involucro.",
    subtitle: "Cappotto esterno: supporto, sistema isolante e raccordi definiti prima della posa.",
    short: "Superfici, strati e dettagli. Un sistema da progettare sul tuo edificio.", cover: "/module-art/facciate-cappotto-dettaglio.jpg",
    needs: [["Leggere l'esistente", "Individuare superfici, discontinuità e stato degli intonaci prima di scegliere il sistema."], ["Definire lo spessore", "Confrontare ingombri, aperture e obiettivi del progetto energetico."], ["Organizzare gli accessi", "Concordare ponteggi, percorsi e interferenze con chi utilizza l'edificio."]],
    solution: [["Sistema coordinato", "Isolante, collante, fissaggi, rasatura e finitura identificati nella specifica dell'offerta."], ["Nodi espliciti", "Zoccolatura, imbotti, davanzali e attacchi in quota descritti con i rispettivi limiti."], ["Quantità leggibili", "Superfici e accessori misurati con criteri dichiarati nel computo."]],
    specs: [["Supporto e preparazione", "Verificare consistenza e adesione del fondo; quantificare pulizie e ripristini prima della posa."], ["Isolante e fissaggio", "Indicare materiale, spessore e sistema di posa. Tipologia e quantità dei fissaggi dipendono da supporto e progetto."], ["Rasatura armata", "Definire rasante, rete, sovrapposizioni e rinforzi ai bordi delle aperture secondo il sistema scelto."], ["Raccordi e finitura", "Specificare profili, gocciolatoi, zoccolatura, tessitura e colore; risolvere i dettagli dei davanzali prima dell'ordine."]],
    included: [["Superfici individuate", "Isolamento dei soli prospetti e delle porzioni misurate nel computo."], ["Ciclo descritto", "Preparazioni, strati e finiture nella configurazione confermata."], ["Accessori elencati", "Profili e raccordi solo nelle quantità e nelle tipologie riportate."]],
    excluded: [["Incarichi tecnici", "Progetto energetico, pratiche e verifiche specialistiche non comprese se prive di voce dedicata."], ["Opere estranee", "Serramenti, coperture, impianti e modifiche strutturali esclusi."], ["Accessi ulteriori", "Occupazioni, noleggi prolungati e opere provvisionali diverse dalla voce di esempio da quotare separatamente."]],
    stages: [["Rilievo", "Superfici, supporto e nodi da confermare."], ["Scelta del sistema", "Materiale, spessore, dettagli e campione di finitura."], ["Preparazione", "Accessi, protezioni e ripristino dei fondi previsti."], ["Posa e raccordi", "Strati e punti singolari secondo le specifiche concordate."], ["Finitura e riscontro", "Tempi di maturazione, verifiche e consegna delle informazioni disponibili."]],
    protection: [["Ponteggi e percorsi", "Accessi e protezioni da definire nel piano di cantiere e valorizzare nelle voci dell'offerta."], ["Parti conservate", "Individuare serramenti, pavimentazioni e impianti da proteggere."], ["Condizioni ambientali", "Pianificare la posa in funzione dei limiti applicativi dei prodotti e del meteo."]],
    checks: [["Fondo", "Riscontri sulla preparazione delle superfici accessibili prima della posa."], ["Strati e nodi", "Verifiche previste su continuità, fissaggi e raccordi prima della finitura."], ["Finitura", "Controllo visivo con campione concordato e annotazione delle riserve."]],
    documents: [["Materiali", "Schede del sistema e dei prodotti effettivamente forniti, secondo disponibilità."], ["Dettagli", "Elenco delle scelte approvate e delle eventuali varianti."], ["Uso e manutenzione", "Indicazioni pertinenti alla finitura installata; attestazioni solo se dovute e incluse nell'incarico."]],
    faq: [["Quale isolante e quale spessore sono previsti?", "Vanno definiti nella specifica tecnica dopo le verifiche sul fabbricato. Questo modello non seleziona automaticamente un materiale o uno spessore."], ["Il cappotto garantisce un risparmio in bolletta?", "Il risultato dipende dall'edificio, dagli impianti e dall'uso. Non sono promesse percentuali di risparmio né salti di classe energetica."], ["Davanzali e imbotti sono compresi?", "Solo i raccordi descritti e misurati. Prolungamenti o sostituzioni richiedono una voce dedicata."], ["Il ponteggio è incluso?", "L'offerta deve precisare tipo di accesso, durata e oneri. La voce dimostrativa non copre qualsiasi ponteggio o occupazione."], ["Si può posare su un intonaco ammalorato?", "L'idoneità del supporto va verificata. Le rimozioni e i ripristini necessari si definiscono prima dell'esecuzione."], ["Chi prepara il progetto energetico?", "L'incarico e il professionista vanno concordati separatamente se non esplicitamente compresi nel preventivo."], ["Quanto dura il cantiere?", "Il calendario dipende da quantità, disponibilità degli accessi, meteo e tempi del ciclo. Le date vengono concordate prima dell'avvio."], ["Sono previste agevolazioni o garanzie particolari?", "Nessuna agevolazione è calcolata in automatico. Eventuali garanzie aggiuntive devono essere documentate con condizioni e soggetto responsabile."]],
    prices: [["Preparazioni", "Cappotto: allestimento e protezioni nell'ambito dimostrativo", "corpo", 1, 1800], ["Preparazioni", "Cappotto: preparazione del supporto individuato", "mq", 120, 12], ["Sistema isolante", "Cappotto: pannelli e posa del sistema da specificare", "mq", 120, 62], ["Sistema isolante", "Cappotto: rasatura armata del sistema previsto", "mq", 120, 20], ["Raccordi", "Cappotto: profili e raccordi descritti", "ml", 45, 18], ["Finitura", "Cappotto: finitura nella tessitura concordata", "mq", 120, 17]],
  },
  rifacimento: {
    title: "Una nuova superficie.\nLa facciata ritrova ordine.", subtitle: "Ripristino di intonaci e finiture esterne, senza sistema a cappotto.", short: "Rimozioni mirate, fondi compatibili e finiture concordate.", cover: facade,
    needs: [["Mappare il degrado", "Distinguere le parti distaccate da quelle conservabili sui prospetti accessibili."], ["Scegliere un ciclo compatibile", "Leggere il supporto e le finiture esistenti prima di definire i prodotti."], ["Gestire il risultato estetico", "Concordare campioni, raccordi e limiti di uniformità rispetto alle porzioni mantenute."]],
    solution: [["Rimozioni misurate", "Quantità e profondità dei ripristini riferite alle zone individuate."], ["Supporti preparati", "Ricostruzione e regolarizzazione nei soli ambiti del computo."], ["Finitura condivisa", "Ciclo, grana e colore scelti dopo i riscontri sul fondo."]],
    specs: [["Indagine delle superfici", "Mappare le zone accessibili e precisare quali indagini ulteriori restano da eseguire."], ["Rimozione e ricostruzione", "Indicare spessore di rimozione, malta compatibile e criterio di misurazione dei rappezzi."], ["Regolarizzazione", "Descrivere la rasatura prevista e gli eventuali rinforzi locali, senza presumere un trattamento strutturale."], ["Finitura esterna", "Identificare fondo, rivestimento o pittura e campione approvato; rispettare i tempi del ciclo selezionato."]],
    included: [["Intonaci indicati", "Rimozioni e ripristini limitati alle quantità espresse."], ["Fondi e finitura", "Preparazione e ciclo superficiale descritti per i prospetti scelti."], ["Raccordi locali", "Riprese presso gli elementi conservati nei limiti dell'offerta."]],
    excluded: [["Isolamento", "Cappotto e altre coibentazioni non fanno parte di questo intervento."], ["Strutture e infiltrazioni", "Consolidamenti e soluzione delle cause di infiltrazione non sono presunti nel ripristino superficiale."], ["Elementi accessori", "Sostituzione di lattonerie, serramenti e impianti da quotare se necessaria."]],
    stages: [["Mappatura", "Identificazione delle porzioni da mantenere o rimuovere."], ["Preparazioni", "Protezioni, accessi e rimozioni previste."], ["Ripristini", "Ricostruzione delle zone concordate e attesa del ciclo."], ["Finiture", "Regolarizzazione, fondo e colore approvato."], ["Consegna", "Riscontro dei prospetti e annotazione delle eventuali riprese."]],
    protection: [["Zone sottostanti", "Delimitare aree e percorsi interessati dalle lavorazioni in quota."], ["Elementi mantenuti", "Proteggere serramenti, soglie e pavimenti individuati."], ["Residui", "Definire raccolta e gestione dei materiali rimossi nelle relative voci."]],
    checks: [["Adesione del fondo", "Riscontro delle aree preparate prima dei ripristini."], ["Raccordi", "Controllo dei passaggi fra intonaco nuovo e conservato."], ["Aspetto finale", "Confronto della finitura con il campione approvato nelle condizioni concordate."]],
    documents: [["Ciclo scelto", "Elenco dei prodotti e schede disponibili."], ["Quantità finali", "Riepilogo delle superfici effettivamente concordate e delle varianti."], ["Manutenzione", "Indicazioni per osservare e mantenere le finiture eseguite."]],
    faq: [["Questo intervento comprende il cappotto?", "No. Il perimetro riguarda intonaci e finiture; l'isolamento richiede una proposta dedicata."], ["Va rimosso tutto l'intonaco?", "Lo decide la verifica delle superfici. Il computo distingue rimozioni locali e superfici di finitura."], ["Le crepe scompaiono definitivamente?", "Il ripristino della superficie non dimostra la risoluzione della causa. Fessure attive o sospette richiedono valutazioni dedicate."], ["Come si misura la facciata?", "Il criterio per vuoti, spallette e cornici deve essere dichiarato nel computo e verificato con il rilievo."], ["Il nuovo colore sarà identico a quello vecchio?", "Non è garantita una corrispondenza perfetta. Esposizione, materiali e invecchiamento possono rendere visibili i raccordi."], ["Sono comprese le lattonerie?", "Solo se riportate in una voce specifica con elementi e quantità. La finitura non comporta automaticamente la loro sostituzione."], ["Quando si può applicare la finitura?", "Dopo le verifiche e i tempi previsti dal ciclo scelto, tenendo conto delle condizioni ambientali."], ["Il prezzo cambia se emergono altre parti distaccate?", "Le quantità ulteriori vanno documentate e concordate prima di estendere le lavorazioni; non si presume una copertura illimitata."]],
    prices: [["Preparazioni", "Facciata: accessi e protezioni del prospetto di esempio", "corpo", 1, 1400], ["Rimozioni", "Facciata: rimozione degli intonaci individuati", "mq", 35, 18], ["Ripristini", "Facciata: ricostruzione dell'intonaco nelle zone previste", "mq", 35, 32], ["Fondi", "Facciata: rasatura delle superfici indicate", "mq", 100, 16], ["Fondi", "Facciata: fondo compatibile con il ciclo selezionato", "mq", 100, 5], ["Finitura", "Facciata: rivestimento di finitura concordato", "mq", 100, 19]],
  },
  balconi: {
    title: "Balconi e frontalini.\nOgni dettaglio ha un perimetro.", subtitle: "Ripristini localizzati di elementi esterni, con accessi e verifiche da definire.", short: "Elementi, degrado e quantità. Ripristini descritti uno per uno.", cover: "/module-art/facciate-balconi-dettaglio.jpg",
    needs: [["Identificare gli elementi", "Numerare balconi, frontalini e intradossi interessati senza estendere l'offerta all'intero edificio."], ["Valutare il degrado", "Distinguere finiture degradate da condizioni che richiedono un approfondimento tecnico."], ["Coordinare gli accessi", "Concordare l'uso delle zone sottostanti e dei balconi durante i lavori."]],
    solution: [["Mappa delle porzioni", "Elementi e superfici collegati a un elenco verificabile."], ["Ciclo di ripristino", "Preparazione e materiali scelti in funzione delle condizioni rilevate."], ["Dettagli separati", "Gocciolatoi, pavimentazioni, impermeabilizzazioni e parapetti trattati come ambiti distinti."]],
    specs: [["Porzioni e profondità", "Identificare frontalini e intradossi, misure e limiti delle rimozioni previste."], ["Ferri eventualmente scoperti", "Trattamenti solo previa valutazione delle condizioni e specifica del tecnico; non equivalgono a un consolidamento."], ["Ricostruzioni", "Definire malta, spessori, preparazione e tempi applicativi compatibili con il supporto."], ["Bordi e finiture", "Specificare profili, gocciolatoi e ciclo protettivo; raccordi con gli strati superiori solo se inclusi."]],
    included: [["Elementi numerati", "Ripristino delle porzioni individuate nell'elenco e nel computo."], ["Ciclo previsto", "Preparazione, ricostruzione e finitura nelle profondità concordate."], ["Bordi descritti", "Gocciolatoi e profili solo nelle quantità espresse."]],
    excluded: [["Interventi strutturali", "Verifiche di portata, consolidamenti e sostituzione delle armature esclusi da questo esempio."], ["Tenuta superiore", "Impermeabilizzazione e pavimentazione del balcone escluse se non descritte."], ["Parapetti", "Adeguamento, sostituzione e verniciatura dei parapetti da quotare separatamente."]],
    stages: [["Rilievo degli elementi", "Numerazione e valutazioni preliminari del degrado."], ["Accessi e delimitazioni", "Disponibilità dei balconi e delle zone sottostanti."], ["Preparazione", "Rimozioni previste e verifica delle superfici scoperte."], ["Ripristino", "Ricostruzioni e raccordi concordati, con tempi del ciclo."], ["Finitura", "Riscontro delle porzioni eseguite e chiusura delle riserve."]],
    protection: [["Aree inferiori", "Delimitazioni da definire prima di lavorare sopra passaggi o spazi utilizzati."], ["Utilizzo dei balconi", "Comunicare limitazioni temporanee e spostamento degli oggetti presenti."], ["Parti conservate", "Individuare parapetti, pavimenti e serramenti da proteggere."]],
    checks: [["Supporto scoperto", "Registrare eventuali condizioni diverse da quelle previste prima di proseguire."], ["Geometria dei bordi", "Riscontro delle ricostruzioni e dei gocciolatoi inclusi."], ["Finitura", "Controllo delle superfici trattate e dei raccordi concordati."]],
    documents: [["Mappa elementi", "Elenco dei balconi e delle porzioni effettivamente trattate."], ["Materiali", "Schede dei prodotti e indicazioni di manutenzione disponibili."], ["Riserve", "Annotazioni dei problemi esclusi e delle eventuali verifiche da completare."]],
    faq: [["Il ripristino certifica la sicurezza del balcone?", "No. Questo modello non sostituisce una valutazione strutturale né certifica la portata dell'elemento."], ["Sono comprese le armature?", "L'eventuale trattamento dei ferri scoperti deve essere descritto dopo la valutazione tecnica; sostituzioni e rinforzi non sono presunti."], ["Si risolvono anche le infiltrazioni?", "Solo le lavorazioni specificamente progettate e incluse per la causa individuata possono riguardare la tenuta. Il frontalino da solo non la garantisce."], ["La pavimentazione verrà rifatta?", "Non in questo esempio. Demolizione, impermeabilizzazione e nuova pavimentazione richiedono voci separate."], ["Si può usare il balcone durante i lavori?", "Limitazioni e tempi di accesso vanno concordati in funzione delle lavorazioni e delle protezioni previste."], ["I parapetti sono inclusi?", "No, salvo voce specifica. La protezione del parapetto esistente non equivale alla sua riparazione o sostituzione."], ["Come sono conteggiati frontalini e intradossi?", "Con unità di misura dichiarate e riferimenti agli elementi: metri lineari o metri quadrati secondo la voce."], ["Cosa succede se il degrado è più esteso?", "Si documenta la condizione e si concordano approfondimenti, quantità e varianti prima di estendere l'intervento."]],
    prices: [["Preparazioni", "Balconi: accessi e delimitazioni per gli elementi di esempio", "corpo", 1, 950], ["Rimozioni", "Balconi: rimozioni superficiali dei frontalini individuati", "ml", 24, 18], ["Ripristini", "Balconi: ricostruzione locale dei frontalini previsti", "ml", 24, 42], ["Ripristini", "Balconi: ripresa superficiale degli intradossi individuati", "mq", 18, 35], ["Bordi", "Balconi: profili gocciolatoio nelle tratte indicate", "ml", 24, 16], ["Finitura", "Balconi: ciclo di finitura delle superfici previste", "mq", 32, 19]],
  },
  tinteggiatura: {
    title: "Il colore dell'edificio.\nUna scelta da condividere.", subtitle: "Preparazione e tinteggiatura delle superfici esterne su supporti idonei.", short: "Supporto, ciclo e campione colore. Il rinnovo delle superfici esterne.", cover: "/module-art/facciate-tinteggiatura-dettaglio.jpg",
    needs: [["Controllare il fondo", "Distinguere sporco e sfarinamento dai difetti che richiedono ripristini ulteriori."], ["Definire il colore", "Confrontare campioni sul posto, grana e accostamenti con le parti conservate."], ["Proteggere l'esistente", "Individuare serramenti, soglie e percorsi interessati dalle lavorazioni."]],
    solution: [["Preparazione mirata", "Pulizia e piccoli ripristini solo nell'estensione indicata."], ["Ciclo identificato", "Fondo e pittura scelti in funzione del supporto e dell'esposizione."], ["Campione approvato", "Colore e aspetto concordati prima dell'applicazione estesa."]],
    specs: [["Pulizia del supporto", "Definire modalità e limiti della pulizia dopo la lettura del fondo; non presumere trattamenti risananti."], ["Piccole riprese", "Quantificare stuccature e ripristini superficiali separatamente dalla pittura."], ["Fondo e pittura", "Indicare prodotti, mani e modalità applicative secondo il ciclo selezionato."], ["Campione e raccordi", "Individuare codice colore, grana e superfici campione; considerare le differenze con le porzioni non trattate."]],
    included: [["Superfici indicate", "Tinteggiatura dei prospetti o delle porzioni presenti nel computo."], ["Preparazione descritta", "Pulizia, fondo e riprese limitate alle rispettive voci."], ["Ciclo colore", "Applicazione della finitura confermata sul campione."]],
    excluded: [["Intonaci estesi", "Rifacimento degli intonaci e distacchi diffusi non compresi nella semplice tinteggiatura."], ["Cause di umidità", "Eliminazione di infiltrazioni, risalita o altre cause di degrado esclusa."], ["Altri materiali", "Verniciatura di metalli, legno e serramenti da valutare separatamente."]],
    stages: [["Valutazione", "Fondo, estensione e accessibilità delle superfici."], ["Campionatura", "Scelta e approvazione del colore."], ["Preparazione", "Protezioni, pulizia e riprese comprese."], ["Applicazione", "Fondo e pittura con attese del ciclo e condizioni adatte."], ["Riscontro", "Controllo visivo delle superfici concordate e pulizia finale prevista."]],
    protection: [["Mascherature", "Definire superfici delicate, vetri e profili da proteggere."], ["Aree esterne", "Organizzare percorsi e aree di lavoro secondo l'accesso scelto."], ["Meteo", "Calendario da adeguare ai limiti di applicazione e asciugatura dei prodotti."]],
    checks: [["Fondo preparato", "Valutare l'idoneità delle superfici prima del ciclo."], ["Campione", "Riscontro della scelta colore approvata."], ["Aspetto", "Verifica visiva di copertura e raccordi nelle condizioni concordate."]],
    documents: [["Colore", "Riferimento del campione e codice del prodotto scelto."], ["Ciclo", "Elenco dei materiali impiegati e schede disponibili."], ["Cura delle superfici", "Indicazioni di pulizia e manutenzione pertinenti alla finitura."]],
    faq: [["La tinteggiatura comprende il rifacimento degli intonaci?", "No. Comprende soltanto le preparazioni e le riprese descritte; distacchi estesi richiedono un intervento distinto."], ["Quante mani sono previste?", "Il numero e il tipo di applicazioni devono essere indicati nella specifica del ciclo scelto, prima della conferma."], ["Posso scegliere qualsiasi colore?", "La scelta va valutata con supporto, prodotto e contesto dell'edificio. Eventuali autorizzazioni o accordi condominiali sono da verificare."], ["Il campione a video è sufficiente?", "No. La resa dipende da luce, supporto e tessitura; è opportuno confermare un campione fisico sul posto."], ["La pittura elimina muffe e umidità?", "Non viene promessa la soluzione delle cause. I fenomeni di umidità richiedono una valutazione prima della finitura."], ["La facciata resterà sempre uniforme?", "Esposizione, manutenzione e materiali influenzano l'invecchiamento. Non è promessa un'uniformità permanente."], ["Si lavora anche con pioggia o forte sole?", "Il programma va adattato alle condizioni ammesse dai prodotti; il calendario non è indipendente dal meteo."], ["Sono inclusi infissi e ringhiere?", "Solo se espressamente descritti in voci dedicate. Il loro mascheramento serve a conservarli, non a verniciarli."]],
    prices: [["Preparazioni", "Tinteggiatura: accesso e protezioni delle superfici di esempio", "corpo", 1, 800], ["Preparazioni", "Tinteggiatura: pulizia del fondo indicato", "mq", 140, 4], ["Riprese", "Tinteggiatura: piccole riprese superficiali individuate", "mq", 10, 22], ["Ciclo colore", "Tinteggiatura: applicazione del fondo scelto", "mq", 140, 4.5], ["Ciclo colore", "Tinteggiatura: pittura esterna del ciclo concordato", "mq", 140, 13], ["Consegna", "Tinteggiatura: rimozione protezioni e pulizia prevista", "corpo", 1, 180]],
  },
  interno: {
    title: "Il comfort,\ndal lato interno.", subtitle: "Isolamento delle pareti interne: spessori, umidità e raccordi da valutare insieme.", short: "Pareti e nodi interni. Un sistema definito sul singolo ambiente.", cover: "/module-art/facciate-interno-dettaglio.jpg",
    needs: [["Capire la parete", "Valutare stratigrafia, stato e condizioni di umidità prima di chiudere la superficie."], ["Misurare gli ingombri", "Considerare la riduzione dello spazio e le interferenze con arredi, prese e radiatori."], ["Trattare i raccordi", "Definire le connessioni con solai, pareti adiacenti e aperture."]],
    solution: [["Sistema specificato", "Materiali e spessori scelti dopo le verifiche pertinenti al caso."], ["Nodi disegnati", "Raccordi e attraversamenti indicati nel progetto dell'intervento."], ["Finiture delimitate", "Estensione delle riprese di battiscopa, pittura e impianti esplicitata nel computo."]],
    specs: [["Verifiche preliminari", "Valutare condizioni termoigrometriche e compatibilità del sistema prima della scelta; incarichi tecnici da definire."], ["Stratigrafia", "Indicare isolante, spessori, posa e finitura. Un eventuale controllo del vapore va progettato, non aggiunto automaticamente."], ["Nodi interni", "Descrivere imbotti, attacchi a pavimento e soffitto, divisori e attraversamenti impiantistici."], ["Ripristini", "Quantificare gli spostamenti impiantistici e le riprese di pittura e battiscopa inclusi."]],
    included: [["Pareti individuate", "Isolamento delle sole superfici e dei risvolti descritti."], ["Sistema descritto", "Preparazione, posa e finitura nella stratigrafia concordata."], ["Riprese misurate", "Raccordi e finiture accessorie limitati alle voci del computo."]],
    excluded: [["Cause di umidità", "Risanamento di infiltrazioni e risalita escluso dalla posa dell'isolamento."], ["Impianti e arredi", "Spostamento di prese, radiatori e mobili escluso se senza voce dedicata."], ["Prestazioni presunte", "Nessuna prestazione acustica, classe energetica o percentuale di risparmio è dichiarata da questo esempio."]],
    stages: [["Rilievo interno", "Superfici, umidità, aperture e interferenze."], ["Definizione tecnica", "Scelta della stratigrafia e dei raccordi pertinenti."], ["Preparazione", "Disponibilità del locale, protezioni e fondi."], ["Posa", "Sistema e nodi nelle configurazioni confermate."], ["Finitura e uso", "Riprese incluse, riscontro e indicazioni di gestione dell'ambiente."]],
    protection: [["Ambiente occupato", "Concordare svuotamento, percorsi e limitazioni d'uso della stanza."], ["Polvere e superfici", "Individuare separazioni e protezioni di pavimenti e arredi conservati."], ["Interferenze", "Coordinare le eventuali opere impiantistiche prima della chiusura delle pareti."]],
    checks: [["Prima della chiusura", "Riscontro del supporto e dei dettagli concordati."], ["Continuità del sistema", "Controlli previsti su nodi e attraversamenti nelle parti accessibili."], ["Finitura", "Verifica delle superfici e delle riprese incluse, senza sostituire le valutazioni progettuali."]],
    documents: [["Stratigrafia", "Riepilogo dei materiali e dei dettagli effettivamente concordati."], ["Prodotti", "Schede e istruzioni disponibili dei materiali forniti."], ["Uso del locale", "Indicazioni pertinenti su manutenzione e gestione dell'ambiente; elaborati tecnici secondo l'incarico."]],
    faq: [["L'isolamento interno elimina automaticamente la condensa?", "No. La soluzione va valutata rispetto alla parete e all'uso del locale; non si promette la scomparsa di condensa o muffa."], ["Quanto spazio si perde nella stanza?", "Dipende dallo spessore complessivo del sistema e dai raccordi. Gli ingombri vanno riportati nella proposta tecnica."], ["Serve sempre una barriera al vapore?", "Non è una scelta automatica. L'eventuale strato di controllo del vapore dipende dalla valutazione del sistema e delle condizioni reali."], ["Prese e radiatori vengono spostati?", "Solo se le modifiche sono descritte e quotate. Le interferenze devono essere risolte prima della posa."], ["Si isolano anche soffitto e pavimento?", "Soltanto le superfici e i risvolti esplicitamente compresi; non si estende automaticamente l'intervento a tutto il locale."], ["Si può abitare la stanza durante i lavori?", "Disponibilità del locale e limitazioni temporanee vanno concordate in funzione delle fasi e dei prodotti utilizzati."], ["La pittura finale è compresa?", "Nell'esempio sono previste le superfici trattate. Pareti adiacenti e intero ambiente richiedono quantità specifiche."], ["È garantito un miglioramento acustico o energetico?", "Questo modello non dichiara valori prestazionali. Eventuali obiettivi devono derivare dal progetto e dalle verifiche pertinenti."]],
    prices: [["Preparazioni", "Isolamento interno: protezioni del locale di esempio", "corpo", 1, 250], ["Preparazioni", "Isolamento interno: preparazione delle pareti previste", "mq", 35, 9], ["Sistema", "Isolamento interno: posa del sistema da specificare", "mq", 35, 58], ["Raccordi", "Isolamento interno: raccordi e risvolti individuati", "ml", 18, 20], ["Finiture", "Isolamento interno: rasatura delle superfici previste", "mq", 35, 16], ["Finiture", "Isolamento interno: pittura delle superfici trattate", "mq", 35, 10]],
  },
  riparazioni: {
    title: "Intervenire dove serve.\nCon limiti chiari.", subtitle: "Riparazioni puntuali di facciata: zone identificate, difetti e riprese descritti.", short: "Zone, difetti e raccordi. Un intervento circoscritto e misurabile.", cover: facade,
    needs: [["Localizzare il difetto", "Associare ogni segnalazione a una zona accessibile e identificabile."], ["Capire i limiti", "Distinguere la ripresa superficiale dalla soluzione delle cause ancora da accertare."], ["Concordare i raccordi", "Valutare in anticipo le possibili differenze di colore e tessitura."]],
    solution: [["Elenco delle zone", "Lavorazioni riferite a porzioni numerate, con fotografie reali da aggiungere al caso."], ["Riparazione mirata", "Materiali e preparazioni definiti per il difetto individuato."], ["Estensioni concordate", "Quantità aggiuntive autorizzate dopo il riscontro, senza allargare implicitamente l'offerta."]],
    specs: [["Localizzazione", "Identificare prospetto, quota e dimensioni di ogni riparazione; documentare solo le zone effettivamente osservate."], ["Natura del difetto", "Descrivere distacco, fessura o giunto; valutare se servano indagini prima di scegliere il trattamento."], ["Ciclo locale", "Indicare rimozioni, preparazioni e materiali compatibili con la parte esistente."], ["Raccordo finale", "Definire il bordo della ripresa e la finitura; non promettere l'invisibilità del rappezzo."]],
    included: [["Zone elencate", "Riparazioni limitate alle porzioni identificate e quantificate."], ["Trattamento descritto", "Preparazioni, riprese e finiture del difetto considerato."], ["Accesso previsto", "Allestimento limitato alle condizioni espresse nella specifica voce."]],
    excluded: [["Rifacimento generale", "Tinteggiatura integrale, intonaci estesi e cappotto esclusi."], ["Cause non accertate", "Risoluzione di movimenti, infiltrazioni o difetti nascosti non compresa per presunzione."], ["Altre porzioni", "Zone non elencate e quantità eccedenti da valutare e quotare dopo il riscontro."]],
    stages: [["Segnalazione", "Raccolta delle informazioni e localizzazione delle zone."], ["Riscontro", "Valutazione delle parti accessibili e scelta del trattamento."], ["Preparazione", "Accesso, delimitazioni e rimozioni previste."], ["Riparazione", "Applicazione del ciclo locale concordato."], ["Chiusura", "Riscontro delle riprese, limiti e indicazioni di osservazione."]],
    protection: [["Accesso puntuale", "Scegliere modalità e protezioni adeguate alle zone concordate."], ["Parti adiacenti", "Definire le superfici conservate da proteggere durante la ripresa."], ["Interruzioni", "Concordare l'uso dei passaggi coinvolti per il tempo necessario."]],
    checks: [["Zona e dimensione", "Confrontare la riparazione con la porzione indicata nell'offerta."], ["Fondo e materiale", "Verifiche previste prima della chiusura del ripristino."], ["Raccordi visibili", "Annotare aspetto finale e limiti residui da osservare nel tempo."]],
    documents: [["Scheda delle zone", "Riepilogo di localizzazione, quantità e trattamento concordato."], ["Materiali", "Schede disponibili dei prodotti impiegati."], ["Esiti e limiti", "Annotazioni delle riprese effettuate e degli aspetti esclusi dall'intervento."]],
    faq: [["La riparazione riguarda tutta la facciata?", "No. Riguarda le sole zone identificate nel computo; altre porzioni richiedono una valutazione separata."], ["Il rappezzo sarà invisibile?", "Non è garantito. Materiali, colore ed esposizione possono rendere riconoscibile la ripresa rispetto all'esistente."], ["Una fessura riparata non tornerà più?", "La ricomparsa dipende anche dalla causa e dai movimenti del supporto. Il trattamento superficiale non certifica la loro eliminazione."], ["Bastano fotografie per un prezzo definitivo?", "Le fotografie aiutano a localizzare il difetto ma non sostituiscono i riscontri necessari per quantità, supporto e accessi."], ["È possibile aggiungere altre zone durante i lavori?", "Sì, dopo averne concordato descrizione, quantità, costo e conseguenze sul programma."], ["L'accesso in quota è compreso?", "Solo nelle modalità e nella durata della voce dedicata. Mezzi o allestimenti diversi richiedono una quotazione."], ["Si risolvono le infiltrazioni?", "Solo se la causa è individuata e il relativo trattamento è espressamente compreso; una ripresa locale non garantisce la tenuta generale."], ["Quali documenti riceverò?", "Il riepilogo concordato delle zone e dei materiali disponibili. Relazioni o prove specialistiche sono comprese soltanto con incarico specifico."]],
    prices: [["Preparazioni", "Riparazioni: accesso e protezioni delle zone di esempio", "corpo", 1, 380], ["Preparazioni", "Riparazioni: pulizia e preparazione delle porzioni individuate", "mq", 8, 12], ["Riprese", "Riparazioni: ripristino locale dell'intonaco indicato", "mq", 8, 38], ["Riprese", "Riparazioni: trattamento dei raccordi descritti", "ml", 12, 16], ["Finitura", "Riparazioni: finitura delle porzioni trattate", "mq", 12, 18], ["Consegna", "Riparazioni: rimozione protezioni e pulizia prevista", "corpo", 1, 120]],
  },
} as const satisfies Record<string, FacEditorialContent>;
