/** Editorial readiness only: none of these badges implies quote-flow integration. */
import { CLM_EDITORIAL } from "./clmEditorialContent";
import { ELT_EDITORIAL } from "./eltEditorialContent";
import { PAV_EDITORIAL } from "./pavEditorialContent";
import { PSC_EDITORIAL } from "./pscEditorialContent";
import { FAC_EDITORIAL } from "./facEditorialContent";
const covers = (area: string, models: Record<string, { cover: string }>) => Object.fromEntries(Object.entries(models).map(([id, model]) => [`${area}/${id}`, model.cover]));
export const FULL_MODULE_COVERS: Readonly<Record<string, string>> = {
  ...covers("climatizzazione", CLM_EDITORIAL),
  ...covers("elettrico", ELT_EDITORIAL),
  ...covers("pavimenti", PAV_EDITORIAL),
  ...covers("piscine", PSC_EDITORIAL),
  ...covers("facciate", FAC_EDITORIAL),
  "termoidraulica/caldaia": "/module-art/termoidraulica-caldaia.jpg",
  "termoidraulica/pompa-calore": "/module-art/termoidraulica-pompa-calore-cover.jpg",
  "termoidraulica/radiante": "/module-art/termoidraulica-radiante-cover.jpg",
  "termoidraulica/terminali": "/module-art/termoidraulica-terminali-cover.jpg",
  "termoidraulica/idrico": "/module-art/termoidraulica-idrico-cover.jpg",
  "termoidraulica/manutenzione": "/pdf-stock/termoidraulico/collaudo.jpg",
  "termoidraulica/ibrido": "/module-art/termoidraulica-ibrido-cover-v2.jpg",
  "termoidraulica/acqua-calda": "/module-art/termoidraulica-acqua-calda-cover-v2.jpg",
  "termoidraulica/conto-termico": "/pdf-stock/termoidraulico/pompa-di-calore.jpg",
  "termoidraulica/full-electric": "/pdf-stock/fotovoltaico/villa-tetto-coppi.jpg",
  "termoidraulica/pellet": "/module-art/termoidraulica-caldaia-wide-v3.jpg",
  "termoidraulica/solare-termico": "/pdf-stock/fotovoltaico/villa-tetto-piano.jpg",
  "termoidraulica/trattamento-acqua": "/pdf-stock/termoidraulico/risultato.jpg",
  "bagni/completo": "/module-art/bagni.jpg",
  "bagni/vasca-doccia": "/module-art/bagni-vasca-doccia-cover.jpg",
  "bagni/doccia": "/module-art/bagni-doccia-cover.jpg",
  "bagni/sanitari": "/module-art/bagni-sanitari-cover.jpg",
  "bagni/accessibilita": "/module-art/bagni-accessibilita-cover.jpg",
  "bagni/rinnovo": "/module-art/bagni-rinnovo-cover.jpg",
  "ristrutturazioni/completa": "/module-art/ristrutturazioni.jpg",
  "ristrutturazioni/parziale": "/module-art/ristrutturazioni-parziale-cover.jpg",
  "ristrutturazioni/commerciale": "/module-art/ristrutturazioni-commerciale-cover.jpg",
  "ristrutturazioni/spazi": "/module-art/ristrutturazioni-spazi-cover.jpg",
  "ristrutturazioni/computo": "/pdf-stock/ristrutturazione/cantiere-ordinato.jpg",
  "ristrutturazioni/cucina": "/pdf-stock/ristrutturazione/storia-ciclo-lavori.jpg",
  "ristrutturazioni/sottotetto": "/pdf-stock/tetti/sottotetto.jpg",
  "ristrutturazioni/aperture-portanti": "/pdf-stock/ristrutturazione/tavola-percorso-lavori.jpg",
  "ristrutturazioni/condominio": "/pdf-stock/ristrutturazione/storia-prima-durante-dopo.jpg",
  "ristrutturazioni/montascale": "/pdf-stock/ristrutturazione/tavola-un-unico-progetto.jpg",
  "pareti-soffitti/tinteggiatura-interna": "/pdf-stock/ristrutturazione/risultato.jpg",
  "pareti-soffitti/carta-da-parati": "/pdf-stock/ristrutturazione/storia-consegna-chiavi.jpg",
  "pareti-soffitti/cartongesso": "/pdf-stock/ristrutturazione/cantiere.jpg",
  "pareti-soffitti/controsoffitti": "/pdf-stock/ristrutturazione/tecnica-casa-sezionata.jpg",
  "pareti-soffitti/decorativi": "/pdf-stock/pavimenti/materiali.jpg",
  "pareti-soffitti/umidita": "/pdf-stock/ristrutturazione/controllo-planarita.jpg",
  "pareti-soffitti/acustica": "/pdf-stock/ristrutturazione/tecnica-riscaldamento-pavimento.jpg",
  "pergole/pergola-bioclimatica": "/pdf-stock/pergole/tecnica-lamelle.jpg",
  "pergole/pergola-telo": "/pdf-stock/pergole/installazione.jpg",
  "pergole/tende-sole": "/pdf-stock/pergole/storia-prima-dopo.jpg",
  "pergole/vetrate": "/pdf-stock/pergole/tecnica-acqua.jpg",
  "pergole/carport": "/module-art/pavimenti-esterni-controllo-pendenza-v1.jpg",
  "serramenti/finestre": "/module-art/serramenti.jpg",
  "serramenti/persiane": "/module-art/serramenti-persiane-cover.jpg",
  "serramenti/avvolgibili": "/module-art/serramenti-avvolgibili-cover.jpg",
  "serramenti/zanzariere": "/module-art/serramenti-zanzariere-cover.jpg",
  "serramenti/porte-ingresso": "/module-art/serramenti-porte-ingresso-cover.jpg",
  "serramenti/porte-interne": "/module-art/serramenti-porte-interne-cover.jpg",
  "serramenti/combinato": "/module-art/serramenti-combinato-cover-v3.jpg",
  "serramenti/portoni-garage": "/pdf-stock/serramenti/installazione.jpg",
  "serramenti/grate": "/pdf-stock/serramenti/risultato.jpg",
  "tetti/ripasso": "/module-art/tetti.jpg",
  "tetti/rifacimento": "/module-art/tetti.jpg",
  "tetti/riparazioni": "/module-art/tetti-riparazioni-cover.jpg",
  "tetti/isolamento": "/pdf-stock/tetti/isolamento.jpg",
  "tetti/impermeabilizzazione": "/module-art/tetti-impermeabilizzazione-cover.jpg",
  "tetti/lattoneria": "/module-art/tetti-lattoneria-cover.jpg",
  "tetti/amianto": "/pdf-stock/tetti/protezione.jpg",
  "tetti/linea-vita": "/pdf-stock/tetti/squadra.jpg",
  "tetti/lucernari": "/pdf-stock/tetti/installazione.jpg",
  "fotovoltaico/accumulo": "/module-art/fotovoltaico-accumulo-cover.jpg",
  "fotovoltaico/nuovo": "/pdf-stock/fotovoltaico/villa-tetto-coppi.jpg",
  "fotovoltaico/ampliamento": "/pdf-stock/fotovoltaico/dettaglio-celle.jpg",
  "fotovoltaico/componenti": "/pdf-stock/fotovoltaico/inverter-monofase.jpg",
  "fotovoltaico/manutenzione": "/pdf-stock/fotovoltaico/controllo-termografico.jpg",
};
export const fullModuleCover = (area: string, module: string): string | null => FULL_MODULE_COVERS[`${area}/${module}`] ?? null;
