/** Editorial content, not engineering specifications or performance promises. */
export type FvEditorialId = "nuovo" | "ampliamento" | "componenti" | "manutenzione";
type Pair = readonly [string, string];
export interface FvEditorialContent {
  title: string; hero: string; subtitle: string; cover: string; detail: string;
  scope: string; checks: Pair[]; phases: Pair[]; faq: Pair[];
}
const img = (name: string) => `/pdf-stock/fotovoltaico/${name}.jpg`;
export const FV_EDITORIAL: Record<FvEditorialId, FvEditorialContent> = {
  nuovo: {
    title: "Nuovo impianto fotovoltaico", hero: "La tua casa.\nUna nuova energia.",
    subtitle: "Un progetto fotovoltaico costruito sui tuoi consumi, sul tuo tetto e sulle tue priorità.",
    cover: img("villa-tetto-coppi"), detail: img("dettaglio-celle"),
    scope: "La fornitura comprende soltanto pannelli, inverter, strutture, protezioni e lavorazioni elencate. Accumulo, backup, opere sul tetto e adeguamenti elettrici richiedono voci esplicite. Produzione, autoconsumo e risparmio sono stime da accompagnare con dati, ipotesi e fonte del calcolo.",
    checks: [["Il tetto disponibile", "Superfici utilizzabili, orientamento, ombre, accessi e condizioni della copertura guidano il layout dei moduli."], ["Il tuo profilo di consumo", "Le bollette e gli orari di utilizzo aiutano a confrontare produzione disponibile e fabbisogno, senza presumere autoconsumo totale."], ["Componenti coordinati", "Potenza dei moduli, inverter, strutture e protezioni devono appartenere a una configurazione definita nel progetto."], ["Scelte aggiuntive", "Batteria, gestione dei carichi e backup vengono descritti e quotati separatamente quando previsti."]],
    phases: [["Sopralluogo e dati", "Raccogliamo consumi e informazioni sulla copertura e sull'impianto elettrico."], ["Progetto e conferma", "Confrontiamo layout, componenti, stime documentate, servizi inclusi e condizioni."], ["Installazione programmata", "Concordiamo accessi, protezioni, montaggio e collegamenti previsti."], ["Verifiche e consegna", "Definiamo controlli, pratiche applicabili, monitoraggio e documenti della fornitura."]],
    faq: [["La batteria è sempre compresa?", "No. Capacità, modello e lavorazioni dell'accumulo devono risultare tra le voci dell'offerta."], ["Quanta energia produrrà?", "La stima richiede località, orientamento, inclinazione, ombre e dati dei componenti. Va accompagnata da ipotesi e fonte, non ricavata dalla fotografia."], ["Il tetto deve essere rifatto?", "Lo stato della copertura va verificato. Le opere edili eventualmente necessarie non sono implicitamente comprese nel fotovoltaico."], ["Posso usare energia durante un blackout?", "Solo con una configurazione di emergenza espressamente prevista e verificata. Non è una funzione automatica di ogni impianto."], ["Quando sarà attivo?", "Il programma distingue disponibilità dei materiali, installazione ed eventuali passaggi con soggetti esterni. Le date si concordano sul caso concreto."], ["Quali pratiche sono incluse?", "La proposta deve elencare incarichi, documenti e servizi compresi, distinguendoli da attività e costi di terzi."], ["Il risparmio è garantito?", "Una simulazione dipende da consumo, produzione, tariffe e uso. Le ipotesi devono essere leggibili e non equivalgono a una garanzia di risultato."], ["Come confermo i prodotti?", "Confronta marca, modello, quantità, schede e accessori. Le immagini del modello sono illustrative, non identificano la fornitura definitiva."]],
  },
  ampliamento: {
    title: "Ampliamento fotovoltaico", hero: "Più possibilità.\nDal tuo impianto attuale.",
    subtitle: "Nuove componenti, compatibilità e lavorazioni distinte da ciò che possiedi già.",
    cover: img("dettaglio-celle"), detail: img("villa-tetto-coppi"),
    scope: "L'offerta riguarda la sola estensione descritta. Potenza esistente, potenza aggiunta e configurazione finale devono essere distinte. Il riuso di inverter, cablaggi e strutture è subordinato a verifica. Non sono inclusi automaticamente rinnovo dell'intero impianto, accumulo o ripristini della copertura.",
    checks: [["Punto di partenza", "Identifichiamo moduli, inverter, schema e documentazione dell'impianto esistente."], ["Spazio per crescere", "Valutiamo superfici libere, ombre, orientamenti e accessi della sola zona interessata."], ["Interfaccia vecchio e nuovo", "Moduli, stringhe, inverter e protezioni vanno verificati insieme: non basta aggiungere pannelli."], ["Beneficio aggiuntivo", "L'eventuale simulazione deve confrontare prima e dopo, separando il contributo dell'ampliamento dalla produzione già disponibile."]],
    phases: [["Rilievo dell'esistente", "Documenti e componenti installati, spazi disponibili e obiettivi dell'estensione."], ["Configurazione dell'ampliamento", "Potenza aggiunta, componenti riutilizzati o sostituiti e opere accessorie."], ["Integrazione programmata", "Accessi, lavorazioni, interruzioni previste e collegamenti secondo progetto."], ["Verifica della configurazione finale", "Riscontri sulle nuove parti, aggiornamenti applicabili e consegna dei riferimenti."]],
    faq: [["Posso conservare il mio inverter?", "Dipende da caratteristiche, capacità disponibile e configurazione. La verifica precede l'ordine."], ["I nuovi moduli devono essere uguali?", "La compatibilità va valutata sul progetto; non si presume dal solo aspetto o dalla potenza nominale."], ["Il prezzo riguarda tutto l'impianto?", "No, riguarda le componenti e le opere dell'estensione elencate. Le parti esistenti vanno identificate separatamente."], ["La produzione aumenterà in proporzione ai pannelli?", "Non necessariamente. Ombre, orientamento, configurazione e limiti dei componenti incidono sul risultato."], ["Sono necessarie pratiche aggiuntive?", "Va verificato sul caso concreto. L'offerta deve chiarire attività comprese e responsabilità."], ["È compresa una batteria?", "Solo se compare nella fornitura con modello, capacità, accessori e lavorazioni."], ["L'impianto dovrà fermarsi?", "Le interruzioni necessarie devono essere programmate e comunicate prima delle lavorazioni."], ["La garanzia copre anche le parti vecchie?", "Non automaticamente: condizioni e copertura si riferiscono ai prodotti e alle opere effettivamente forniti."]],
  },
  componenti: {
    title: "Sostituzione componenti", hero: "Il componente giusto.\nNel sistema che hai già.",
    subtitle: "Una sostituzione mirata, con prodotti identificati e compatibilità verificata.",
    cover: img("inverter-monofase"), detail: img("componenti-elettrici"),
    scope: "La proposta riguarda soltanto i componenti identificati e le lavorazioni indicate. Diagnosi ulteriori, guasti ad altre parti, adeguamenti, ponteggi e ripristini vanno concordati se non compresi. La sostituzione non rinnova automaticamente l'intero impianto né tutte le sue garanzie.",
    checks: [["Componente da sostituire", "Marca, modello, funzione e motivo dell'intervento devono essere riconoscibili nel riepilogo."], ["Prodotto proposto", "Confrontiamo caratteristiche e interfacce con le schede del nuovo componente, senza presumere equivalenza dal solo ingombro."], ["Collegamenti e accessori", "Adattatori, cablaggi, protezioni e configurazioni necessari vanno esplicitati nella fornitura."], ["Riscontro finale", "Le verifiche riguardano il componente sostituito e la sua interazione prevista con l'impianto."]],
    phases: [["Identificazione e diagnosi", "Raccogliamo segnalazione, dati del prodotto e riscontri disponibili."], ["Scelta del ricambio", "Confermiamo compatibilità, disponibilità, prezzo e limiti dell'intervento."], ["Sostituzione", "Programmiamo accesso, interruzione e lavorazioni concordate."], ["Prova e consegna", "Documentiamo componente nuovo, configurazione e riferimenti per l'assistenza."]],
    faq: [["Il ricambio sarà identico?", "La disponibilità può richiedere un modello diverso. La compatibilità va confermata prima dell'installazione."], ["La diagnosi è compresa?", "Solo nelle attività indicate, con eventuali limiti di tempo o approfondimenti da concordare."], ["Sono compresi tutti i guasti?", "No. Difetti diversi da quelli quotati richiedono una valutazione e un accordo separati."], ["Aumenterà la produzione?", "La sostituzione non implica automaticamente un incremento. Prestazioni e obiettivi devono essere documentati."], ["Chi gestisce il componente rimosso?", "Ritiro e gestione vanno indicati tra i servizi compresi o esclusi."], ["Cambierà l'app di monitoraggio?", "Può dipendere dal ricambio. Accessi, servizi e compatibilità vanno verificati e comunicati."], ["Quanto dura il fermo?", "Dipende da disponibilità e intervento. Il periodo previsto viene concordato, non desunto dal modello."], ["Quale garanzia riceverò?", "Quella applicabile al componente e alle lavorazioni fornite, secondo i documenti e le condizioni concordate."]],
  },
  manutenzione: {
    title: "Manutenzione fotovoltaico", hero: "Conoscere lo stato.\nDecidere con chiarezza.",
    subtitle: "Controlli concordati, evidenze leggibili e interventi aggiuntivi solo se autorizzati.",
    cover: img("controllo-termografico"), detail: img("dettaglio-celle"),
    scope: "Sono comprese solo le attività e le frequenze elencate. Pulizia, termografia, misure, ricambi e riparazioni sono prestazioni distinte, non incluse dalla sola immagine. Il servizio non garantisce assenza di guasti futuri né un incremento fisso di produzione.",
    checks: [["Perimetro del servizio", "Numero e posizione dei moduli, inverter e parti accessibili definiscono cosa verrà controllato."], ["Attività concordate", "Controllo visivo, pulizia e prove strumentali vanno descritti singolarmente con gli eventuali limiti."], ["Condizioni e accessi", "Accessibilità, meteo e condizioni del sito possono modificare il programma o richiedere mezzi dedicati."], ["Esiti e priorità", "Le anomalie rilevate si distinguono dalle parti non verificabili. Gli interventi proposti richiedono approvazione."]],
    phases: [["Raccolta informazioni", "Impianto, segnalazioni, precedenti interventi e disponibilità di accesso."], ["Programma del servizio", "Attività, frequenza, condizioni di esecuzione e prezzo concordati."], ["Controlli previsti", "Esecuzione delle sole verifiche e attività comprese, con i riscontri disponibili."], ["Rapporto e prossime azioni", "Esiti, limiti del controllo, priorità ed eventuali proposte aggiuntive da autorizzare."]],
    faq: [["La pulizia è sempre inclusa?", "No, deve comparire tra le attività con superfici e modalità concordate."], ["La termografia è compresa?", "Solo se espressamente prevista. Le foto del modello sono illustrative e non ampliano il servizio."], ["Sono inclusi i ricambi?", "Soltanto quelli elencati. Ricambi e riparazioni emersi dai controlli vengono proposti separatamente."], ["Quanto spesso serve intervenire?", "La frequenza dipende da sito, componenti, istruzioni dei produttori e condizioni d'uso."], ["Avrò più produzione?", "Non è possibile promettere un aumento fisso dal solo servizio. Eventuali confronti richiedono dati comparabili."], ["Cosa succede se piove?", "Le attività dipendenti dal meteo possono essere riprogrammate secondo le condizioni concordate."], ["Riceverò un rapporto?", "Se previsto, il rapporto descrive attività svolte, riscontri, parti non controllate e azioni suggerite."], ["Il servizio copre i guasti futuri?", "No. Eventuali assistenza continuativa, reperibilità e coperture devono essere definite in un accordo specifico."]],
  },
};
