import type { TetEditorialPair } from "./fullTettiFactory";
import { FAQ_CONTO_TERMICO } from "@/lib/contoTermico/testi";
import { FAQ_FULL_ELECTRIC } from "@/lib/fullElectric/testi";

interface IdrEditorial {
  hero: string; subtitle: string; cover: string; detail: string; context: string; scope: string;
  specs: TetEditorialPair[]; stages: TetEditorialPair[]; faq: TetEditorialPair[];
  rows: [string, string, number][];
  /** «Perché sceglierci» e garanzie scritti per l'intervento; senza, si compongono da specs e stages. */
  usp?: TetEditorialPair[];
  garanzie?: TetEditorialPair[];
}

/** One editorial brief per intervention, not a renamed whole-house installation. */
export const IDR_REMAINING_EDITORIAL = {
  caldaia: {
    hero: "Un nuovo generatore.\nUn intervento chiaro.",
    subtitle: "La caldaia giusta per l'impianto esistente, con collegamenti, rimozioni e avviamento definiti prima dei lavori.",
    cover: "/module-art/termoidraulica-caldaia.jpg", detail: "/module-art/termoidraulica-caldaia.jpg", context: "/pdf-stock/comune/consegna-documenti.jpg",
    scope: "La proposta riguarda la sostituzione della caldaia e le attività elencate. Canna fumaria, rete gas, scarichi, alimentazione, distribuzione e terminali non vengono rinnovati automaticamente. Adeguamenti e ripristini devono essere indicati separatamente.",
    specs: [["Impianto da conoscere", "Identificare generatore esistente, utilizzo sanitario, terminali e caratteristiche dei collegamenti."], ["Apparecchio proposto", "Marca, modello, potenza e dotazioni risultano dalla scheda selezionata, non dall'immagine illustrativa."], ["Collegamenti compatibili", "Verificare evacuazione fumi, scarico condensa, gas, acqua e alimentazione rispetto alla configurazione reale."], ["Regolazione e accesso", "Definire comandi, posizione, accessibilità per assistenza e opere necessarie prima dell'ordine."]],
    stages: [["Rilievo dell'esistente", "Raccogliamo dati del generatore e dei collegamenti accessibili."], ["Scelta e perimetro", "Confermiamo apparecchio, adattamenti, rimozioni ed esclusioni."], ["Sostituzione programmata", "Concordiamo interruzione delle utenze e attività di installazione."], ["Avviamento e istruzioni", "Eseguiamo le verifiche previste e spieghiamo uso, documenti e assistenza."]],
    faq: [["Posso mantenere i radiatori?", "Si valuta la compatibilità con l'impianto e con il generatore scelto. La sostituzione dei terminali non è implicita."], ["La canna fumaria è compresa?", "Solo le opere descritte. Configurazione, compatibilità e accessi devono essere verificati."], ["Chi rimuove la vecchia caldaia?", "Smontaggio, trasporto e gestione del rimosso devono comparire nella proposta."], ["Quanto resterò senza riscaldamento?", "La finestra di interruzione si concorda dopo il sopralluogo; non è fissata dal modello."], ["È incluso il termostato?", "Solo se il comando è elencato con modello e modalità di collegamento."], ["Risparmierò una percentuale precisa?", "Non senza un confronto documentato su impianto, consumi e utilizzo. Nessuna percentuale è automatica."], ["Sono previsti adeguamenti?", "Quelli rilevati e quotati. Eventuali condizioni non accessibili richiedono una proposta integrativa approvata."], ["Sono compresi i controlli successivi?", "Le attività alla consegna e i servizi periodici devono essere distinti; non si presume un contratto di manutenzione."]],
    rows: [["Generatore", "Caldaia e dotazioni della configurazione dimostrativa", 1800], ["Sostituzione", "Smontaggio previsto e installazione sui collegamenti indicati", 620], ["Avviamento", "Verifiche previste e istruzioni della configurazione installata", 180]],
  },
  "pompa-calore": {
    hero: "Il comfort cambia.\nLa scelta parte dalla casa.",
    subtitle: "Pompa di calore, terminali e regolazione: un progetto commisurato all'edificio e alle tue abitudini.",
    cover: "/module-art/termoidraulica-pompa-calore-cover.jpg", detail: "/module-art/termoidraulica.jpg", context: "/pdf-stock/comune/consegna-documenti.jpg",
    scope: "Sono compresi il generatore e le opere elencate. Accumuli, produzione sanitaria, raffrescamento, rete elettrica, terminali e opere murarie richiedono voci esplicite. Non si presume la completa elettrificazione dell'edificio né un risultato energetico garantito.",
    specs: [["Fabbisogno e terminali", "Valutare edificio, temperature richieste, distribuzione e corpi scaldanti prima di selezionare il sistema."], ["Configurazione", "Identificare unità, componenti interni, accumuli e funzioni effettivamente incluse."], ["Spazi e utenze", "Verificare posizione esterna, accessi, scarichi e disponibilità elettrica rispetto al progetto."], ["Comandi e utilizzo", "Concordare zone, regolazione e modalità d'uso; riscaldamento, sanitario e raffrescamento sono funzioni distinte."]],
    stages: [["Conoscere l'edificio", "Raccogliamo caratteristiche della casa, impianto e necessità d'uso."], ["Definire la soluzione", "Dimensioniamo la configurazione e delimitiamo opere e predisposizioni."], ["Installare e collegare", "Coordiniamo apparecchi, collegamenti e interruzioni concordate."], ["Regolare e consegnare", "Verifichiamo le funzioni previste e spieghiamo regolazione e documenti."]],
    faq: [["Funziona con i miei radiatori?", "Serve una verifica di fabbisogni, dimensioni e temperature. La compatibilità non dipende solo dal nome del generatore."], ["Produce acqua calda sanitaria?", "Solo se la funzione, l'accumulo e i collegamenti sono inclusi nella configurazione."], ["Può anche raffrescare?", "Solo con componenti, terminali e gestione previsti dal progetto; non è una funzione automaticamente utilizzabile."], ["Devo cambiare il contatore?", "La potenza disponibile e le caratteristiche dell'alimentazione si verificano sul posto."], ["Dove viene collocata l'unità esterna?", "Posizione, accessibilità e interferenze si definiscono rispetto al prodotto e al contesto reale."], ["La vecchia caldaia viene rimossa?", "La proposta deve specificare cosa viene dismesso, conservato o integrato."], ["Quanto risparmierò?", "Occorre una simulazione con ipotesi dichiarate e consumi reali. Il modello non garantisce risparmi."], ["Sono comprese opere e finiture?", "Soltanto quelle elencate: basamenti, passaggi, rete elettrica e ripristini non sono impliciti."]],
    rows: [["Sistema", "Pompa di calore e componenti della configurazione dimostrativa", 6200], ["Installazione", "Posizionamento e collegamenti previsti nell'esempio", 1700], ["Consegna", "Regolazione e verifica delle funzioni indicate", 380]],
  },
  radiante: {
    hero: "Il comfort,\nsotto ogni passo.",
    subtitle: "Circuiti, quote e regolazione pensati insieme: il riscaldamento a pavimento incontra il progetto degli ambienti.",
    cover: "/module-art/termoidraulica-radiante-cover.jpg", detail: "/pdf-stock/termoidraulico/collaudo.jpg", context: "/pdf-stock/comune/consegna-documenti.jpg",
    scope: "L'offerta riguarda il sistema radiante e le opere descritte. Demolizioni, sottofondi, massetti, pavimenti, porte e generatore sono lavorazioni distinte. Quote disponibili, supporti e tempi delle fasi devono essere confermati prima della posa.",
    specs: [["Superfici e quote", "Misurare aree effettive, spessori disponibili, soglie e raccordi con i locali conservati."], ["Circuiti e materiali", "Definire pannelli, tubazioni, collettori e circuito per ambiente sulla base del progetto."], ["Zone e regolazione", "Identificare comandi e gestione delle zone compatibili con il generatore esistente o proposto."], ["Opere coordinate", "Separare posa impiantistica, massetti, finiture e attività previste prima della messa in servizio."]],
    stages: [["Rilievo delle quote", "Verifichiamo superfici, supporti e interferenze con le finiture."], ["Progetto dei circuiti", "Concordiamo zone, componenti e confini tra lavorazioni."], ["Posa e riscontri", "Installiamo le parti previste e registriamo i controlli concordati prima della copertura."], ["Avvio coordinato", "Programmiamo le fasi successive e la consegna secondo sistema, materiali e condizioni reali."]],
    faq: [["Quanto si alzerà il pavimento?", "Lo spessore dipende dal sistema e dalla stratigrafia: va verificato con quote, soglie e finiture."], ["Il nuovo pavimento è incluso?", "Solo se compare nel computo. Impianto radiante e rivestimento finale sono forniture distinte."], ["Posso mantenere la caldaia?", "Occorre verificarne compatibilità, temperature e regolazione con il progetto del radiante."], ["Quanto tempo serve prima dell'uso?", "Il programma dipende da materiali, opere e procedure previste. Non è garantito un numero fisso di giorni."], ["Posso controllare ogni stanza?", "Le zone indipendenti e i relativi comandi devono essere elencati nella configurazione."], ["Sono comprese le demolizioni?", "Solo le rimozioni, i trasporti e i ripristini descritti nell'offerta."], ["Può raffrescare?", "Serve una configurazione specifica anche per regolazione e gestione dell'umidità; non è implicita."], ["Avrò le foto prima della copertura?", "La documentazione fotografica e il suo perimetro si concordano. Le immagini di questo modello sono illustrative."]],
    rows: [["Sistema radiante", "Pannelli e circuiti delle aree dimostrative indicate", 3600], ["Distribuzione", "Collettore e regolazione delle zone descritte", 850], ["Verifiche", "Riscontri previsti prima della copertura e consegna delle informazioni", 320]],
  },
  terminali: {
    hero: "Il calore,\nnel posto giusto.",
    subtitle: "Radiatori e terminali selezionati per ambiente: dimensioni, resa, collegamenti e finiture messi in chiaro.",
    cover: "/module-art/termoidraulica-terminali-cover.jpg", detail: "/module-art/termoidraulica-terminali-detail.jpg", context: "/pdf-stock/comune/consegna-documenti.jpg",
    scope: "L'intervento riguarda i corpi scaldanti e i collegamenti elencati. Non comporta il rinnovo del generatore o dell'intera distribuzione. Spostamenti, nuove tracce, alimentazioni elettriche e ripristini richiedono voci dedicate.",
    specs: [["Un elenco per ambiente", "Indicare stanza, quantità, dimensioni e posizione di ciascun terminale."], ["Resa alla temperatura prevista", "Confrontare dati del prodotto, fabbisogno e condizioni di funzionamento effettive dell'impianto."], ["Attacchi e supporti", "Verificare interassi, tubazioni, fissaggi e accessibilità delle valvole."], ["Comandi e finitura", "Specificare materiale, colore, valvole e regolazione; eventuali terminali ventilati richiedono predisposizioni dedicate."]],
    stages: [["Rilievo stanza per stanza", "Identifichiamo apparecchi esistenti, attacchi e posizioni richieste."], ["Selezione dei terminali", "Confermiamo prodotti, finiture e accessori inclusi."], ["Sostituzione o aggiunta", "Programmiamo svuotamenti, montaggi e collegamenti descritti."], ["Verifica e regolazione", "Controlliamo le parti interessate e spieghiamo le funzioni dei comandi previsti."]],
    faq: [["Posso cambiare dimensione?", "Va verificata la resa richiesta insieme a spazi, attacchi e compatibilità dell'impianto."], ["Posso spostare un radiatore?", "Lo spostamento richiede percorsi e opere espliciti; non coincide con una sostituzione sugli stessi attacchi."], ["Sono incluse le valvole?", "Soltanto quelle elencate, distinguendo valvole, detentori e teste di regolazione."], ["Cambierà anche la caldaia?", "No, salvo una fornitura specifica nella proposta."], ["Devo ritinteggiare la parete?", "Ripristini e tinteggiatura devono essere quotati o indicati come esclusi."], ["Si può lavorare con il riscaldamento acceso?", "Le interruzioni necessarie e lo svuotamento si concordano rispetto all'impianto reale."], ["La foto è il prodotto scelto?", "No: è illustrativa. Marca, modello e finitura risultano dalla distinta effettiva."], ["I vecchi terminali vengono portati via?", "Rimozione, trasporto e gestione del materiale devono comparire tra le lavorazioni incluse."]],
    rows: [["Terminali", "Corpi scaldanti delle posizioni dimostrative indicate", 1250], ["Accessori", "Valvole e accessori dei soli terminali elencati", 220], ["Installazione", "Rimozioni previste, montaggio e verifica dei collegamenti interessati", 580]],
  },
  idrico: {
    hero: "Ogni punto acqua.\nUn percorso definito.",
    subtitle: "Adduzione, distribuzione e scarichi descritti per ambiente, con le opere accessorie chiaramente separate.",
    cover: "/module-art/termoidraulica-idrico-cover.jpg", detail: "/module-art/termoidraulica-idrico-detail.jpg", context: "/module-art/termoidraulica-acqua-calda-comfort.jpg",
    scope: "Sono comprese le reti, i punti e le lavorazioni elencati. Sanitari, rubinetteria, produzione di acqua calda, colonne comuni, demolizioni e finiture non sono implicitamente inclusi. Il confine tra rete nuova e parti conservate deve essere indicato.",
    specs: [["Punti serviti", "Elencare utenze e ambienti, distinguendo acqua fredda, calda ed eventuali predisposizioni."], ["Percorsi e distribuzione", "Definire origine delle reti, materiali, collettori, intercettazioni e tratti conservati."], ["Scarichi", "Identificare tratti e raccordi interessati, quote e collegamenti alle parti esistenti."], ["Opere e verifiche", "Concordare accessi, tracce, ripristini e riscontri sulle sole parti oggetto dell'intervento."]],
    stages: [["Mappa delle utenze", "Raccogliamo posizioni, utilizzi e informazioni sulle reti accessibili."], ["Percorsi e perimetro", "Definiamo reti nuove, collegamenti e confini delle opere."], ["Posa coordinata", "Realizziamo i tratti descritti coordinandoli con le altre lavorazioni."], ["Riscontri e documenti", "Eseguiamo le verifiche previste e consegniamo le informazioni pertinenti alle opere realizzate."]],
    faq: [["Sono compresi sanitari e rubinetti?", "Solo se elencati separatamente. La rete idrica non equivale alla fornitura completa del bagno."], ["Viene sostituito tutto l'impianto?", "Solo il perimetro descritto; tratti conservati e collegamenti devono essere riconoscibili."], ["Sono comprese le colonne condominiali?", "Non automaticamente. Responsabilità, accessi e perimetro vanno definiti prima dei lavori."], ["Chi chiude le tracce?", "Demolizioni, chiusure, impermeabilizzazioni e finiture devono risultare nelle voci incluse o escluse."], ["Posso mantenere i punti esistenti?", "La compatibilità dei collegamenti e lo stato delle parti accessibili devono essere verificati."], ["Sono previste interruzioni dell'acqua?", "Sì, se necessarie alle attività concordate; durata e coordinamento si definiscono prima dell'intervento."], ["Riceverò una mappa dei percorsi?", "Elaborati e documentazione fotografica devono essere previsti e riferiti alle opere effettive."], ["L'offerta comprende l'acqua calda?", "La rete di acqua calda e il suo generatore sono elementi distinti: la produzione non è inclusa senza voce specifica."]],
    rows: [["Adduzione", "Distribuzione e punti acqua delle aree dimostrative indicate", 2100], ["Scarichi", "Tratti di scarico e raccordi descritti nell'esempio", 900], ["Verifiche", "Riscontri sulle parti realizzate e documenti pertinenti", 300]],
  },
  manutenzione: {
    hero: "Capire il problema.\nDefinire l'intervento.",
    subtitle: "Diagnosi, attività e ricambi separati: una proposta leggibile per la cura dell'impianto esistente.",
    cover: "/pdf-stock/termoidraulico/collaudo.jpg", detail: "/module-art/termoidraulica.jpg", context: "/module-art/termoidraulica-caldaia.jpg",
    scope: "Il servizio copre solo apparecchi, attività e limiti descritti. Un'uscita diagnostica non garantisce la risoluzione di ogni guasto. Ricambi, attività ulteriori e parti non accessibili richiedono una proposta e un'autorizzazione specifiche.",
    specs: [["Richiesta e apparecchio", "Identificare sintomo o servizio, componente interessato e dati disponibili del prodotto."], ["Attività incluse", "Distinguere uscita, diagnosi, pulizia, regolazione e riparazione effettivamente previste."], ["Tempi e ricambi", "Specificare ore o limiti del servizio; modello, disponibilità e costo dei ricambi non sono presunti."], ["Esito e limiti", "Registrare attività svolte, riscontri, parti non verificate e proposte residue."]],
    stages: [["Raccolta delle informazioni", "Raccogliamo sintomi, dati dell'apparecchio e condizioni di accesso."], ["Verifica sul posto", "Svolgiamo le sole attività diagnostiche o manutentive concordate."], ["Proposta di intervento", "Se servono ulteriori opere o ricambi, li descriviamo e richiediamo conferma prima di procedere."], ["Riepilogo del servizio", "Consegniamo esito, limiti e indicazioni riferite alle attività effettivamente svolte."]],
    faq: [["L'uscita garantisce la riparazione?", "No. Una diagnosi può richiedere attività o ricambi ulteriori, da approvare separatamente."], ["I ricambi sono compresi?", "Solo quelli identificati nel computo. Nessun ricambio generico è incluso automaticamente."], ["Il prezzo copre tutte le ore?", "Il servizio deve specificare attività, tempo incluso e modalità per eventuali estensioni."], ["Posso richiedere un servizio periodico?", "Periodicità, attività e durata vanno definite in una proposta dedicata; non sono implicite."], ["Viene verificato l'intero impianto?", "Solo il perimetro concordato e accessibile. Le parti non controllate devono essere indicate."], ["Cosa succede se il guasto non è riproducibile?", "Si registrano condizioni osservate e limiti della diagnosi, concordando gli eventuali passi successivi."], ["La foto mostra il lavoro che verrà eseguito?", "È un'illustrazione. L'attività effettiva è quella descritta nella proposta."], ["È prevista reperibilità urgente?", "Solo se espressamente concordata con condizioni e disponibilità; non viene promessa dal modello."]],
    rows: [["Uscita", "Accesso programmato sull'apparecchio dimostrativo indicato", 60], ["Servizio", "Attività diagnostiche o manutentive descritte, senza ricambi", 120], ["Riepilogo", "Registrazione dei riscontri e delle attività residue", 20]],
  },
  // Il Conto Termico 3.0 (regole in src/lib/contoTermico): il PDF è
  // ContoTermicoPDF, che legge da qui copertina, domande e passaggi.
  "conto-termico": {
    hero: "Il calore di casa.\nCon l'aiuto dello Stato.",
    subtitle: "Pompa di calore o generatore rinnovabile al posto del vecchio impianto, con il contributo del GSE e il conto di quanto resta a te.",
    cover: "/pdf-stock/termoidraulico/pompa-di-calore.jpg", detail: "/module-art/termoidraulica.jpg", context: "/pdf-stock/comune/consegna-documenti.jpg",
    scope: "La proposta riguarda il generatore, i collegamenti e le attività elencate. Il contributo del Conto Termico è stimato: l'importo definitivo lo stabilisce il GSE. Distribuzione, terminali, opere murarie e adeguamenti elettrici non sono compresi se non elencati.",
    specs: [["Impianto da sostituire", "Il Conto Termico chiede un impianto di riscaldamento funzionante che viene sostituito: si identifica prima dei lavori."], ["Generatore proposto", "Potenza ed efficienza stagionale (SCOP) risultano dalla scheda tecnica del modello: sono i dati con cui il GSE calcola il contributo."], ["Contributo e modalità", "Si concorda se il contributo arriva dal GSE al cliente o se l'impresa lo sconta in fattura con il mandato all'incasso."], ["Documenti per il GSE", "Foto prima e dopo, fatture, bonifici, schede e certificato di smaltimento si raccolgono durante i lavori."]],
    stages: [["Sopralluogo e requisiti", "Verifichiamo l'impianto da sostituire, la casa e i requisiti del nuovo generatore."], ["Firma e installazione", "Confermi la proposta; smontiamo e smaltiamo il vecchio generatore e installiamo il nuovo."], ["Domanda al GSE", "Entro 90 giorni dalla fine dei lavori, con foto, fatture e documenti tecnici."], ["Il contributo", "Accettata la domanda, il GSE paga il contributo, oppure lo sconta l'impresa in fattura se hai scelto così."]],
    // Le stesse domande del documento: una sola fonte, src/lib/contoTermico/testi.ts.
    faq: FAQ_CONTO_TERMICO.map(({ domanda, risposta }) => [domanda, risposta] as TetEditorialPair),
    rows: [["Sistema", "Pompa di calore aria-acqua con modulo idronico e bollitore della configurazione dimostrativa", 9800], ["Installazione", "Smontaggio e smaltimento del vecchio generatore, collegamenti e messa in funzione", 2300], ["Pratica GSE", "Raccolta dei documenti e invio della domanda al GSE", 400]],
    // Composti da specs e stages, qui uscivano frasi fuori posto («Compatibilità
    // prima dell'ordine» spiegata col modo di ricevere il contributo).
    usp: [["Il contributo, messo in chiaro", "Nel preventivo trovi il contributo stimato, quanto resta a te e quando arriva: i numeri sono gli stessi in ogni pagina."], ["Un generatore scelto sui requisiti", "Potenza ed efficienza stagionale (SCOP) sono i dati con cui il GSE calcola il contributo: li verifichiamo sulla scheda tecnica prima dell'ordine."], ["I documenti, raccolti durante i lavori", "Foto prima e dopo, fatture, schede e certificato di smaltimento: quello che serve alla domanda al GSE non si ricostruisce dopo."]],
    garanzie: [["Garanzia del produttore", "Sul generatore vale la garanzia del produttore, alle condizioni della sua documentazione."], ["Impianto a regola d'arte", "A fine lavori rilasciamo la dichiarazione di conformità prevista per le opere eseguite."], ["Documenti per il GSE", "Foto, fatture, schede tecniche e certificato di smaltimento restano a te, pronti per la domanda e per eventuali controlli."], ["Assistenza definita", "Contatti e documenti restano a te; manutenzione e servizi aggiuntivi sono quelli concordati."]],
  },
  "full-electric": {
    hero: "La casa senza gas.\nTutta elettrica, dal tuo tetto.",
    subtitle: "Pompa di calore, induzione, fotovoltaico e batteria: un solo progetto e una sola bolletta.",
    cover: "/pdf-stock/fotovoltaico/villa-tetto-coppi.jpg", detail: "/pdf-stock/fotovoltaico/tecnica-percorso-energia.jpg", context: "/pdf-stock/fotovoltaico/sopralluogo.jpg",
    scope: "La proposta riguarda i componenti, i collegamenti e le attività elencate. Produzione, consumi e risparmi sono stime; gli incentivi dipendono dai requisiti e dalle regole in vigore. Opere murarie, adeguamenti della rete e aumenti di potenza non sono compresi se non elencati.",
    specs: [["Consumi e bollette di oggi", "Gas e luce di un anno: da qui si misura quanto cambia con la casa tutta elettrica."], ["Il sistema proposto", "Potenza del fotovoltaico, capacità della batteria e pompa di calore risultano dalle schede dei modelli proposti."], ["Energia e bollette di domani", "Produzione, quota consumata in casa e bolletta rimasta sono stime scritte nel preventivo."], ["Incentivi e rientro", "Detrazione e Conto Termico valgono su componenti diversi; il rientro tiene conto di entrambi."]],
    stages: [["Sopralluogo e consumi", "Guardiamo tetto, locale tecnico e impianto di oggi, e leggiamo con te le bollette di gas e luce."], ["Progetto e pratiche", "Dimensioniamo impianto e batteria sui tuoi consumi e prepariamo connessione alla rete e pratiche per gli incentivi."], ["Installazione coordinata", "Fotovoltaico, batteria, pompa di calore e induzione in giorni concordati, un lavoro alla volta."], ["Attivazione e addio al gas", "Colleghiamo l'impianto, avviamo la pompa di calore e ti spieghiamo l'app; poi il contratto del gas si chiude."]],
    // Le stesse domande del documento: una sola fonte, src/lib/fullElectric/testi.ts.
    faq: FAQ_FULL_ELECTRIC.map(({ domanda, risposta }) => [domanda, risposta] as TetEditorialPair),
    rows: [["Fotovoltaico e batteria", "Impianto fotovoltaico con batteria di accumulo della configurazione dimostrativa", 14200], ["Pompa di calore", "Pompa di calore aria-acqua per riscaldamento e acqua calda, installazione compresa", 10300], ["Cucina e impianto elettrico", "Piano a induzione e adeguamento della linea elettrica", 1500]],
    usp: [["Un solo progetto", "Fotovoltaico, batteria, pompa di calore e induzione dimensionati insieme sui tuoi consumi, non quattro preventivi da mettere d'accordo."], ["I numeri, messi in chiaro", "Produzione, bollette prima e dopo, incentivi e rientro: stime scritte, pagina per pagina, sugli stessi dati."], ["Dalla pratica all'app", "Connessione alla rete, pratiche per gli incentivi e l'app per seguire l'energia di casa."]],
    garanzie: [["Garanzia del produttore", "Su moduli, inverter, batteria e pompa di calore valgono le garanzie dei produttori, alle condizioni della loro documentazione."], ["Impianto a regola d'arte", "A fine lavori rilasciamo le dichiarazioni di conformità previste per le opere eseguite."], ["Pratiche seguite", "Connessione alla rete e pratiche per gli incentivi compresi nella proposta: le seguiamo noi, con i tuoi documenti."], ["Assistenza definita", "Contatti e documenti restano a te; manutenzione e servizi aggiuntivi sono quelli concordati."]],
  },
} satisfies Record<string, IdrEditorial>;
