import type { PavUnitaMisura } from "@/types/pavimenti";

export type PavEditorialPair = readonly [string, string];
export interface PavEditorialContent {
  title: string; hero: string; subtitle: string; cover: string; detail: string; material: string;
  scope: string; specs: PavEditorialPair[]; stages: PavEditorialPair[];
  protection: PavEditorialPair[]; checks: PavEditorialPair[]; documents: PavEditorialPair[];
  faq: PavEditorialPair[];
  rows: [string, string, PavUnitaMisura, number, number][];
}

/** Native ImageGen illustrations of operations, never evidence of completed company jobs. */
export const PAV_OPERATIONAL_IMAGES = {
  resina: "/module-art/pavimenti-resina-applicazione-v1.jpg",
  parquet: "/module-art/pavimenti-parquet-levigatura-v1.jpg",
  pareti: "/module-art/pavimenti-pareti-posa-verticale-v1.jpg",
  esterni: "/module-art/pavimenti-esterni-controllo-pendenza-v1.jpg",
} as const;

/** Editorial stock illustrates choices and workmanship, never completed company jobs. */
export const PAV_EDITORIAL = {
  sovrapposizione: {
    title: "Posa su fondo esistente", hero: "Una nuova superficie.\nUna base da verificare.",
    subtitle: "Rinnovare il pavimento conservando il supporto compatibile: quote, adesione e raccordi prima della posa.",
    cover: "/module-art/pavimenti.jpg", detail: "/pdf-stock/pavimenti/installazione.jpg", material: "Gres porcellanato",
    scope: "La sovrapposizione interessa solo le superfici rilevate e il fondo risultato idoneo. Non corregge cedimenti, umidità o distacchi nascosti. Demolizioni estese, porte da accorciare, soglie e rifacimento dei sottofondi richiedono voci dedicate.",
    specs: [
      ["Il fondo che rimane", "Verifichiamo stabilità, adesione, planarità e presenza di fessure o umidità. Le zone non idonee vengono individuate prima di confermare il ciclo."],
      ["Le quote della casa", "Lo spessore di adesivo e nuova finitura si confronta con porte, portefinestre, soglie, scale ed elettrodomestici incassati."],
      ["Materiale e disegno", "Formato, direzione di posa, fuga e tagli si concordano su campione. Sfridi e scorta sono quantità da esplicitare nel computo."],
      ["Raccordi che durano", "I giunti presenti si valutano prima di coprirli. Battiscopa e profili di transizione completano soltanto i tratti indicati in offerta."],
    ],
    stages: [
      ["Rilievo del supporto", "Misuriamo le superfici accessibili e registriamo quote, difetti e raccordi critici."],
      ["Preparazione compatibile", "Pulizia, preparazione superficiale e primer si scelgono in funzione del supporto e del sistema di posa."],
      ["Posa e raccordi", "Si eseguono posa, tagli, giunti, stuccatura e finiture comprese secondo il disegno approvato."],
      ["Riapertura degli ambienti", "Concordiamo quando camminare, pulire e ricollocare gli arredi seguendo i tempi dei prodotti impiegati."],
    ],
    protection: [["Zone utilizzabili", "Organizziamo il lavoro per aree e indichiamo i passaggi che devono rimanere liberi."], ["Arredi e porte", "Lo spostamento dei mobili si concorda; le ante vicine alla nuova quota vanno verificate prima della posa."], ["Tagli e polvere", "Definiamo l'area di taglio e proteggiamo superfici e ambienti adiacenti."], ["Prima dell'uso", "Le zone fresche restano interdette fino al tempo di transito comunicato."]],
    checks: [["Quote finali", "Riscontro dei raccordi e dell'apertura delle porte interessate."], ["Posa e fughe", "Controllo visivo di allineamenti, tagli e continuità delle fughe previste."], ["Giunti", "Verifica dei raccordi e dei giunti individuati nel progetto di posa."], ["Consegna", "Registrazione di eventuali osservazioni prima di ricollocare gli arredi."]],
    documents: [["Materiale scelto", "Codici, formato, tono e lotto disponibili della fornitura."], ["Ciclo di posa", "Prodotti impiegati per preparazione, adesione e stuccatura."], ["Disegno e raccordi", "Schema concordato e indicazioni sui giunti conservati."], ["Cura iniziale", "Tempi di utilizzo e prodotti di pulizia compatibili."]],
    faq: [["Posso evitare ogni demolizione?", "Solo se il fondo è compatibile. Zone instabili o distaccate possono richiedere rimozioni localizzate da concordare."], ["Quanto si alza il pavimento?", "Dipende da materiale e ciclo di posa. La quota complessiva va verificata con porte e soglie prima dell'ordine."], ["Si coprono le crepe?", "Prima si valuta la causa. La nuova superficie non elimina automaticamente movimenti o cedimenti del supporto."], ["È adatto al riscaldamento a pavimento?", "Serve una verifica della stratigrafia e della compatibilità dei materiali con l'impianto esistente."], ["Il battiscopa è incluso?", "Solo per tipo, altezza e metri indicati nel computo; rimozione e ripristini vanno specificati."], ["Gli arredi possono rimanere?", "Le zone di posa devono essere accessibili. Spostamenti e deposito si concordano prima dell'avvio."], ["Quando posso camminarci?", "I tempi dipendono dai prodotti e dalle condizioni del cantiere; vengono comunicati prima della riconsegna."], ["Come scelgo colore e fuga?", "Con un campione e uno schema approvati. La foto del modello è illustrativa e non identifica la fornitura."]],
    rows: [["Preparazione", "Preparazione del fondo esistente compatibile e primer del ciclo dimostrativo", "mq", 45, 16], ["Materiale", "Fornitura gres del formato da confermare, senza scorta aggiuntiva", "mq", 45, 34], ["Posa", "Posa in sovrapposizione, tagli ordinari e stuccatura", "mq", 45, 32], ["Raccordi", "Battiscopa e raccordi sui soli tratti rilevati", "ml", 30, 15]],
  },
  rifacimento: {
    title: "Rimozione e rifacimento", hero: "Ripartire dal fondo.\nRinnovare ogni passo.",
    subtitle: "Rimozione del pavimento, verifica dei sottofondi e nuova posa con lavorazioni e finiture definite.",
    cover: "/pdf-stock/pavimenti/installazione.jpg", detail: "/pdf-stock/pavimenti/materiali.jpg", material: "Gres porcellanato",
    scope: "Il rifacimento comprende rimozioni, preparazioni e posa elencate nel computo. Lo stato del fondo scoperto può richiedere una revisione prima di proseguire. Rifacimento degli impianti, consolidamenti strutturali e bonifiche non sono impliciti nella sostituzione del pavimento.",
    specs: [["Che cosa rimuoviamo", "Pavimento, collante, battiscopa ed eventuale massetto vengono distinti per estensione e profondità di intervento."], ["Il sottofondo scoperto", "Dopo la rimozione si verificano compattezza, quote e condizioni del supporto prima delle preparazioni successive."], ["La nuova stratigrafia", "Spessori, materiali e tempi di maturazione si coordinano con le quote finite e gli ambienti adiacenti."], ["Finiture misurabili", "Materiale, formato, fuga, battiscopa e raccordi sono descritti e quantificati separatamente."]],
    stages: [["Rilievo e organizzazione", "Individuiamo aree di demolizione, percorsi di trasporto e parti da conservare."], ["Rimozione controllata", "Rimuoviamo gli strati previsti, gestiamo i materiali di risulta e rivalutiamo il fondo accessibile."], ["Preparazione e nuova posa", "Eseguiamo i ripristini concordati e attendiamo l'idoneità del supporto prima di posare."], ["Finiture e consegna", "Completiamo fughe, raccordi e pulizia prevista; verifichiamo insieme gli ambienti."]],
    protection: [["Impianti esistenti", "Prima delle demolizioni identifichiamo i passaggi conosciuti e i punti sensibili."], ["Polvere e rumore", "Concordiamo orari, separazione degli ambienti e area per il deposito temporaneo."], ["Percorsi di trasporto", "Proteggiamo i passaggi utilizzati per movimentare materiali e macerie."], ["Fondi scoperti", "Delimitiamo dislivelli e superfici non transitabili durante le lavorazioni."]],
    checks: [["Supporto pronto", "Riscontro di quote e condizioni del sottofondo prima della copertura."], ["Superficie finita", "Verifica visiva di planarità, allineamento e tagli nelle aree concordate."], ["Raccordi", "Controllo di soglie, battiscopa e passaggi verso i locali conservati."], ["Riconsegna", "Annotazione delle lavorazioni concluse e delle eventuali osservazioni."]],
    documents: [["Rimozioni", "Riepilogo degli strati rimossi e delle attività effettivamente svolte."], ["Preparazioni", "Materiali e interventi concordati sul fondo dopo l'apertura."], ["Nuova fornitura", "Codici dei rivestimenti e riferimenti dei prodotti di posa."], ["Uso e cura", "Indicazioni per pulizia iniziale, transito e ricollocazione dei mobili."]],
    faq: [["Si demolisce anche il massetto?", "Solo se previsto. Pavimento, collante e massetto sono strati distinti da descrivere nel computo."], ["Che cosa succede se il fondo è degradato?", "Si documenta il problema e si concordano lavorazioni e costi prima di proseguire."], ["Sono inclusi carico e smaltimento?", "Le attività di movimentazione, trasporto e gestione del rimosso devono risultare nell'offerta."], ["Gli impianti vengono rifatti?", "No, salvo voci dedicate. La rimozione del pavimento non equivale al rinnovo degli impianti sottostanti."], ["Posso mantenere lo stesso livello?", "Le quote si verificano rispetto agli spessori reali e ai raccordi con gli ambienti conservati."], ["Quanto resta inutilizzabile la stanza?", "Il programma dipende dalle preparazioni e dai tempi di maturazione; le date vanno confermate dopo il rilievo."], ["Sono compresi i battiscopa?", "Solo quelli indicati per materiale, quantità e posa. I ripristini delle pareti sono da distinguere."], ["Resteranno piastrelle di scorta?", "La scorta va quantificata e ordinata esplicitamente, possibilmente insieme allo stesso lotto."]],
    rows: [["Rimozioni", "Rimozione pavimento e collante nei limiti concordati", "mq", 45, 23], ["Gestione rimosso", "Carico, trasporto e gestione dei materiali ordinari rimossi", "corpo", 1, 420], ["Sottofondo", "Regolarizzazione del supporto compatibile, senza rifacimento integrale del massetto", "mq", 45, 22], ["Fornitura e posa", "Gres, posa, tagli ordinari e stuccatura della configurazione dimostrativa", "mq", 45, 66], ["Finiture", "Battiscopa e raccordi descritti", "ml", 30, 15]],
  },
  resina: {
    title: "Pavimentazione in resina", hero: "Continuità da vivere.\nUn ciclo da progettare.",
    subtitle: "Supporto, preparazione e finitura lavorano insieme: la resina si sceglie per l'uso reale degli ambienti.",
    cover: "/module-art/pavimenti-resina.jpg", detail: PAV_OPERATIONAL_IMAGES.resina, material: "Resina",
    scope: "La proposta riguarda il ciclo in resina e le preparazioni descritte. La finitura non risolve da sola umidità, fessurazioni attive o cedimenti. Impermeabilizzazione, rinforzi, trattamento dei giunti e risvolti devono essere espressamente individuati.",
    specs: [["Supporto e umidità", "Compattezza, contaminazioni e condizioni di umidità guidano l'idoneità del ciclo. Eventuali criticità si risolvono prima della finitura."], ["Uso della superficie", "Traffico, acqua, detergenti ed esposizione alla luce orientano la scelta del sistema e della protezione finale."], ["Campione e aspetto", "Colore, grado di lucentezza e texture si approvano su campione; una lavorazione continua può presentare variazioni materiche."], ["Giunti e raccordi", "Si definiscono giunti da rispettare, risvolti e connessioni con soglie o rivestimenti di altro materiale."]],
    stages: [["Diagnosi del supporto", "Rileviamo stato, utilizzo previsto e punti critici della superficie."], ["Preparazione del ciclo", "La lavorazione meccanica e i primer sono quelli previsti dal sistema scelto."], ["Applicazione degli strati", "Eseguiamo gli strati concordati rispettando le condizioni e gli intervalli del prodotto."], ["Protezione e avvio all'uso", "Consegniamo indicazioni su maturazione, carichi, detergenti e manutenzione della finitura."]],
    protection: [["Ambienti separati", "Delimitiamo le zone di applicazione e concordiamo ventilazione e accessi."], ["Bordi e superfici", "Proteggiamo serramenti, pareti e arredi non interessati dal ciclo."], ["Condizioni del cantiere", "Temperature, polvere e umidità devono essere compatibili con i prodotti durante l'applicazione."], ["Maturazione", "Evitiamo transito e posa di teli o oggetti sulla finitura prima dei tempi comunicati."]],
    checks: [["Ciclo applicato", "Riscontro dei prodotti e degli strati effettivamente previsti."], ["Aspetto concordato", "Confronto visivo con campione, texture e lucentezza approvati."], ["Giunti e bordi", "Verifica dei raccordi e delle interruzioni del ciclo previste."], ["Utilizzo", "Conferma dei tempi per transito, lavaggio e carichi ordinari."]],
    documents: [["Sistema scelto", "Riferimenti dei prodotti per primer, strati e protezione finale."], ["Campione", "Colore e finitura approvati, con le variazioni materiche previste."], ["Supporto", "Annotazioni sulle preparazioni e sui punti critici trattati."], ["Manutenzione", "Detergenti compatibili, cautele iniziali e modalità di eventuale ripristino."]],
    faq: [["La resina elimina le fughe?", "L'aspetto può essere continuo, ma giunti e movimenti del supporto devono essere gestiti secondo il sistema previsto."], ["È impermeabile?", "Solo un sistema espressamente progettato e applicato per questa funzione può essere valutato come impermeabilizzazione."], ["Posso applicarla sopra le piastrelle?", "Occorre verificare adesione, planarità e umidità e definire le preparazioni del ciclo."], ["È resistente a tutto?", "Resistenza e manutenzione dipendono dal sistema e dall'uso. Non è una promessa di assenza di graffi o macchie."], ["Il colore sarà uniforme?", "La texture e le possibili variazioni materiche si concordano su campione prima dei lavori."], ["Quanto impiega ad asciugare?", "Transito e pieno utilizzo possono avere tempi diversi; fanno riferimento ai prodotti e alle condizioni effettive."], ["Si può riparare localmente?", "Dipende dal ciclo. Un ripristino può restare visibile e va valutato prima di promettere un risultato uniforme."], ["Posso usarla all'esterno?", "Solo con un sistema adeguato all'esposizione, al supporto e alla destinazione prevista, da indicare in offerta."]],
    rows: [["Preparazione", "Preparazione meccanica del fondo idoneo per ciclo in resina", "mq", 40, 21], ["Primer", "Primer e preparazioni previste dal sistema dimostrativo", "mq", 40, 18], ["Ciclo resina", "Applicazione del ciclo e finitura decorativa da campionare", "mq", 40, 62], ["Protezione", "Protezione finale e raccordi ordinari previsti", "mq", 40, 19]],
  },
  parquet: {
    title: "Recupero parquet", hero: "Il legno che hai.\nUna nuova vita.",
    subtitle: "Riparazioni, levigatura e finitura rispettano lo spessore disponibile e il carattere del parquet esistente.",
    cover: "/pdf-stock/pavimenti/vita.jpg", detail: PAV_OPERATIONAL_IMAGES.parquet, material: "Parquet esistente",
    scope: "Il recupero interessa le superfici e le riparazioni elencate. La possibilità di levigare dipende da spessore utile, precedenti lavorazioni e stabilità degli elementi. Macchie profonde, dislivelli e differenze tra legno nuovo ed esistente possono rimanere visibili.",
    specs: [["Legno e spessore utile", "Identifichiamo la tipologia del parquet e valutiamo lo strato lavorabile prima di proporre la levigatura."], ["Elementi da riparare", "Doghe mobili, mancanti o danneggiate si individuano e si quantificano separatamente, verificando la reperibilità di elementi compatibili."], ["Finitura scelta", "Olio o vernice, colore e lucentezza si scelgono con campione e indicazioni sulla manutenzione prevista."], ["Carattere da conservare", "Venature, ossidazione e precedenti segni fanno parte del risultato atteso: il recupero non trasforma ogni parquet in un pavimento nuovo."]],
    stages: [["Verifica del parquet", "Controlliamo stabilità e condizioni visibili del legno, bordi e precedenti trattamenti."], ["Riparazioni concordate", "Interveniamo sugli elementi descritti e prepariamo la superficie per la lavorazione."], ["Levigatura e finitura", "Eseguiamo il ciclo compatibile con lo spessore disponibile e la finitura approvata."], ["Rientro e cura", "Comunichiamo tempi per camminare, arredi e tappeti, con istruzioni per la pulizia."]],
    protection: [["Locali liberi", "Concordiamo lo sgombero completo delle zone da levigare e il deposito degli arredi."], ["Polvere", "Proteggiamo gli ambienti confinanti; l'aspirazione delle macchine non implica assenza assoluta di polvere."], ["Bordi delicati", "Battiscopa, soglie e arredi fissi vengono individuati prima delle lavorazioni."], ["Finitura fresca", "Accesso, aerazione e ricollocazione dei tappeti seguono i tempi comunicati per il prodotto."]],
    checks: [["Stabilità", "Riscontro delle riparazioni sugli elementi individuati."], ["Aspetto del legno", "Confronto del risultato con il campione e i limiti concordati."], ["Bordi e passaggi", "Controllo delle lavorazioni vicino a soglie e battiscopa."], ["Cura", "Spiegazione delle cautele per acqua, detergenti, feltrini e tappeti."]],
    documents: [["Intervento eseguito", "Aree lavorate ed elementi riparati o sostituiti."], ["Finitura", "Prodotto, colore e lucentezza concordati."], ["Limiti del recupero", "Segni preesistenti e differenze di tono riconosciuti nel sopralluogo."], ["Manutenzione del legno", "Istruzioni per pulizia e rinnovo della protezione scelta."]],
    faq: [["Tutti i parquet si possono levigare?", "No. Serve uno spessore lavorabile adeguato e un pavimento stabile; un laminato non si tratta come il legno."], ["Scompariranno tutte le macchie?", "Macchie profonde o alterazioni del legno possono restare. Il risultato va valutato e concordato prima."], ["Le doghe nuove avranno lo stesso colore?", "Specie, età e ossidazione possono creare differenze anche con materiale compatibile."], ["Olio o vernice?", "La scelta considera aspetto, uso e manutenzione. Si conferma con un campione e il ciclo del prodotto."], ["Ci sarà polvere?", "Si usano protezioni e aspirazione, ma la lavorazione non garantisce un ambiente privo di polvere."], ["Devo togliere tutti i mobili?", "Le aree da lavorare devono essere libere; lo spostamento degli arredi va concordato."], ["Quando rimetto tappeti e mobili?", "Dopo i tempi comunicati per la finitura applicata; transito leggero e copertura del legno possono richiedere attese diverse."], ["Si possono recuperare solo alcune stanze?", "Sì, valutando raccordi e possibili differenze di aspetto con le superfici non trattate."]],
    rows: [["Preparazione", "Preparazione parquet e verifica delle zone lavorabili", "mq", 40, 6], ["Riparazioni", "Riparazioni localizzate degli elementi descritti nell'esempio", "corpo", 1, 280], ["Levigatura", "Levigatura compatibile con spessore utile verificato", "mq", 40, 21], ["Finitura", "Ciclo di finitura da campionare e istruzioni di manutenzione", "mq", 40, 24]],
  },
  pareti: {
    title: "Rivestimenti a parete", hero: "Pareti da guardare.\nDettagli da risolvere.",
    subtitle: "Materiali, allineamenti e tagli costruiscono il disegno; supporti e raccordi ne rendono possibile la posa.",
    cover: "/module-art/pavimenti-pareti.jpg", detail: PAV_OPERATIONAL_IMAGES.pareti, material: "Rivestimento ceramico",
    scope: "Sono comprese le pareti, le altezze e le preparazioni descritte. Nicchie, forature, profili, grandi lastre e impermeabilizzazione delle zone bagnate richiedono specifiche voci. Un rivestimento decorativo non sostituisce la verifica del supporto o degli impianti nascosti.",
    specs: [["Pareti da rivestire", "Misuriamo altezze, aperture e sviluppo delle superfici, distinguendo nicchie e imbotti."], ["Supporto verticale", "Planarità, consistenza e compatibilità dell'intonaco o del pannello si verificano rispetto a formato e peso della finitura."], ["Disegno e tagli", "Partenze, allineamento delle fughe, angoli e tagli intorno alle prese vengono approvati prima della posa."], ["Acqua e raccordi", "Nelle aree esposte all'acqua si definiscono eventuale sistema impermeabile, sigillature e collegamenti con sanitari o piani."]],
    stages: [["Rilievo delle pareti", "Registriamo misure, aperture, attacchi e supporti accessibili."], ["Schema approvato", "Concordiamo materiale, altezze, fughe, tagli e finitura degli spigoli."], ["Preparazione e posa", "Eseguiamo preparazioni previste, posa verticale, forature e profili elencati."], ["Sigillature e consegna", "Completiamo i raccordi concordati e spieghiamo pulizia e cura delle fughe."]],
    protection: [["Piani e pavimenti", "Proteggiamo sanitari, arredi e superfici sotto le pareti interessate."], ["Impianti", "Individuiamo prese e attacchi; spostamenti e scollegamenti richiedono attività specifiche."], ["Taglio delle lastre", "Concordiamo movimentazione, appoggi e area di taglio adeguati al formato."], ["Uso della zona", "Evitiamo acqua e urti sulle superfici appena posate fino ai tempi comunicati."]],
    checks: [["Allineamento", "Riscontro delle partenze e delle fughe rispetto allo schema concordato."], ["Spigoli e fori", "Verifica di profili, tagli e raccordi attorno agli elementi esistenti."], ["Sigillature", "Controllo dei collegamenti previsti nelle zone esposte all'acqua."], ["Pulizia finale", "Rimozione dei residui secondo i materiali e indicazioni di manutenzione."]],
    documents: [["Disegno approvato", "Superfici, altezze e schema dei tagli scelti."], ["Fornitura", "Codici del rivestimento, profili e materiali per fughe."], ["Zone bagnate", "Sistema impermeabile e raccordi soltanto se inclusi nel lavoro."], ["Cura", "Istruzioni per detergenti, fughe e sigillature."]],
    faq: [["Si può posare sul vecchio rivestimento?", "Solo su supporto compatibile e dopo aver definito preparazione, quote e raccordi."], ["Le grandi lastre costano come le piastrelle?", "Formato, movimentazione e tagli influenzano la lavorazione e vanno descritti in offerta."], ["Le prese vengono spostate?", "Solo con interventi impiantistici previsti separatamente; la posa non include automaticamente lo spostamento."], ["La doccia è impermeabilizzata?", "Il rivestimento da solo non definisce un sistema impermeabile. Preparazioni e raccordi devono essere indicati."], ["Come saranno chiusi gli angoli?", "Profili, pezzi speciali o lavorazioni dei bordi si scelgono nello schema di posa."], ["Sono incluse nicchie e forature?", "Solo se quantificate e descritte, considerando formato e posizione."], ["La fuga può essere invisibile?", "Larghezza e materiale si scelgono in funzione del prodotto e della posa, senza promettere assenza di fughe."], ["Quando posso usare l'acqua?", "Dopo i tempi previsti per adesivi, fughe e sigillanti effettivamente applicati."]],
    rows: [["Supporto", "Preparazione di pareti idonee nelle superfici rilevate", "mq", 25, 18], ["Fornitura", "Rivestimento ceramico del formato dimostrativo", "mq", 25, 38], ["Posa verticale", "Posa, tagli ordinari e stuccatura secondo schema", "mq", 25, 39], ["Profili", "Profili di chiusura e raccordi elencati", "ml", 12, 22]],
  },
  esterni: {
    title: "Pavimentazioni esterne", hero: "Spazi aperti.\nAcqua con una direzione.",
    subtitle: "Sottofondo, pendenze, drenaggio e finitura si coordinano con esposizione e utilizzo dello spazio esterno.",
    cover: "/module-art/pavimenti-esterni.jpg", detail: PAV_OPERATIONAL_IMAGES.esterni, material: "Gres per esterni",
    scope: "L'offerta riguarda le superfici e il sistema di posa descritti. Pendenze e punti di raccolta vanno verificati sul posto. Impermeabilizzazioni, nuovi scarichi, scavi, consolidamenti e portata carrabile richiedono un progetto e voci specifiche; non sono impliciti nella nuova finitura.",
    specs: [["Destinazione reale", "Terrazzo, percorso o area carrabile hanno esigenze diverse. Carichi, transito e manutenzione guidano il sistema scelto."], ["Quote e pendenze", "Le quote finite si confrontano con soglie, scarichi e percorsi dell'acqua per evitare raccordi improvvisati."], ["Materiale per esposizione", "La finitura va selezionata per condizioni esterne, uso e caratteristiche dichiarate dal produttore."], ["Strati e giunti", "Supporto, eventuale impermeabilizzazione, posa e giunti devono essere compatibili tra loro e con i dettagli perimetrali."]],
    stages: [["Rilievo dello spazio", "Misuriamo quote, pendenze esistenti e punti di raccolta accessibili."], ["Sistema e dettagli", "Concordiamo stratigrafia, materiale, raccordi e opere per il drenaggio incluse."], ["Preparazione e posa", "Programmiamo i lavori secondo il meteo e realizziamo le lavorazioni previste."], ["Controllo e manutenzione", "Verifichiamo finiture e percorsi dell'acqua previsti, poi consegniamo le indicazioni per la cura."]],
    protection: [["Accessi esterni", "Delimitiamo percorsi, gradini e zone di deposito mantenendo gli accessi concordati."], ["Meteo", "Proteggiamo materiali e lavorazioni fresche in relazione a pioggia, sole e temperature."], ["Scarichi", "Evitiamo l'ingresso di residui nelle griglie e proteggiamo i punti di raccolta durante la posa."], ["Verde e facciate", "Individuiamo le superfici adiacenti da preservare e i limiti dell'area di cantiere."]],
    checks: [["Pendenze", "Riscontro delle quote e dei percorsi verso i punti di raccolta previsti."], ["Raccordi", "Controllo di soglie, bordi, giunti e connessioni con le superfici conservate."], ["Superficie", "Verifica visiva di posa e fughe in relazione al sistema concordato."], ["Scarichi accessibili", "Controllo della pulizia e dell'accessibilità dei punti interessati, senza certificare reti non oggetto dei lavori."]],
    documents: [["Sistema di posa", "Stratigrafia e materiali effettivamente previsti."], ["Quote e raccordi", "Indicazioni dei dettagli concordati presso soglie e scarichi."], ["Caratteristiche", "Schede del materiale selezionato per la destinazione esterna."], ["Manutenzione", "Pulizia della finitura, dei giunti e dei punti di raccolta accessibili."]],
    faq: [["Il nuovo pavimento risolve le infiltrazioni?", "Solo se si individuano le cause e si prevede il sistema necessario. La sostituzione della finitura non è automaticamente un intervento impermeabile."], ["È adatto alle auto?", "L'uso carrabile richiede una valutazione di supporto, carichi e sistema; non dipende soltanto dalla piastrella."], ["Si possono correggere le pendenze?", "Occorre verificare quote disponibili, soglie e scarichi; le preparazioni vanno quantificate."], ["Sono inclusi scarichi nuovi?", "Solo se elencati con collegamenti e opere accessorie."], ["La superficie è antiscivolo?", "La scelta considera caratteristiche dichiarate e condizioni d'uso. Acqua, sporco e manutenzione influenzano il comportamento reale."], ["Si può lavorare con qualsiasi meteo?", "No. Temperature e precipitazioni devono essere compatibili con i materiali e possono modificare il programma."], ["La posa è incollata o sopraelevata?", "Il sistema va indicato nell'offerta: preparazioni e dettagli cambiano e non sono intercambiabili."], ["Serve manutenzione?", "Sì: pulizia di superficie, giunti e punti di raccolta secondo i materiali e l'esposizione."]],
    rows: [["Preparazione", "Preparazione e regolarizzazione delle pendenze nelle aree concordate", "mq", 35, 29], ["Fornitura", "Gres per esterni della configurazione pedonale dimostrativa", "mq", 35, 42], ["Posa", "Posa incollata e stuccatura compatibile con uso esterno", "mq", 35, 38], ["Raccordi", "Raccordi perimetrali e giunti sui tratti descritti", "ml", 24, 24]],
  },
  "posa-parquet": {
    title: "Posa parquet", hero: "Il calore del legno.\nPosato a regola.",
    subtitle: "Parquet prefinito o massello posato sul supporto giusto: fondo, posa e finiture definiti prima, con quote e raccordi verificati.",
    cover: "/pdf-stock/pavimenti/vita.jpg", detail: "/pdf-stock/pavimenti/installazione.jpg", material: "Parquet prefinito o massello",
    scope: "La posa riguarda le superfici e il tipo di parquet elencati. Il fondo va verificato per planarità e umidità: incollato o flottante sono soluzioni diverse. Rimozione del pavimento esistente, massetti, barriere al vapore, accorciamento delle porte e battiscopa richiedono voci dedicate.",
    specs: [
      ["Il fondo prima del legno", "Planarità, umidità residua e pulizia del supporto decidono se posare e come: un fondo umido o irregolare compromette il parquet, si verifica prima."],
      ["Prefinito o massello", "Spessore, incastro e possibilità di future levigature cambiano con il tipo scelto. La posa incollata e quella flottante non sono intercambiabili."],
      ["Disegno e direzione", "Senso delle doghe, partenza, sfrido e giochi perimetrali si concordano su campione: il legno lavora, il giunto di dilatazione non è facoltativo."],
      ["Quote e raccordi", "Spessore del pacchetto, soglie, porte e battiscopa si confrontano prima dell'ordine; profili di transizione completano i soli tratti indicati."],
    ],
    stages: [
      ["Rilievo del fondo", "Misuriamo superfici, quote e verifichiamo planarità e umidità del supporto accessibile."],
      ["Materiale e posa", "Confermiamo tipo di parquet, disegno, sistema di posa e finiture su campione approvato."],
      ["Posa e giunti", "Eseguiamo posa, tagli, giunti di dilatazione e finiture perimetrali comprese secondo lo schema."],
      ["Cura del legno", "Concordiamo tempi per camminare, arredi e tappeti e consegniamo le indicazioni di manutenzione."],
    ],
    protection: [["Zone di posa", "Organizziamo il lavoro per aree e indichiamo i passaggi da lasciare liberi durante la posa."], ["Arredi e porte", "Lo spostamento dei mobili si concorda; le ante vicine alla nuova quota vanno verificate prima."], ["Umidità e clima", "Il legno va acclimatato; condizioni di umidità e temperatura del cantiere influiscono sulla posa."], ["Prima dell'uso", "Le zone appena posate restano interdette fino ai tempi comunicati per adesivi e finiture."]],
    checks: [["Planarità e posa", "Riscontro di allineamenti, incastri e giochi perimetrali rispetto allo schema."], ["Giunti", "Verifica dei giunti di dilatazione e dei raccordi con altre superfici."], ["Quote e porte", "Controllo delle soglie e dell'apertura delle porte interessate."], ["Consegna", "Registrazione di eventuali osservazioni e istruzioni per la cura del legno."]],
    documents: [["Parquet scelto", "Tipo, essenza, formato e lotto della fornitura."], ["Sistema di posa", "Incollato o flottante, adesivi e materassino impiegati."], ["Disegno e giunti", "Schema di posa e posizione dei giunti di dilatazione."], ["Cura del legno", "Prodotti e cautele per pulizia, umidità e manutenzione."]],
    faq: [["Meglio incollato o flottante?", "Dipende da fondo, tipo di parquet e uso. La posa incollata è più stabile; la flottante è più rapida. Si sceglie sul supporto reale, non a priori."], ["Va bene sul riscaldamento a pavimento?", "Serve verificare stratigrafia, tipo di legno e compatibilità con l'impianto: non ogni parquet e posa sono adatti."], ["Devo rimuovere il vecchio pavimento?", "Non sempre, se il fondo è idoneo. Rimozione, massetti e barriere al vapore si valutano e si quotano a parte."], ["Il legno si muoverà?", "Il parquet lavora con umidità e temperatura: i giunti di dilatazione servono proprio a questo. È un comportamento normale, non un difetto."], ["Le doghe avranno tutte lo stesso aspetto?", "Il legno è naturale: venature e tono variano. Si concorda un campione, sapendo che il risultato non è uniforme come un gres."], ["Il battiscopa è incluso?", "Solo per tipo, altezza e metri indicati nel computo; rimozione e ripristini vanno specificati."], ["Quando posso camminarci?", "Dopo i tempi di adesivi e finiture, comunicati prima della riconsegna. Tappeti e mobili pesanti richiedono attese diverse."], ["Come scelgo essenza e finitura?", "Con un campione e uno schema approvati. La foto del modello è illustrativa e non identifica la fornitura."]],
    rows: [["Preparazione", "Preparazione del fondo idoneo del ciclo dimostrativo", "mq", 40, 14], ["Materiale", "Fornitura parquet del tipo da confermare, senza scorta aggiuntiva", "mq", 40, 48], ["Posa", "Posa, tagli, giunti di dilatazione e finiture perimetrali", "mq", 40, 34], ["Raccordi", "Battiscopa e profili di transizione sui soli tratti rilevati", "ml", 28, 16]],
  },
  scale: {
    title: "Rivestimento scale", hero: "Ogni gradino.\nMisurato e rivestito.",
    subtitle: "Pedate, alzate e profili su misura per la scala reale: materiali, tagli e sicurezza del passo definiti prima della posa.",
    cover: "/module-art/pavimenti.jpg", detail: "/pdf-stock/pavimenti/tecnica-giunto.jpg", material: "Gres, legno o pietra per gradini",
    scope: "L'intervento riguarda i gradini, i pianerottoli e i profili elencati. Ogni scala ha misure proprie: pedate e alzate si rilevano una a una. Struttura della scala, adeguamenti geometrici, parapetti, corrimano e illuminazione richiedono voci dedicate.",
    specs: [
      ["Misure gradino per gradino", "Pedate e alzate raramente sono identiche: si rilevano una a una. Sporgenza del naso, spessore del materiale e quota finita cambiano il taglio di ogni elemento."],
      ["Materiale e sicurezza", "Gres, legno o pietra si scelgono su uso e resistenza. La sicurezza del passo, con superficie e bordo adeguati, non è un accessorio."],
      ["Profili e bordo", "Il profilo del naso protegge lo spigolo e segna il gradino: tipo, fissaggio e finitura si concordano prima della posa."],
      ["Raccordi e pianerottoli", "Attacco con il pavimento esistente, pianerottoli e sviluppo laterale vanno definiti per un risultato continuo, non improvvisato."],
    ],
    stages: [
      ["Rilievo della scala", "Misuriamo ogni gradino, i pianerottoli e i raccordi con le superfici adiacenti."],
      ["Materiale e schema", "Confermiamo materiale, profili, finitura del bordo e sicurezza del passo su campione."],
      ["Posa dei gradini", "Eseguiamo preparazione, posa di pedate, alzate e profili secondo le misure rilevate."],
      ["Riscontro e uso", "Verifichiamo continuità e bordo dei gradini e comunichiamo i tempi per l'uso della scala."],
    ],
    protection: [["Passaggio obbligato", "La scala spesso è l'unico accesso: organizziamo la posa per fasce e tempi che lascino un passaggio sicuro."], ["Bordi e spigoli", "Proteggiamo gli spigoli lavorati e le superfici adiacenti durante la posa e l'indurimento."], ["Polvere e tagli", "Definiamo l'area di taglio e proteggiamo gli ambienti vicini alla scala."], ["Prima del transito", "I gradini appena posati restano interdetti fino ai tempi comunicati per adesivi e finiture."]],
    checks: [["Misure e complanarità", "Riscontro di pedate, alzate e allineamento dei gradini rispetto al rilievo."], ["Bordo e profili", "Verifica dei profili del naso, dello spigolo e della sicurezza del passo."], ["Raccordi", "Controllo degli attacchi con pavimento e pianerottoli."], ["Consegna", "Registrazione di osservazioni e indicazioni per pulizia e uso."]],
    documents: [["Materiale scelto", "Tipo, formato e lotto degli elementi per gradini."], ["Profili e finiture", "Profili del naso, fissaggi e finitura del bordo impiegati."], ["Rilievo dei gradini", "Misure delle pedate, delle alzate e dei raccordi eseguiti."], ["Cura", "Prodotti e cautele per pulizia e manutenzione della scala."]],
    faq: [["Ogni gradino è uguale?", "Raramente: pedate e alzate variano di qualche millimetro. Per questo si rilevano una a una e i tagli si fanno su misura."], ["Che materiale è meglio per una scala?", "Dipende da uso, sicurezza e ambiente. Gres, legno e pietra hanno resistenze e resa diverse: si sceglie sul caso reale, con attenzione al passo."], ["I gradini saranno antiscivolo?", "La sicurezza del passo si cura con superficie e profilo del bordo adeguati. Acqua e usura influenzano il comportamento reale."], ["Serve il profilo sul bordo?", "Il profilo del naso protegge lo spigolo e rende visibile il gradino: tipo e fissaggio si concordano nello schema."], ["Posso rivestire sopra i gradini esistenti?", "Solo se struttura, quote e sporgenza lo consentono: aggiungere spessore cambia le alzate e va verificato prima."], ["Sono compresi corrimano e parapetti?", "No, salvo voce esplicita: sono elementi distinti da coordinare con l'intervento."], ["Quanto resta inagibile la scala?", "Si organizza per fasce e tempi, ma le zone appena posate restano interdette fino all'indurimento comunicato."], ["Come scelgo materiale e finitura?", "Con un campione e uno schema approvati. La foto del modello è illustrativa e non identifica la fornitura."]],
    rows: [["Rilievo e preparazione", "Rilievo dei gradini e preparazione dei piani del ciclo dimostrativo", "cad", 14, 22], ["Materiale", "Pedate, alzate e profili del materiale da confermare", "cad", 14, 68], ["Posa", "Posa di pedate, alzate e profili secondo le misure rilevate", "cad", 14, 46], ["Raccordi", "Raccordi con pavimento e pianerottoli sui tratti descritti", "ml", 6, 28]],
  },
  levigatura: {
    title: "Levigatura marmo e cotto", hero: "La superficie di sempre.\nRiportata a nuova.",
    subtitle: "Levigatura, lucidatura e trattamento di marmo, cotto e graniglia esistenti: un recupero che rispetta il materiale e i suoi limiti.",
    cover: "/pdf-stock/pavimenti/storia-prima-durante-dopo.jpg", detail: "/pdf-stock/pavimenti/vita.jpg", material: "Marmo, cotto o graniglia esistente",
    scope: "Il recupero interessa le superfici e le lavorazioni elencate. Il risultato dipende dallo stato del materiale: graffi profondi, macchie penetrate, dislivelli tra elementi e alcune fessure possono restare visibili. Sostituzione di parti mancanti, stuccature estese e nuovi trattamenti richiedono voci dedicate.",
    specs: [
      ["Materiale e stato reale", "Marmo, cotto e graniglia si lavorano in modo diverso. Durezza, usura, macchie e precedenti trattamenti determinano ciò che si può recuperare."],
      ["Ciclo di lavorazione", "Levigatura, eventuale stuccatura, lucidatura e trattamento protettivo sono fasi distinte: si concordano sul materiale, non si danno per scontate."],
      ["Finitura attesa", "Lucido, satinato o naturale si scelgono su campione. Il recupero migliora la superficie ma non trasforma un materiale usurato in nuovo."],
      ["Limiti riconosciuti", "Macchie penetrate, dislivelli tra gli elementi e piccole fessure fanno parte del risultato atteso e si segnalano prima, non dopo."],
    ],
    stages: [
      ["Verifica della superficie", "Controlliamo materiale, stato, macchie e dislivelli visibili prima di proporre il ciclo."],
      ["Ciclo e finitura", "Confermiamo lavorazioni, stuccature comprese e finitura su una zona campione."],
      ["Levigatura e trattamento", "Eseguiamo levigatura, lucidatura e trattamento protettivo previsti sulle superfici concordate."],
      ["Cura della superficie", "Comunichiamo i tempi per camminare e arredi e consegniamo le indicazioni di manutenzione."],
    ],
    protection: [["Locali liberi", "Concordiamo lo sgombero delle zone da lavorare e il deposito degli arredi."], ["Polvere e acqua", "Proteggiamo gli ambienti confinanti; la levigatura, a secco o a umido, richiede protezioni adeguate."], ["Bordi e battiscopa", "Individuiamo battiscopa, soglie e arredi fissi prima delle lavorazioni."], ["Trattamento fresco", "Accesso e ricollocazione dei tappeti seguono i tempi del trattamento applicato."]],
    checks: [["Uniformità", "Riscontro della levigatura e della lucidatura rispetto al campione concordato."], ["Stuccature", "Verifica delle stuccature comprese e dei raccordi tra gli elementi."], ["Bordi e passaggi", "Controllo delle lavorazioni vicino a soglie e battiscopa."], ["Cura", "Spiegazione delle cautele per acqua, detergenti e protezione periodica."]],
    documents: [["Intervento eseguito", "Superfici lavorate e materiale trattato."], ["Ciclo e finitura", "Lavorazioni, prodotti e finitura concordati."], ["Limiti del recupero", "Macchie, dislivelli e segni riconosciuti nel sopralluogo."], ["Manutenzione", "Prodotti e cautele per pulizia e rinnovo della protezione."]],
    faq: [["Il pavimento tornerà come nuovo?", "Il recupero migliora molto la superficie, ma non cancella la sua storia: alcune macchie profonde o segni possono restare. Si valuta prima, su una zona campione."], ["Marmo e cotto si lavorano uguale?", "No: durezza, porosità e ciclo di lucidatura sono diversi. Il cotto in genere richiede anche un trattamento protettivo dedicato."], ["Spariranno le macchie?", "Le macchie superficiali sì, quelle penetrate nel materiale spesso no. La differenza si riconosce nel sopralluogo, non si promette."], ["Devo togliere tutti i mobili?", "Le aree da lavorare devono essere libere; lo spostamento degli arredi si concorda prima dell'avvio."], ["Ci sarà molta polvere?", "La levigatura a umido la riduce; con protezioni e aspirazione si contiene, ma non si garantisce un ambiente privo di polvere."], ["Posso scegliere lucido o satinato?", "Sì, su campione. La resa dipende anche dal materiale: uno stesso ciclo dà risultati diversi su marmi diversi."], ["Serve un trattamento dopo?", "In genere sì, soprattutto per il cotto: protegge la superficie e va rinnovato nel tempo. Fa parte della manutenzione."], ["Si possono trattare solo alcune stanze?", "Sì, valutando i raccordi e le possibili differenze di aspetto con le superfici non trattate."]],
    rows: [["Preparazione", "Verifica e preparazione delle superfici del ciclo dimostrativo", "mq", 45, 8], ["Levigatura", "Levigatura del materiale esistente sulle aree concordate", "mq", 45, 22], ["Lucidatura", "Lucidatura e stuccature comprese secondo il campione", "mq", 45, 18], ["Trattamento", "Trattamento protettivo e istruzioni di manutenzione", "mq", 45, 9]],
  },
} satisfies Record<string, PavEditorialContent>;
