/** Editorial content for the six original Piscine documents. Images are illustrative. */
export type PscEditorialPair = readonly [string, string];
interface PscEditorialContent {
  title: string; hero: string; subtitle: string; cover: string; detail: string;
  scope: string; specs: readonly PscEditorialPair[]; stages: readonly PscEditorialPair[];
  checks: readonly PscEditorialPair[]; exclusions: readonly PscEditorialPair[];
  faq: readonly PscEditorialPair[]; rows: readonly (readonly [string, string, number])[];
}

export const PSC_EDITORIAL = {
  nuova: {
    title: "Nuova piscina", hero: "Il tuo spazio.\nUna nuova idea d'acqua.",
    subtitle: "Dal terreno al primo avviamento: struttura, circolazione e finiture pensate insieme.",
    cover: "/module-art/piscine.jpg", detail: "/pdf-stock/piscine/tecnica-vasca.jpg",
    scope: "La realizzazione comprende le opere e le dotazioni elencate nel computo, con dimensioni, sistema costruttivo e finiture da confermare nel progetto. Scavo, trasporto delle terre, locale tecnico e sistemazione del giardino devono avere un perimetro esplicito: la fotografia non definisce la fornitura.",
    specs: [
      ["Il terreno prima della forma", "Rilievo, quote, accesso dei mezzi e interferenze con reti esistenti guidano il posizionamento. Condizioni del terreno e presenza d'acqua richiedono valutazioni specifiche prima dello scavo."],
      ["La vasca e i suoi raccordi", "Dimensioni utili, profondità, scala e sistema costruttivo si definiscono insieme. Giunti, attraversamenti e bordo si coordinano con il rivestimento scelto."],
      ["L'acqua deve circolare", "Skimmer o sfioro, riprese, mandata e locale tecnico fanno parte di un sistema da dimensionare. Pompa, filtro e trattamento sono identificati nella proposta."],
      ["Il bordo incontra il giardino", "Materiali, pendenze e collegamenti con le superfici esterne si concordano sul posto. Solarium, doccia, illuminazione e copertura sono dotazioni distinte."]
    ],
    stages: [
      ["Rilievo e progetto", "Confermare posizione, quote, caratteristiche della vasca, accessi e verifiche preliminari prima di ordinare i materiali."],
      ["Preparazione e struttura", "Organizzare l'area, eseguire le opere di terreno previste e realizzare la struttura con i passaggi impiantistici concordati."],
      ["Impianti e superfici", "Posare tubazioni e apparecchiature, completare tenuta, rivestimento e bordo rispettando le sequenze del sistema scelto."],
      ["Avviamento accompagnato", "Registrare i controlli previsti, impostare le funzioni concordate e spiegare al proprietario comandi, pulizia e gestione ordinaria."]
    ],
    checks: [["Geometria e finiture", "Confrontare dimensioni e livelli realizzati con gli elaborati concordati; verificare bordi, scala e raccordi accessibili."], ["Circuiti e collegamenti", "Eseguire e registrare le prove previste sulle linee prima di coprirle, distinguendole dalle verifiche della vasca."], ["Filtrazione e comandi", "Riscontrare circolazione, filtrazione e regolazioni previste; verificare le dotazioni effettivamente installate."], ["Acqua e primo utilizzo", "Registrare i parametri misurati e le indicazioni di gestione. La sola limpidezza non sostituisce i controlli dell'acqua."]],
    exclusions: [["Pratiche e progettazione", "Incarichi tecnici, indagini e pratiche sono inclusi solo se descritti e quantificati."], ["Condizioni del terreno", "Roccia, falda, sottoservizi e opere di sostegno non rilevate richiedono valutazione e accordo economico."], ["Spazi esterni e dotazioni", "Giardino, solarium, arredi, riscaldamento e copertura non sono inclusi dalla sola immagine della piscina."]],
    faq: [["Quale forma posso scegliere?", "La forma deve essere compatibile con terreno, spazio e sistema costruttivo. Il rilievo consente di confermare dimensioni e profondità."], ["Skimmer o sfioro?", "Cambiano raccolta superficiale, quote, ingombri e componenti. La scelta va definita insieme al locale tecnico."], ["Lo scavo è compreso?", "Solo nei limiti della voce dedicata, precisando quantità, accessi, trasporto e destinazione dei materiali."], ["Chi verifica le pratiche necessarie?", "Il referente tecnico incaricato verifica il caso concreto. Ruoli e prestazioni professionali vanno indicati nella proposta."], ["Quanto dura il cantiere?", "Il programma dipende da progetto, accessibilità, meteo, forniture e tempi tecnici dei materiali; si concorda dopo il rilievo."], ["La piscina comprende una copertura?", "Solo se modello, misure, fissaggi e montaggio sono indicati. Una copertura termica non equivale automaticamente a un dispositivo di sicurezza."], ["È previsto il riscaldamento?", "Occorre una voce specifica con apparecchio, predisposizioni e collegamenti. Il consumo dipende anche da utilizzo e condizioni esterne."], ["Come avviene la consegna?", "Si rivedono dotazioni, verifiche e istruzioni, annotando eventuali attività residue e contatti per l'assistenza."]],
    rows: [["Vasca", "Struttura e predisposizioni della nuova piscina nella configurazione dimostrativa", 18000], ["Circolazione", "Circuito di filtrazione, componenti e collegamenti descritti nella proposta", 5200], ["Finiture e avviamento", "Sistema di rivestimento concordato e verifiche di avviamento della fornitura", 6800]],
  },
  ristrutturazione: {
    title: "Ristrutturazione piscina", hero: "Una piscina conosciuta.\nUn nuovo equilibrio.",
    subtitle: "Conservare ciò che funziona. Rinnovare struttura, superfici e impianti dove serve.",
    cover: "/pdf-stock/piscine/risultato.jpg", detail: "/pdf-stock/piscine/installazione.jpg",
    scope: "Il rinnovo riguarda le porzioni di vasca, le finiture e i componenti indicati. Una nuova superficie non risolve automaticamente lesioni strutturali o perdite delle tubazioni. Le parti conservate vengono distinte dalle parti sostituite e le anomalie emerse durante le rimozioni richiedono una variante concordata.",
    specs: [["Leggere lo stato esistente", "Raccogliere storia delle perdite, riparazioni precedenti e anomalie osservate. Il rilievo distingue vasca, bordo, raccordi e impianti accessibili."], ["Conservare con criterio", "Individuare supporti e componenti riutilizzabili, motivando le sostituzioni. La compatibilità tra vecchio e nuovo si verifica prima della posa."], ["Raccordare le superfici", "Preparazione, ripristini e finitura seguono un sistema coerente. Scale, spigoli, giunti e attraversamenti richiedono dettagli dedicati."], ["Rimettere in funzione", "Definire il percorso di riempimento e riavvio con i controlli previsti sulle parti interessate. Le reti nascoste conservate restano fuori dal rinnovo salvo voce specifica."]],
    stages: [["Rilievo e diagnosi", "Documentare le condizioni iniziali e circoscrivere le verifiche necessarie prima di definire le opere."], ["Rimozioni selettive", "Programmare messa fuori servizio, rimozioni e gestione dei materiali, proteggendo ciò che viene mantenuto."], ["Ripristino coordinato", "Eseguire le riparazioni concordate, adeguare i raccordi previsti e posare le nuove superfici."], ["Riapertura e consegna", "Verificare le lavorazioni rinnovate, registrare quanto resta esistente e consegnare le indicazioni per il riavvio."]],
    checks: [["Supporti dopo le rimozioni", "Confrontare lo stato emerso con quello previsto e registrare eventuali opere ulteriori prima di eseguirle."], ["Raccordi tra vecchio e nuovo", "Controllare i dettagli concordati presso bocchette, scarichi, scala e bordo."], ["Tenuta delle parti lavorate", "Documentare le verifiche previste dal sistema, senza estendere l'esito alle reti non ispezionate."], ["Ritorno in servizio", "Concordare riempimento e regolazioni; registrare eventuali difetti residui estranei al perimetro dei lavori."]],
    exclusions: [["Consolidamenti strutturali", "Lesioni o cedimenti richiedono diagnosi e progetto; non sono riparati dalla semplice posa del rivestimento."], ["Reti non accessibili", "Tubazioni interrate e impianti conservati non si intendono sostituiti né integralmente verificati."], ["Rinnovo del giardino", "Pavimentazioni, verde e accessori restano esclusi salvo voci dedicate."]],
    faq: [["Si può mantenere la struttura?", "La decisione dipende dalle condizioni rilevate e dalle verifiche concordate. Le superfici visibili non descrivono da sole lo stato strutturale."], ["Bisogna svuotare la piscina?", "Modalità e opportunità dello svuotamento devono essere valutate per la vasca e il terreno reali prima dell'intervento."], ["Il nuovo rivestimento elimina le perdite?", "Solo se la causa rientra nelle superfici e nei raccordi trattati. Occorre distinguere perdite della vasca e dell'impianto."], ["Posso cambiare scala o profondità?", "Sono modifiche da progettare e quotare, non comprese automaticamente nel rinnovo delle finiture."], ["Si può riutilizzare il filtro?", "Si valutano stato, prestazioni e compatibilità con la configurazione finale prima di confermarne il mantenimento."], ["Cosa succede se emergono problemi nascosti?", "Si documenta l'anomalia e si concordano lavorazioni, prezzo e tempi aggiuntivi prima di procedere."], ["Quando potrò riutilizzare la vasca?", "Dopo completamento e controlli previsti, rispettando i tempi del sistema posato e il programma di riavvio."], ["La garanzia copre tutta la piscina?", "Le condizioni si riferiscono alle opere eseguite e ai prodotti forniti. Le parti conservate vanno identificate nel verbale."]],
    rows: [["Preparazione", "Rimozioni selettive e preparazione delle porzioni di vasca concordate", 2800], ["Rinnovo", "Ripristini, raccordi e nuove finiture del perimetro dimostrativo", 6200], ["Riavvio", "Verifiche sulle parti rinnovate e riavvio programmato della piscina", 900]],
  },
  rivestimento: {
    title: "Rivestimento e impermeabilizzazione", hero: "La bellezza dell'acqua.\nComincia dalla superficie.",
    subtitle: "Supporto, tenuta e finitura: un sistema continuo, curato anche nei dettagli.",
    cover: "/module-art/piscine-posa-pvc.jpg", detail: "/module-art/piscine-posa-pvc.jpg",
    scope: "La proposta identifica superfici da trattare, preparazione, sistema di tenuta e rivestimento. PVC armato, membrane e finiture incollate sono soluzioni differenti: materiali e sequenze effettive devono essere descritti. Riparazioni strutturali, reti interrate e opere al bordo restano distinte.",
    specs: [["Un supporto pronto", "Rilevare superfici, planarità e parti incoerenti; definire rimozioni e ripristini necessari per il sistema scelto, comprese scale e zone di raccordo."], ["Un sistema dichiarato", "Precisare tipologia, componenti, finitura e modalità di posa. La proposta non somma automaticamente cicli impermeabilizzanti alternativi."], ["Dettagli che contano", "Definire continuità presso spigoli, giunti, fari, bocchette e scarichi. Compatibilità di flange, guarnizioni e pezzi speciali va confermata."], ["Tempi prima dell'acqua", "Posa, eventuale maturazione e riempimento seguono le indicazioni del sistema. Condizioni del supporto e ambiente influenzano la programmazione."]],
    stages: [["Mappatura delle superfici", "Misurare fondo, pareti e scala, registrando difetti e punti singolari da trattare."], ["Preparazione del supporto", "Rimuovere le parti previste e realizzare i ripristini concordati prima della posa."], ["Tenuta e finitura", "Applicare il sistema scelto e completare i raccordi compatibili con le dotazioni conservate."], ["Verifica e riempimento", "Registrare i controlli previsti e concordare riempimento, pulizia e manutenzione delle nuove superfici."]],
    checks: [["Superficie preparata", "Verificare le condizioni richieste dal sistema prima di coprire il supporto."], ["Continuità della posa", "Riscontrare sormonti o giunzioni, angoli e raccordi secondo la tecnologia effettivamente scelta."], ["Attraversamenti", "Controllare le chiusure accessibili di fari, bocchette e scarichi interessati dalla lavorazione."], ["Finitura e consegna", "Registrare difetti visibili, esito delle verifiche concordate e istruzioni per il primo riempimento."]],
    exclusions: [["Lesioni e movimenti", "Consolidamenti o correzioni di cedimenti richiedono valutazioni e opere specifiche."], ["Perdite della rete", "Ricerca e riparazione delle perdite nelle tubazioni sono prestazioni separate."], ["Dotazioni e bordo", "Fari, skimmer, scale e pavimentazioni esterne si sostituiscono solo se elencati."]],
    faq: [["PVC armato o finitura incollata?", "La scelta dipende da supporto, dettagli, aspetto desiderato e compatibilità. Il preventivo deve identificare un sistema preciso."], ["Occorre rimuovere tutto il rivestimento?", "Dipende dalle condizioni e dal ciclo scelto. Le rimozioni incluse devono essere misurate e descritte."], ["Il colore sarà quello della foto?", "La foto è illustrativa. Colore e texture si approvano su campione o scheda; luce e acqua cambiano la percezione."], ["I giunti vengono coperti?", "Il trattamento dei giunti si definisce nel dettaglio del sistema e non si improvvisa per uniformare la superficie."], ["Sono compresi scale e gradini?", "Solo se superfici, raccordi e finitura risultano nella misurazione e nella fornitura."], ["Quando si può riempire?", "Dopo i controlli e i tempi prescritti per i materiali posati, secondo la programmazione dell'intervento."], ["Questo intervento risolve ogni perdita?", "No. La tenuta delle superfici trattate è distinta da quella di tubazioni, apparecchiature e componenti non interessati."], ["Come si pulisce il rivestimento?", "Si seguono le istruzioni del produttore per detergenti, strumenti e gestione dell'acqua, consegnate con il sistema installato."]],
    rows: [["Supporto", "Preparazione e ripristini delle superfici interne misurate", 1800], ["Rivestimento", "Sistema di tenuta e finitura scelto per la configurazione dimostrativa", 5400], ["Raccordi", "Dettagli degli attraversamenti previsti e verifiche prima del riempimento", 850]],
  },
  impianti: {
    title: "Adeguamento impianti", hero: "Acqua in movimento.\nGestione più chiara.",
    subtitle: "Filtrazione, circolazione e trattamento: componenti coordinati per la tua vasca.",
    cover: "/pdf-stock/piscine/locale-tecnico.jpg", detail: "/pdf-stock/piscine/tecnica-filtrazione.jpg",
    scope: "L'adeguamento riguarda pompa, filtro, trattamento e collegamenti espressamente indicati. Volume della vasca, percorso delle tubazioni e condizioni del locale tecnico guidano la configurazione. Il rinnovo delle apparecchiature non implica la sostituzione di tutte le reti esistenti.",
    specs: [["Partire dal circuito reale", "Rilevare volume utile, riprese, mandate, diametri e percorso delle tubazioni. Prestazioni richieste e perdite del circuito orientano la scelta della pompa."], ["Filtro e pompa insieme", "Verificare l'abbinamento di apparecchiature, mezzo filtrante e collegamenti. Ingombri e spazi di manutenzione devono restare accessibili."], ["Trattamento identificato", "Precisare tecnologia, sensori e dosaggio eventualmente previsti. Un sistema automatico richiede comunque controlli e manutenzione."], ["Un locale gestibile", "Organizzare valvole, comandi e accessi, verificando le predisposizioni necessarie. Scarichi e alimentazioni elettriche si descrivono separatamente."]],
    stages: [["Rilievo del circuito", "Raccogliere dati della vasca e identificare apparecchiature, linee e anomalie esistenti."], ["Configurazione concordata", "Definire componenti, collegamenti, alimentazioni e parti da conservare."], ["Sostituzione programmata", "Concordare il fermo della piscina ed eseguire rimozioni e installazioni previste."], ["Regolazione e istruzioni", "Verificare le funzioni previste, identificare valvole e comandi e spiegare pulizia e controlli periodici."]],
    checks: [["Collegamenti accessibili", "Controllare raccordi, sostegni e assenza di perdite nei tratti lavorati secondo le prove concordate."], ["Funzionamento del circuito", "Riscontrare flusso, rumori anomali e indicazioni strumentali nelle condizioni di prova."], ["Regolazione", "Verificare impostazioni, timer, sensori e funzioni di trattamento effettivamente forniti."], ["Manutenzione accessibile", "Dimostrare accesso a prefiltro, valvole e componenti previsti senza attribuire prestazioni a parti non verificate."]],
    exclusions: [["Reti interrate", "Ricerca perdite, scavi e sostituzione delle linee nascoste richiedono voci specifiche."], ["Opere elettriche e scarichi", "Quadri, alimentazioni e scarichi non descritti restano esclusi dall'adeguamento idraulico."], ["Servizi e consumabili", "Controllo remoto, ricambi e prodotti successivi al primo avviamento sono inclusi solo se concordati."]],
    faq: [["Una pompa più potente migliora la filtrazione?", "Non necessariamente: occorre verificare l'intero circuito e l'abbinamento con il filtro."], ["Posso conservare il filtro?", "Serve un riscontro su stato, caratteristiche e compatibilità con le nuove apparecchiature."], ["Il trattamento automatico elimina i controlli?", "No. Sensori, dosaggio e qualità dell'acqua richiedono gestione secondo le istruzioni dei componenti scelti."], ["Sono comprese nuove tubazioni?", "Soltanto per tratti, materiali e collegamenti elencati. Le linee interrate restano identificate come esistenti."], ["L'impianto sarà più silenzioso?", "Rumore e vibrazioni dipendono anche da posa, circuito e locale. Eventuali obiettivi devono essere valutati sul posto."], ["Posso controllarlo dal telefono?", "Solo se interfaccia, connettività e servizio sono previsti. Compatibilità e disponibilità della rete vanno verificate."], ["Quanto resterà ferma la piscina?", "Il fermo si programma in base a componenti, collegamenti e prove; eventuali imprevisti richiedono aggiornamento del programma."], ["Quali documenti riceverò?", "Elenco dei componenti, istruzioni, impostazioni concordate e documentazione applicabile alle opere effettuate."]],
    rows: [["Componenti", "Gruppo pompa e filtro della configurazione dimostrativa", 2400], ["Collegamenti", "Raccordi, valvole e posa sui tratti accessibili descritti", 1100], ["Regolazione", "Configurazione delle funzioni previste e istruzioni di conduzione", 450]],
  },
  accessori: {
    title: "Coperture e accessori", hero: "I dettagli giusti.\nOgni giorno in piscina.",
    subtitle: "Copertura, comandi e dotazioni scelti sulle misure della vasca e sulle tue abitudini.",
    cover: "/module-art/piscine-copertura-rullo.jpg", detail: "/module-art/piscine-copertura-rullo.jpg",
    scope: "Sono compresi solo gli accessori identificati per modello, dimensioni e funzione. Copertura termica, invernale o con funzione di sicurezza non sono equivalenti. Fissaggi, avvolgitore, alimentazioni e predisposizioni devono essere indicati; la fotografia di una piscina arredata è soltanto un riferimento d'ambiente.",
    specs: [["Misure e ostacoli", "Rilevare sagoma, bordo, scala, sfioro e spazio di manovra. Gli ingombri della copertura e del sistema di raccolta devono essere compatibili con l'uso quotidiano."], ["La funzione prima del modello", "Distinguere contenimento delle dispersioni, protezione stagionale e altre prestazioni documentate. La funzione di sicurezza non si presume dalla presenza del telo."], ["Fissaggi e predisposizioni", "Verificare supporti, ancoraggi e passaggi necessari. Motori, docce, luci o altri accessori richiedono collegamenti specifici da quotare."], ["Comandi comprensibili", "Definire apertura, chiusura, stoccaggio e pulizia. Limiti d'impiego e manutenzione sono quelli del prodotto effettivamente fornito."]],
    stages: [["Misura e scelta", "Confermare misure utili, funzione desiderata, ingombri e accessori della fornitura."], ["Verifica dei supporti", "Controllare le predisposizioni e identificare gli eventuali adeguamenti necessari prima del montaggio."], ["Posa delle dotazioni", "Montare solo i componenti elencati, coordinando fissaggi e collegamenti previsti."], ["Prova con il proprietario", "Mostrare uso, raccolta e manutenzione dell'accessorio e consegnare i documenti del modello scelto."]],
    checks: [["Misure e adattamento", "Verificare corrispondenza della fornitura, ingombri e compatibilità con bordo e scala."], ["Fissaggi previsti", "Riscontrare posa e condizioni dei supporti nelle zone interessate."], ["Movimento e comandi", "Provare le funzioni previste secondo le istruzioni, mantenendo libera l'area di movimento."], ["Limiti d'uso", "Confermare che il proprietario abbia ricevuto istruzioni e limiti prestazionali del prodotto."]],
    exclusions: [["Opere di predisposizione", "Rifacimento bordi, rinforzi, scavi e alimentazioni non elencati richiedono una proposta dedicata."], ["Prestazioni non dichiarate", "Funzioni antiannegamento, portata pedonale e automazioni non si intendono comprese senza prodotto e documentazione specifici."], ["Altre dotazioni", "Arredi, robot, riscaldamento e illuminazione presenti nelle immagini non fanno parte della fornitura salvo voce dedicata."]],
    faq: [["Quale copertura è adatta?", "La scelta parte dalla funzione richiesta e dalle misure reali, poi considera apertura, ingombri e manutenzione."], ["Una copertura termica è una protezione di sicurezza?", "La funzione di sicurezza deve essere espressamente documentata per il prodotto e la posa scelti; non deriva dal solo nome copertura."], ["È compreso l'avvolgitore?", "Solo se descritto con dimensioni, supporti e montaggio nella proposta."], ["Serve elettricità?", "Dipende dall'accessorio. Alimentazione, comando e collegamenti devono essere verificati e definiti prima della posa."], ["Si può montare sul bordo esistente?", "Occorre verificarne forma, condizioni e compatibilità con i fissaggi previsti."], ["Sono compresi robot e doccia?", "Sono dotazioni autonome: modello, collegamenti e installazione devono risultare nel computo."], ["La copertura elimina la manutenzione?", "No. Vasca, acqua e accessorio continuano a richiedere i controlli e le cure indicate."], ["Come si conserva fuori stagione?", "Pulizia, asciugatura e stoccaggio dipendono dal materiale e dalle istruzioni del produttore, da consegnare con l'accessorio."]],
    rows: [["Copertura", "Copertura stagionale e dotazioni della configurazione dimostrativa", 1900], ["Montaggio", "Fissaggi e montaggio sui supporti verificati della fornitura", 550], ["Consegna", "Prova funzionale, spiegazione d'uso e documenti del prodotto", 180]],
  },
  manutenzione: {
    title: "Manutenzione stagionale", hero: "Ogni stagione.\nLa cura che serve.",
    subtitle: "Apertura, chiusura e visite concordate: una piscina seguita con attività riconoscibili.",
    cover: "/pdf-stock/piscine/collaudo.jpg", detail: "/pdf-stock/piscine/locale-tecnico.jpg",
    scope: "Il servizio riguarda le visite e le attività elencate: apertura, chiusura o manutenzione periodica hanno perimetri diversi. Numero di accessi, prodotti compresi, ricambi e chiamate extra devono essere espliciti. Il controllo eseguito durante una visita non garantisce le condizioni dell'acqua per l'intera stagione.",
    specs: [["Conoscere la piscina", "Registrare volume, apparecchiature, trattamento e stato della copertura. Annotare le criticità già note e l'ultima messa in servizio."], ["Un servizio definito", "Specificare apertura, chiusura o frequenza delle visite, con attività e responsabilità tra un accesso e il successivo."], ["Controlli tracciabili", "Raccogliere i riscontri previsti su acqua, circolazione e componenti accessibili. Annotare prodotti impiegati e anomalie da valutare separatamente."], ["Ricambi senza sorprese", "Distinguere pulizia e regolazione dalle riparazioni. I pezzi da sostituire vengono identificati e concordati prima dell'acquisto."]],
    stages: [["Programmazione della visita", "Confermare servizio richiesto, accessi, disponibilità delle utenze e condizioni iniziali."], ["Pulizia e attività previste", "Eseguire le operazioni concordate su vasca, copertura e apparecchiature accessibili."], ["Riscontri e regolazioni", "Registrare misure e funzioni verificate, segnalando ricambi o interventi ulteriori."], ["Rapporto e prossimo accesso", "Consegnare il riepilogo della visita e le indicazioni per il periodo successivo, con eventuale nuova data concordata."]],
    checks: [["Stato rilevato", "Annotare copertura, superfici e componenti accessibili, distinguendo usura e guasti segnalati."], ["Parametri misurati", "Registrare i parametri previsti con data della visita e riferimenti del trattamento utilizzato."], ["Funzioni verificate", "Riscontrare circolazione, prefiltro e comandi coinvolti nel servizio concordato."], ["Attività da proseguire", "Precisare controlli a carico del proprietario e anomalie che richiedono una valutazione dedicata."]],
    exclusions: [["Riparazioni e ricambi", "Ricerca guasti, parti di ricambio e riparazioni sono extra salvo indicazione esplicita."], ["Visite aggiuntive", "Urgenze, reperibilità e accessi oltre il programma non sono impliciti nel servizio stagionale."], ["Ripristini straordinari", "Acqua in condizioni anomale, perdite e interventi strutturali richiedono valutazione separata."]],
    faq: [["Apertura e chiusura sono entrambe comprese?", "Solo se indicate come attività distinte, precisando numero di visite e materiali inclusi."], ["Quante visite sono previste?", "La periodicità viene concordata in base a impianto, uso e servizio richiesto e deve risultare nella proposta."], ["Chi controlla l'acqua tra le visite?", "Il rapporto definisce le attività del proprietario. Una visita non sostituisce la gestione ordinaria della piscina."], ["I prodotti sono compresi?", "Solo quelli identificati nella fornitura, con quantità o limite concordato. Consumi ulteriori richiedono accordo."], ["La chiusura richiede sempre lo svuotamento?", "La procedura dipende dalla vasca, dal clima e dalle apparecchiature: si seguono le indicazioni applicabili alla configurazione reale."], ["Un guasto viene riparato subito?", "Prima si identifica il problema e si concordano ricambi, attività e costo; la manutenzione ordinaria non include qualsiasi riparazione."], ["Devo essere presente?", "Accesso, utenze e modalità di consegna del rapporto possono essere concordati, indicando un referente per le anomalie."], ["Riceverò un resoconto?", "Il rapporto riporta attività effettuate, riscontri, prodotti previsti e segnalazioni con le indicazioni per il successivo periodo."]],
    rows: [["Visita", "Accesso stagionale programmato: apertura o chiusura da specificare", 180], ["Cura ordinaria", "Pulizia e controlli dei componenti accessibili previsti nel servizio", 160], ["Materiali e rapporto", "Materiali del pacchetto dimostrativo e rapporto delle attività effettuate", 80]],
  },
} satisfies Record<string, PscEditorialContent>;
