-- ════════════════════════════════════════════════════════════════
-- TABELLA 2: Fatture
-- ════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  invoice_number     TEXT,
  invoice_year       INTEGER DEFAULT EXTRACT(YEAR FROM NOW()),
  progressive_number INTEGER,
  document_type TEXT NOT NULL DEFAULT 'invoice',
  status TEXT NOT NULL DEFAULT 'draft',
  client_id           UUID REFERENCES marketing_contacts(id),
  client_company_name TEXT NOT NULL,
  client_vat_number   TEXT,
  client_fiscal_code  TEXT,
  client_address      TEXT,
  client_city         TEXT,
  client_zip          TEXT,
  client_country      TEXT DEFAULT 'IT',
  client_pec          TEXT,
  client_sdi_code     TEXT,
  client_email        TEXT,
  issue_date   DATE NOT NULL DEFAULT CURRENT_DATE,
  due_date     DATE,
  payment_date DATE,
  subtotal     NUMERIC(12,2) DEFAULT 0,
  tax_amount   NUMERIC(12,2) DEFAULT 0,
  total        NUMERIC(12,2) DEFAULT 0,
  paid_amount  NUMERIC(12,2) DEFAULT 0,
  payment_method TEXT,
  payment_terms  TEXT,
  payment_days   INTEGER,
  bank_iban      TEXT,
  order_id            UUID REFERENCES orders(id),
  quote_id            UUID,
  credited_invoice_id UUID REFERENCES invoices(id),
  notes       TEXT,
  footer_text TEXT,
  external_id       TEXT,
  external_provider TEXT,
  external_sync_at  TIMESTAMPTZ,
  external_status   TEXT,
  external_sdi_id   TEXT,
  external_xml_url  TEXT,
  pdf_url          TEXT,
  pdf_generated_at TIMESTAMPTZ,
  created_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
