-- Applicata direttamente in produzione dal pannello Supabase e ricostruita
-- qui dal registro migrazioni (supabase_migrations.schema_migrations),
-- per riallineare la cartella del repo alla storia reale del database.

-- ===== PAVIMENTI (pav_) =====
INSERT INTO public.platform_feature_flags (key, name, description, category, is_beta, default_value, plans_included, icon, sort_order, price_per_month)
VALUES ('modulo_pavimenti_attivo', 'Pavimenti & Resine',
  'Preventivatore posa pavimenti: gres, parquet, resine, microcemento e pietra — massetti, sottofondi, computo metrico e incentivi.',
  'modulo_vendita', true, false, '{pro,enterprise}'::text[], 'LayoutGrid', 109, 149)
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, category=EXCLUDED.category, is_beta=EXCLUDED.is_beta, plans_included=EXCLUDED.plans_included, icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order, price_per_month=EXCLUDED.price_per_month;

CREATE TABLE IF NOT EXISTS public.pav_listino_capitoli (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, nome text NOT NULL, ordine int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pav_listino_voci (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, capitolo_id uuid REFERENCES public.pav_listino_capitoli(id) ON DELETE SET NULL, codice text, descrizione text NOT NULL, unita_misura text NOT NULL DEFAULT 'cad', costo_materiali numeric NOT NULL DEFAULT 0, costo_manodopera numeric NOT NULL DEFAULT 0, ricarico_pct numeric NOT NULL DEFAULT 0, prezzo_unitario numeric NOT NULL DEFAULT 0, articolo_id uuid, tariffa_id uuid, note text, ordine int NOT NULL DEFAULT 0, fonte text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pav_progetti (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, code text, stato text NOT NULL DEFAULT 'bozza', tipo_intervento text, numero_ambienti int, tipo_materiale text, cliente_nome text, cliente_cognome text, cliente_email text, cliente_telefono text, cantiere_indirizzo text, cantiere_citta text, cantiere_provincia text, cantiere_cap text, immobile_tipo text, immobile_superficie_mq numeric, immobile_anno int, immobile_piani int, massimale_detrazione numeric, opportunita_id uuid, cliente_id uuid, template_id uuid, sconto_pct numeric NOT NULL DEFAULT 0, iva_pct numeric NOT NULL DEFAULT 22, detrazione_pct numeric NOT NULL DEFAULT 0, totale_imponibile numeric NOT NULL DEFAULT 0, totale numeric NOT NULL DEFAULT 0, note text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
DO $$ BEGIN ALTER TABLE public.pav_progetti ADD CONSTRAINT pav_progetti_stato_chk CHECK (stato IN ('bozza','da_consegnare','consegnato','in_valutazione','accettato','rifiutato','scaduto','archiviato')) NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS public.pav_computo_voci (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), progetto_id uuid NOT NULL REFERENCES public.pav_progetti(id) ON DELETE CASCADE, company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, capitolo_nome text NOT NULL DEFAULT 'Generale', descrizione text NOT NULL, unita_misura text NOT NULL DEFAULT 'cad', quantita numeric NOT NULL DEFAULT 0, prezzo_unitario numeric NOT NULL DEFAULT 0, costo_materiali numeric NOT NULL DEFAULT 0, costo_manodopera numeric NOT NULL DEFAULT 0, sconto_pct numeric NOT NULL DEFAULT 0, importo numeric NOT NULL DEFAULT 0, margine_eur numeric NOT NULL DEFAULT 0, margine_pct numeric NOT NULL DEFAULT 0, listino_voce_id uuid, ordine int NOT NULL DEFAULT 0, fonte text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pav_progetti_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), progetto_id uuid NOT NULL REFERENCES public.pav_progetti(id) ON DELETE CASCADE, company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, tipo text NOT NULL DEFAULT 'situazione', url text NOT NULL, caption text, ordine int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pav_template_pdf (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, logo_url text, color_primary text DEFAULT '#1E3A5F', color_secondary text DEFAULT '#F97316', color_accent text DEFAULT '#16A34A', color_text text DEFAULT '#212529', chi_siamo text, chi_siamo_foto_url text, esigenze jsonb DEFAULT '[]'::jsonb, soluzione jsonb DEFAULT '[]'::jsonb, usp jsonb DEFAULT '[]'::jsonb, testimonianze jsonb DEFAULT '[]'::jsonb, cronoprogramma jsonb DEFAULT '[]'::jsonb, consulente_default jsonb, cover_title text, cover_subtitle text, cover_image_url text, payment_terms_text text, validity_text text, footer_text text, show_chi_siamo boolean DEFAULT true, show_cronoprogramma boolean DEFAULT true, show_margine boolean DEFAULT false, ragione_sociale text, indirizzo_completo text, telefono text, email text, partita_iva text, font_family text DEFAULT 'helvetica', show_footer_version boolean DEFAULT true, show_footer_legal boolean DEFAULT false, cover_logo_position text DEFAULT 'top_left', cover_text_color text DEFAULT '#FFFFFF', cover_overlay_opacity numeric DEFAULT 0.4, garanzie jsonb DEFAULT '[]'::jsonb, faq jsonb DEFAULT '[]'::jsonb, percorso jsonb DEFAULT '[]'::jsonb, show_garanzie boolean DEFAULT true, show_percorso boolean DEFAULT true, cover_title_size numeric DEFAULT 30, cover_text_align text DEFAULT 'left', default_iva_pct numeric DEFAULT 22, default_detrazione_pct numeric DEFAULT 0, default_validita_giorni integer DEFAULT 30, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_pav_progetti_company ON public.pav_progetti(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pav_computo_progetto ON public.pav_computo_voci(progetto_id, ordine);
CREATE INDEX IF NOT EXISTS idx_pav_listino_voci_company ON public.pav_listino_voci(company_id, capitolo_id, ordine);
CREATE INDEX IF NOT EXISTS idx_pav_media_progetto ON public.pav_progetti_media(progetto_id, ordine);
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['pav_listino_capitoli','pav_listino_voci','pav_progetti','pav_computo_voci','pav_progetti_media','pav_template_pdf'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format($q$DROP POLICY IF EXISTS "pav super admin all" ON public.%I$q$, t);
  EXECUTE format($q$CREATE POLICY "pav super admin all" ON public.%I FOR ALL USING (has_role(auth.uid(),'super_admin'::app_role)) WITH CHECK (has_role(auth.uid(),'super_admin'::app_role))$q$, t);
  EXECUTE format($q$DROP POLICY IF EXISTS "pav company members" ON public.%I$q$, t);
  EXECUTE format($q$CREATE POLICY "pav company members" ON public.%I FOR ALL TO authenticated USING (company_id = get_user_company_id(auth.uid())) WITH CHECK (company_id = get_user_company_id(auth.uid()))$q$, t);
END LOOP; END $$;

-- ===== PISCINE (pis_) =====
INSERT INTO public.platform_feature_flags (key, name, description, category, is_beta, default_value, plans_included, icon, sort_order, price_per_month)
VALUES ('modulo_piscine_attivo', 'Piscine',
  'Preventivatore piscine interrate e fuori terra: scavo, struttura, impermeabilizzazione, impianto, filtrazione e coperture — computo metrico.',
  'modulo_vendita', true, false, '{pro,enterprise}'::text[], 'Waves', 110, 149)
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description, category=EXCLUDED.category, is_beta=EXCLUDED.is_beta, plans_included=EXCLUDED.plans_included, icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order, price_per_month=EXCLUDED.price_per_month;

CREATE TABLE IF NOT EXISTS public.pis_listino_capitoli (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, nome text NOT NULL, ordine int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pis_listino_voci (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, capitolo_id uuid REFERENCES public.pis_listino_capitoli(id) ON DELETE SET NULL, codice text, descrizione text NOT NULL, unita_misura text NOT NULL DEFAULT 'cad', costo_materiali numeric NOT NULL DEFAULT 0, costo_manodopera numeric NOT NULL DEFAULT 0, ricarico_pct numeric NOT NULL DEFAULT 0, prezzo_unitario numeric NOT NULL DEFAULT 0, articolo_id uuid, tariffa_id uuid, note text, ordine int NOT NULL DEFAULT 0, fonte text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pis_progetti (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, code text, stato text NOT NULL DEFAULT 'bozza', tipo_intervento text, tipo_piscina text, tipo_costruzione text, cliente_nome text, cliente_cognome text, cliente_email text, cliente_telefono text, cantiere_indirizzo text, cantiere_citta text, cantiere_provincia text, cantiere_cap text, immobile_tipo text, immobile_superficie_mq numeric, immobile_anno int, immobile_piani int, massimale_detrazione numeric, opportunita_id uuid, cliente_id uuid, template_id uuid, sconto_pct numeric NOT NULL DEFAULT 0, iva_pct numeric NOT NULL DEFAULT 22, detrazione_pct numeric NOT NULL DEFAULT 0, totale_imponibile numeric NOT NULL DEFAULT 0, totale numeric NOT NULL DEFAULT 0, note text, created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
DO $$ BEGIN ALTER TABLE public.pis_progetti ADD CONSTRAINT pis_progetti_stato_chk CHECK (stato IN ('bozza','da_consegnare','consegnato','in_valutazione','accettato','rifiutato','scaduto','archiviato')) NOT VALID; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS public.pis_computo_voci (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), progetto_id uuid NOT NULL REFERENCES public.pis_progetti(id) ON DELETE CASCADE, company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, capitolo_nome text NOT NULL DEFAULT 'Generale', descrizione text NOT NULL, unita_misura text NOT NULL DEFAULT 'cad', quantita numeric NOT NULL DEFAULT 0, prezzo_unitario numeric NOT NULL DEFAULT 0, costo_materiali numeric NOT NULL DEFAULT 0, costo_manodopera numeric NOT NULL DEFAULT 0, sconto_pct numeric NOT NULL DEFAULT 0, importo numeric NOT NULL DEFAULT 0, margine_eur numeric NOT NULL DEFAULT 0, margine_pct numeric NOT NULL DEFAULT 0, listino_voce_id uuid, ordine int NOT NULL DEFAULT 0, fonte text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pis_progetti_media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), progetto_id uuid NOT NULL REFERENCES public.pis_progetti(id) ON DELETE CASCADE, company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE, tipo text NOT NULL DEFAULT 'situazione', url text NOT NULL, caption text, ordine int NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.pis_template_pdf (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_id uuid NOT NULL UNIQUE REFERENCES public.companies(id) ON DELETE CASCADE, logo_url text, color_primary text DEFAULT '#1E3A5F', color_secondary text DEFAULT '#F97316', color_accent text DEFAULT '#16A34A', color_text text DEFAULT '#212529', chi_siamo text, chi_siamo_foto_url text, esigenze jsonb DEFAULT '[]'::jsonb, soluzione jsonb DEFAULT '[]'::jsonb, usp jsonb DEFAULT '[]'::jsonb, testimonianze jsonb DEFAULT '[]'::jsonb, cronoprogramma jsonb DEFAULT '[]'::jsonb, consulente_default jsonb, cover_title text, cover_subtitle text, cover_image_url text, payment_terms_text text, validity_text text, footer_text text, show_chi_siamo boolean DEFAULT true, show_cronoprogramma boolean DEFAULT true, show_margine boolean DEFAULT false, ragione_sociale text, indirizzo_completo text, telefono text, email text, partita_iva text, font_family text DEFAULT 'helvetica', show_footer_version boolean DEFAULT true, show_footer_legal boolean DEFAULT false, cover_logo_position text DEFAULT 'top_left', cover_text_color text DEFAULT '#FFFFFF', cover_overlay_opacity numeric DEFAULT 0.4, garanzie jsonb DEFAULT '[]'::jsonb, faq jsonb DEFAULT '[]'::jsonb, percorso jsonb DEFAULT '[]'::jsonb, show_garanzie boolean DEFAULT true, show_percorso boolean DEFAULT true, cover_title_size numeric DEFAULT 30, cover_text_align text DEFAULT 'left', default_iva_pct numeric DEFAULT 22, default_detrazione_pct numeric DEFAULT 0, default_validita_giorni integer DEFAULT 30, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_pis_progetti_company ON public.pis_progetti(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pis_computo_progetto ON public.pis_computo_voci(progetto_id, ordine);
CREATE INDEX IF NOT EXISTS idx_pis_listino_voci_company ON public.pis_listino_voci(company_id, capitolo_id, ordine);
CREATE INDEX IF NOT EXISTS idx_pis_media_progetto ON public.pis_progetti_media(progetto_id, ordine);
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['pis_listino_capitoli','pis_listino_voci','pis_progetti','pis_computo_voci','pis_progetti_media','pis_template_pdf'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format($q$DROP POLICY IF EXISTS "pis super admin all" ON public.%I$q$, t);
  EXECUTE format($q$CREATE POLICY "pis super admin all" ON public.%I FOR ALL USING (has_role(auth.uid(),'super_admin'::app_role)) WITH CHECK (has_role(auth.uid(),'super_admin'::app_role))$q$, t);
  EXECUTE format($q$DROP POLICY IF EXISTS "pis company members" ON public.%I$q$, t);
  EXECUTE format($q$CREATE POLICY "pis company members" ON public.%I FOR ALL TO authenticated USING (company_id = get_user_company_id(auth.uid())) WITH CHECK (company_id = get_user_company_id(auth.uid()))$q$, t);
END LOOP; END $$;
