-- HR1a: Add organigramma and extended fields to hr_profili
ALTER TABLE public.hr_profili
  ADD COLUMN IF NOT EXISTS responsabile_id UUID REFERENCES public.hr_profili(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS mansione TEXT,
  ADD COLUMN IF NOT EXISTS reparto TEXT,
  ADD COLUMN IF NOT EXISTS posizione_organigramma INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS orario_inizio TIME DEFAULT '08:00',
  ADD COLUMN IF NOT EXISTS orario_fine TIME DEFAULT '17:00',
  ADD COLUMN IF NOT EXISTS pausa_pranzo_minuti INTEGER DEFAULT 60,
  ADD COLUMN IF NOT EXISTS giorni_lavorativi TEXT[] DEFAULT ARRAY['Lun','Mar','Mer','Gio','Ven'],
  ADD COLUMN IF NOT EXISTS ferie_anno_giorni DECIMAL(4,1) DEFAULT 26,
  ADD COLUMN IF NOT EXISTS permessi_anno_ore DECIMAL(5,1) DEFAULT 32,
  ADD COLUMN IF NOT EXISTS rol_anno_ore DECIMAL(5,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ferie_residue DECIMAL(4,1) DEFAULT 26,
  ADD COLUMN IF NOT EXISTS permessi_residui_ore DECIMAL(5,1) DEFAULT 32,
  ADD COLUMN IF NOT EXISTS rol_residuo_ore DECIMAL(5,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS badge_id TEXT,
  ADD COLUMN IF NOT EXISTS pin_timbratura TEXT,
  ADD COLUMN IF NOT EXISTS colore_avatar TEXT DEFAULT '#0EA5E9',
  ADD COLUMN IF NOT EXISTS nazionalita TEXT DEFAULT 'Italiana',
  ADD COLUMN IF NOT EXISTS stato_civile TEXT,
  ADD COLUMN IF NOT EXISTS luogo_nascita TEXT,
  ADD COLUMN IF NOT EXISTS citta_residenza TEXT,
  ADD COLUMN IF NOT EXISTS cap_residenza TEXT,
  ADD COLUMN IF NOT EXISTS telefono_privato TEXT,
  ADD COLUMN IF NOT EXISTS email_privata TEXT,
  ADD COLUMN IF NOT EXISTS contatto_emergenza_nome TEXT,
  ADD COLUMN IF NOT EXISTS contatto_emergenza_telefono TEXT,
  ADD COLUMN IF NOT EXISTS ccnl TEXT DEFAULT 'Edilizia',
  ADD COLUMN IF NOT EXISTS note_interne TEXT;
