-- Table
CREATE TABLE IF NOT EXISTS public.quote_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT 'Template Personalizzato',
  is_default BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  layout TEXT NOT NULL DEFAULT 'classic',
  logo_url TEXT,
  logo_position TEXT DEFAULT 'left',
  logo_size TEXT DEFAULT 'medium',
  show_logo BOOLEAN DEFAULT true,
  primary_color TEXT DEFAULT '#1E40AF',
  secondary_color TEXT DEFAULT '#3B82F6',
  accent_color TEXT DEFAULT '#DBEAFE',
  text_color TEXT DEFAULT '#111827',
  header_text_color TEXT DEFAULT '#FFFFFF',
  font_family TEXT DEFAULT 'helvetica',
  show_quote_number BOOLEAN DEFAULT true,
  show_validity_date BOOLEAN DEFAULT true,
  show_company_details BOOLEAN DEFAULT true,
  show_client_details BOOLEAN DEFAULT true,
  show_payment_terms BOOLEAN DEFAULT true,
  show_delivery_terms BOOLEAN DEFAULT true,
  show_notes BOOLEAN DEFAULT true,
  show_page_numbers BOOLEAN DEFAULT true,
  footer_text TEXT DEFAULT '',
  cover_tagline TEXT DEFAULT '',
  show_watermark BOOLEAN DEFAULT false,
  watermark_text TEXT DEFAULT 'OFFERTA RISERVATA',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
