ALTER TABLE automation_flows
  ADD COLUMN IF NOT EXISTS note TEXT,
  ADD COLUMN IF NOT EXISTS note_color TEXT,
  ADD COLUMN IF NOT EXISTS allow_reentry BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_multiple_opportunities BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS stop_on_reply BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'account',
  ADD COLUMN IF NOT EXISTS time_window_active BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS time_window_from TEXT DEFAULT '09:00',
  ADD COLUMN IF NOT EXISTS time_window_to TEXT DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS sender_name TEXT,
  ADD COLUMN IF NOT EXISTS sender_email TEXT;
