-- Sprint 7: Custom Sender Domain per azienda (GHL/ActiveCampaign style)
--
-- Ogni azienda può registrare il proprio dominio (es. rossicostruzioni.it) e,
-- dopo aver superato la verifica DNS su ENTRAMBI i provider (Elastic Email per
-- il marketing, SendGrid per il transactional), le email escono da
--   noreply@<dominio-azienda>
-- invece che dal dominio piattaforma.

CREATE TABLE IF NOT EXISTS public.company_email_domains (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  domain TEXT NOT NULL,
  from_email TEXT NOT NULL DEFAULT 'noreply',
  from_name TEXT,

  -- Elastic Email (marketing stream)
  ee_domain_added BOOLEAN NOT NULL DEFAULT false,
  ee_spf_verified BOOLEAN NOT NULL DEFAULT false,
  ee_dkim_verified BOOLEAN NOT NULL DEFAULT false,
  ee_tracking_verified BOOLEAN NOT NULL DEFAULT false,

  -- SendGrid (transactional stream) — 3 CNAMEs generated by /whitelabel/domains
  sg_domain_id TEXT,
  sg_cname_1_host TEXT,
  sg_cname_1_value TEXT,
  sg_cname_1_valid BOOLEAN NOT NULL DEFAULT false,
  sg_cname_2_host TEXT,
  sg_cname_2_value TEXT,
  sg_cname_2_valid BOOLEAN NOT NULL DEFAULT false,
  sg_cname_3_host TEXT,
  sg_cname_3_value TEXT,
  sg_cname_3_valid BOOLEAN NOT NULL DEFAULT false,

  -- Aggregate status — the domain is "verified" only when BOTH providers are happy
  is_verified BOOLEAN GENERATED ALWAYS AS (
    ee_spf_verified
    AND ee_dkim_verified
    AND sg_cname_1_valid
    AND sg_cname_2_valid
    AND sg_cname_3_valid
  ) STORED,
  is_active BOOLEAN NOT NULL DEFAULT false,
  verified_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (company_id, domain)
);

CREATE INDEX IF NOT EXISTS idx_ced_company
  ON public.company_email_domains (company_id);

CREATE INDEX IF NOT EXISTS idx_ced_active
  ON public.company_email_domains (company_id)
  WHERE is_active = true;

ALTER TABLE public.company_email_domains ENABLE ROW LEVEL SECURITY;

-- Read: any member of the company OR super_admin
DROP POLICY IF EXISTS ced_company_read ON public.company_email_domains;
CREATE POLICY ced_company_read ON public.company_email_domains
  FOR SELECT
  USING (
    public.has_role(auth.uid(), 'super_admin'::public.app_role)
    OR company_id IN (
      SELECT company_id FROM public.user_roles WHERE user_id = auth.uid()
    )
  );

-- Write: company owner/admin OR super_admin
DROP POLICY IF EXISTS ced_company_write ON public.company_email_domains;
CREATE POLICY ced_company_write ON public.company_email_domains
  FOR ALL
  USING (
    public.has_role(auth.uid(), 'super_admin'::public.app_role)
    OR company_id IN (
      SELECT company_id FROM public.user_roles
      WHERE user_id = auth.uid()
        AND role = 'company_admin'::public.app_role
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'super_admin'::public.app_role)
    OR company_id IN (
      SELECT company_id FROM public.user_roles
      WHERE user_id = auth.uid()
        AND role = 'company_admin'::public.app_role
    )
  );

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_company_email_domains_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_ced_updated_at ON public.company_email_domains;
CREATE TRIGGER trg_ced_updated_at
BEFORE UPDATE ON public.company_email_domains
FOR EACH ROW EXECUTE FUNCTION public.set_company_email_domains_updated_at();
