-- 4. Extend existing sales_targets with new columns
ALTER TABLE sales_targets
  ADD COLUMN IF NOT EXISTS assigned_to UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS year INTEGER,
  ADD COLUMN IF NOT EXISTS month INTEGER,
  ADD COLUMN IF NOT EXISTS target_amount DECIMAL(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS target_deals INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT NULL;
