ALTER TABLE public.companies
  ADD COLUMN IF NOT EXISTS business_name text,
  ADD COLUMN IF NOT EXISTS vat_number text,
  ADD COLUMN IF NOT EXISTS fiscal_code text,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS pec text,
  ADD COLUMN IF NOT EXISTS sdi_code text,
  ADD COLUMN IF NOT EXISTS legal_address text,
  ADD COLUMN IF NOT EXISTS legal_city text,
  ADD COLUMN IF NOT EXISTS legal_province text,
  ADD COLUMN IF NOT EXISTS legal_postal_code text,
  ADD COLUMN IF NOT EXISTS operational_address text,
  ADD COLUMN IF NOT EXISTS operational_city text,
  ADD COLUMN IF NOT EXISTS operational_province text,
  ADD COLUMN IF NOT EXISTS operational_postal_code text,
  ADD COLUMN IF NOT EXISTS website text,
  ADD COLUMN IF NOT EXISTS notes text;