-- 3. hr_profili
CREATE TABLE IF NOT EXISTS public.hr_profili (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  employee_id uuid REFERENCES public.employees(id) ON DELETE SET NULL,
  nome text NOT NULL,
  cognome text NOT NULL,
  codice_fiscale text,
  sesso text CHECK (sesso IN ('M','F','altro')),
  data_nascita date,
  telefono text,
  email text,
  indirizzo text,
  iban text,
  foto_url text,
  data_assunzione date,
  data_cessazione date,
  tipo_contratto text DEFAULT 'indeterminato' CHECK (tipo_contratto IN ('indeterminato','determinato','apprendistato','collaborazione','partita_iva','stagionale')),
  ore_settimanali numeric(5,2) DEFAULT 40,
  ore_giornaliere numeric(4,2) DEFAULT 8,
  orario_tipo text DEFAULT 'fisso' CHECK (orario_tipo IN ('fisso','turnista','flessibile')),
  sede_id uuid REFERENCES public.hr_sedi(id) ON DELETE SET NULL,
  matricola text,
  livello_ccnl text,
  note text,
  attivo boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
