// This file is automatically generated. Do not edit it directly.
// v2
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Sicurezza: le variabili d'ambiente sono obbligatorie — nessun fallback hardcoded
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "[Supabase] Variabili d'ambiente mancanti: VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY sono obbligatorie. Controlla il file .env."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// navigator.locks can stall indefinitely on mobile Safari, Android WebViews,
// and even desktop Chrome (especially with extensions), preventing
// onAuthStateChange(INITIAL_SESSION) from firing and leaving the app
// stuck on "Caricamento..." forever.
// Fix: always use a no-op lock to bypass the Web Locks API entirely.
// Trade-off: loses cross-tab session coordination, but avoids deadlocks.

async function lockNoOp<R>(
  _name: string,
  _acquireTimeout: number,
  fn: () => Promise<R>
): Promise<R> {
  return await fn();
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: lockNoOp,
  }
});